### ISSUE TITLE
502 Bad Gateway

### ISSUE THREAD

**Issue by MichielHuijse** [docksal/docksal#1726] opened 2022-10-31 16:18 UTC
**502 Bad Gateway**

Problem/feature description...

Often I get the : '502 Bad Gateway' message when loading a page.

**Steps to reproduce the issue:**

1. Go to the homepage of my Drupal site

**Describe the results you received:**

502 Bad Gateway openresty/1.19.9.1

**Describe the results you expected:**

200 -> homepage

**Output of `fin config`:**

<details>
  <summary>fin config output</summary>

```
---------------------
COMPOSE_PROJECT_NAME_SAFE: sitename
COMPOSE_FILE:
/home/username/.docksal/stacks/volumes-bind.yml
/home/username/.docksal/stacks/stack-default.yml
/home/username/sites/sitename/.docksal/docksal.yml
ENV_FILE:
/home/username/sites/sitename/.docksal/docksal.env

PROJECT_ROOT: /home/username/sites/sitename
DOCROOT: public_html
VIRTUAL_HOST: sitename.docksal.site
VIRTUAL_HOST_ALIASES: *.sitename.docksal.site
IP: 192.168.64.100

MySQL endpoint: 192.168.64.100:49160
Public URL:

Docker Compose configuration
---------------------
services:
  cli:
    dns:
    - 8.8.8.8
    - 9.9.9.9
    environment:
      BLACKFIRE_CLIENT_ID: null
      BLACKFIRE_CLIENT_TOKEN: null
      COMPOSER_ALLOW_XDEBUG: "0"
      COMPOSER_DEFAULT_VERSION: null
      COMPOSER_DISABLE_XDEBUG_WARN: "0"
      DOCROOT: public_html
      DRUSH_ALLOW_XDEBUG: "0"
      DRUSH_OPTIONS_URI: sitename.docksal.site
      GIT_USER_EMAIL: username.huijse@gmail.com
      GIT_USER_NAME: username Huijse
      HOST_GID: "1000"
      HOST_UID: "1000"
      MYSQL_DATABASE: default
      MYSQL_HOST: db
      MYSQL_PASSWORD: user
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
      PHP_IDE_CONFIG: null
      SECRET_ACQUIA_CLI_KEY: null
      SECRET_ACQUIA_CLI_SECRET: null
      SECRET_PLATFORMSH_CLI_TOKEN: null
      SECRET_SSH_PRIVATE_KEY: null
      SECRET_TERMINUS_TOKEN: null
      SSH_AUTH_SOCK: /.ssh-agent/proxy-socket
      VIRTUAL_HOST: sitename.docksal.site
      XDEBUG_CONFIG: client_host=192.168.64.1 remote_host=192.168.64.1
      XDEBUG_ENABLED: "0"
    extends:
      file: /home/username/.docksal/stacks/services.yml
      service: cli
    hostname: cli
    healthcheck:
      interval: 10s
    image: docksal/cli:php8.0-3.2
    labels:
      io.docksal.shell: bash
      io.docksal.user: docker
    logging:
      options:
        max-file: "10"
        max-size: 1m
    networks:
      default: null
    volumes:
    - type: volume
      source: docksal_ssh_agent
      target: /.ssh-agent
      read_only: true
      volume: {}
    - type: volume
      source: cli_home
      target: /home/docker
      volume: {}
    - type: bind
      source: /tmp/.docksal/sitename
      target: /tmp/.docksal/sitename
      read_only: true
      bind:
        create_host_path: true
    - type: volume
      source: project_root
      target: /var/www
      volume:
        nocopy: true
  db:
    dns:
    - 8.8.8.8
    - 9.9.9.9
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: null
      MYSQL_DATABASE: default
      MYSQL_INITDB_SKIP_TZINFO: null
      MYSQL_ONETIME_PASSWORD: null
      MYSQL_PASSWORD: user
      MYSQL_RANDOM_ROOT_PASSWORD: null
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
    extends:
      file: /home/username/.docksal/stacks/services.yml
      service: mariadb
    hostname: db
    healthcheck:
      interval: 10s
    image: docksal/mariadb:10.6-1.3
    logging:
      options:
        max-file: "10"
        max-size: 1m
    networks:
      default: null
    ports:
    - mode: ingress
      target: 3306
      protocol: tcp
    volumes:
    - type: volume
      source: db_data
      target: /var/lib/mysql
      volume: {}
    - type: volume
      source: project_root
      target: /var/www
      read_only: true
      volume:
        nocopy: true
  solr:
    dns:
    - 8.8.8.8
    - 9.9.9.9
    - 8.8.8.8
    - 9.9.9.9
    extends:
      file: /home/username/.docksal/stacks/services.yml
      service: solr
    hostname: solr
    healthcheck:
      interval: 10s
    image: docksal/solr:8.6-edge
    labels:
      io.docksal.cert-name: none
      io.docksal.virtual-host: solr.sitename.docksal.site,solr.sitename.docksal.site.*
      io.docksal.virtual-port: "8983"
    logging:
      options:
        max-file: "10"
        max-size: 1m
    networks:
      default: null
    volumes:
    - type: volume
      source: project_root
      target: /var/www
      read_only: true
      volume:
        nocopy: true
  web:
    depends_on:
      cli:
        condition: service_started
    dns:
    - 8.8.8.8
    - 9.9.9.9
    environment:
      APACHE_BASIC_AUTH_PASS: null
      APACHE_BASIC_AUTH_USER: null
      APACHE_DOCUMENTROOT: /var/www/public_html
      APACHE_FCGI_HOST_PORT: cli:9000
    extends:
      file: /home/username/.docksal/stacks/services.yml
      service: apache
    hostname: web
    healthcheck:
      interval: 10s
    image: docksal/apache:2.4-2.5
    labels:
      io.docksal.cert-name: none
      io.docksal.permanent: "false"
      io.docksal.project-root: /home/username/sites/sitename
      io.docksal.virtual-host: sitename.docksal.site,*.sitename.docksal.site,sitename.docksal.site.*
    logging:
      options:
        max-file: "10"
        max-size: 1m
    networks:
      default: null
    volumes:
    - type: volume
      source: project_root
      target: /var/www
      read_only: true
      volume:
        nocopy: true
networks:
  default:
    name: sitename_default
volumes:
  cli_home:
    name: sitename_cli_home
  db_data:
    name: sitename_db_data
  docksal_ssh_agent:
    name: docksal_ssh_agent
    external: true
  project_root:
    name: sitename_project_root
    driver: local
    driver_opts:
      device: /home/username/sites/sitename
      o: bind
      type: none
---------------------

```

</details>

<br>

**Output of `fin sysinfo`:**

<details>
  <summary>fin sysinfo output</summary>

  ```
in sysinfo

███  DOCKSAL
Docksal version: v1.17.0
fin version:     1.110.1

███  OS
Linux Ubuntu 20.04
Linux username-Latitude-E6420 5.4.0-131-generic #147-Ubuntu SMP Fri Oct 14 17:07:22 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

███  ENVIRONMENT
MODE : Linux Kernel
DOCKER_HOST : 

███  DOCKER
Expected client version: 20.10.12
Expected server version: 20.10.12

Installed versions:

Client: Docker Engine - Community
 Version:           20.10.12
 API version:       1.41
 Go version:        go1.16.12
 Git commit:        e91ed57
 Built:             Mon Dec 13 11:45:33 2021
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.12
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.16.12
  Git commit:       459d0df
  Built:            Mon Dec 13 11:43:42 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.8
  GitCommit:        9cd3357b7fd7218e4aec3eae239db1f68a5a6ec6
 runc:
  Version:          1.1.4
  GitCommit:        v1.1.4-0-g5fd4c4d
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0

███  DOCKER COMPOSE
Expected version:  2.1.0
Installed version: v2.1.0

███  DOCKSAL: PROJECTS
project    STATUS                         virtual host                                                            project root
frederik   Exited (0) 53 minutes ago      othersitename.docksal.site,*.othersitename.docksal.site,othersitename.docksal.site.*   /home/username/sites/othersitename
sitename     Up 15 minutes (healthy)        sitename.docksal.site,*.sitename.docksal.site,sitename.docksal.site.*         /home/username/sites/sitename
newtest    Exited (0) About an hour ago   newtest.docksal.site,*.newtest.docksal.site,newtest.docksal.site.*      /home/username/sites/newtest
drupal9    Exited (0) 47 hours ago        drupal9.docksal.site,*.drupal9.docksal.site,drupal9.docksal.site.*      /home/username/sites/drupal9

███  DOCKSAL: VIRTUAL HOSTS
*.sitename.docksal.site
solr.sitename.docksal.site.*
solr.sitename.docksal.site
sitename.docksal.site.*
sitename.docksal.site

███  DOCKSAL: NETWORKING

DOCKSAL_IP: 192.168.64.100
DOCKSAL_HOST_IP: 192.168.64.1
DOCKSAL_VHOST_PROXY_IP: 
DOCKSAL_DNS_IP: 
DOCKSAL_DNS_DISABLED: 1
DOCKSAL_NO_DNS_RESOLVER: 1
DOCKSAL_DNS_UPSTREAM: 
DOCKSAL_DNS_DOMAIN: docksal.site

███  DOCKSAL: CONNECTIVITY

Host to 192.168.64.100:         PASS
Container to 192.168.64.100:    PASS
Container to 192.168.64.1:      PASS

Checking connectivity to http://dns-test.docksal.site...
Host: PASS
Containers: PASS

███  DOCKER: RUNNING CONTAINERS
CONTAINER ID   IMAGE                      COMMAND                  CREATED             STATUS                    PORTS                                                    NAMES
19ff77508c37   docksal/vhost-proxy:1.8    "docker-entrypoint.s…"   17 minutes ago      Up 17 minutes (healthy)   192.168.64.100:80->80/tcp, 192.168.64.100:443->443/tcp   docksal-vhost-proxy
daf0692e7838   docksal/solr:8.6-edge      "docker-entrypoint.s…"   20 minutes ago      Up 15 minutes (healthy)   8983/tcp                                                 sitename_solr_1
8d886528847f   docksal/ssh-agent:1.4      "docker-entrypoint.s…"   54 minutes ago      Up 54 minutes (healthy)                                                            docksal-ssh-agent
3317f091d43c   docksal/apache:2.4-2.5     "httpd-foreground"       About an hour ago   Up 15 minutes (healthy)   80/tcp, 443/tcp                                          sitename_web_1
1aeaa5914dbe   docksal/cli:php8.0-3.2     "/opt/startup.sh sup…"   About an hour ago   Up 15 minutes (healthy)   22/tcp, 3000/tcp, 9000/tcp                               sitename_cli_1
cf3f5ff9f6fb   docksal/mariadb:10.6-1.3   "docker-entrypoint.s…"   25 hours ago        Up 15 minutes (healthy)   0.0.0.0:49160->3306/tcp, :::49160->3306/tcp              sitename_db_1

███  DOCKER: NETWORKS
NETWORK ID     NAME              DRIVER    SCOPE
b013af1b1fa7   _default          bridge    local
23f2182f31a1   bridge            bridge    local
50ef5367e26d   drupal9_default   bridge    local
32db6cc03e56   host              host      local
d3799b3283a6   newtest_default   bridge    local
5e2ec7114f99   none              null      local
4ce84c154f67   sitename_default    bridge    local

███  HDD Usage
Filesystem      Size  Used Avail Use% Mounted on
udev            3,8G     0  3,8G   0% /dev
tmpfs           784M  2,7M  781M   1% /run
/dev/sda5       109G   93G  9,9G  91% /
tmpfs           3,9G   79M  3,8G   3% /dev/shm
tmpfs           5,0M  4,0K  5,0M   1% /run/lock
tmpfs           3,9G     0  3,9G   0% /sys/fs/cgroup
/dev/loop0      115M  115M     0 100% /snap/core/13741
/dev/loop3       56M   56M     0 100% /snap/core18/2566
/dev/loop2       56M   56M     0 100% /snap/core18/2560
/dev/loop5       73M   73M     0 100% /snap/core22/310
/dev/loop4       64M   64M     0 100% /snap/core20/1623
/dev/loop1      115M  115M     0 100% /snap/core/13886
/dev/loop6      2,7M  2,7M     0 100% /snap/gnome-calculator/920
/dev/loop7      1,5M  1,5M     0 100% /snap/gnome-system-monitor/181
/dev/loop8      219M  219M     0 100% /snap/gnome-3-34-1804/77
/dev/loop9      415M  415M     0 100% /snap/gnome-42-2204/29
/dev/loop10      92M   92M     0 100% /snap/gtk-common-themes/1535
/dev/loop13     512K  512K     0 100% /snap/gnome-characters/781
/dev/loop11     251M  251M     0 100% /snap/zoom-client/170
/dev/loop12      46M   46M     0 100% /snap/snap-store/599
/dev/loop15     321M  321M     0 100% /snap/vlc/3078
/dev/loop14     296M  296M     0 100% /snap/vlc/2344
/dev/loop16     768K  768K     0 100% /snap/gnome-logs/115
/dev/loop17     347M  347M     0 100% /snap/gnome-3-38-2004/119
/dev/loop18     113M  113M     0 100% /snap/slack/66
/dev/loop19     128K  128K     0 100% /snap/bare/5
/dev/loop20      82M   82M     0 100% /snap/gtk-common-themes/1534
/dev/loop21     113M  113M     0 100% /snap/slack/67
tmpfs           784M  4,0K  784M   1% /run/user/129
tmpfs           784M   32K  784M   1% /run/user/1000
  ```

</details>

**Comment by jphat** [comment] 2023-02-02 17:18
have you tried `fin system reset` see https://github.com/docksal/docksal/issues/1693

**Comment by ivnish** [comment] 2023-03-13 08:32
Duplicate of https://github.com/docksal/docksal/issues/1693

**Comment by lmakarov** [comment] 2023-03-14 15:06
Try updating to the latest release and see if that make any difference:

```bash
DOCKSAL_VERSION=v1.18.0 fin update
```

If that does not help, please post a comment in #1693 with the steps that **maintainers** can use to reproduce the issue.

**Closed by lmakarov** 2023-03-14 15:06 UTC
