### ISSUE TITLE
Docksal 1.17.0: 502 Bad Gateway after project start

### ISSUE THREAD

**Issue by ivnish** [docksal/docksal#1693] opened 2022-07-12 08:38 UTC
After upgrade to docksal 1.17.0 sometimes (not every day) after project start I get 502 error (502 Bad Gateway, openresty/1.19.9.1)

fin p start (again) fix this. How to debug this problem?

**Comment by fullheart** [comment] 2022-07-17 18:36
I have exactly the same problem.

Thank you for investigat in this problem and this GREAT tool!

**Comment by thunderjet12** [comment] 2022-08-08 08:02
same here  endeavouros "Arch Linux based' distro   earlier this year i used docksal "Probably 1.16..." in garuda Linux "also Arch Linux based" and it installed and worked like charm best experience and less resources with a docker tool  i have had 
the workaround mention above to re run " fin p start " worked although i see some  warning  and deprecated with WordPress 6 but updated to 6.0.1 and activated twenty twenty two "a blocks theme support"
and  i hope docksal  get fixed soon

**Comment by danbohea** [comment] 2022-08-10 08:49
I have the same issue.
Docksal 1.17.0
Kubuntu 22.04
Running `fin start` again seems to fix the issue.

**Comment by fullheart** [comment] 2022-08-10 19:13
Here more information to reproduce the problem:

**How reproduce**
This error happen on my system (`Ubuntu 20.04.4 LTS`) when I stop and start with `fin start` /  `fin stop` the project **multiple times**.

**Analyse problem**
In the docker logs of the `web` container, I see, that nginx don't finde the `php-fpm` upstream to forward php script to `php-fpm` process of the cli container.


Output of command: **`docker logs --follow ..._web_1`**
```
2022-08-10 18:53:52 | Passing execution to: nginx -g daemon off;
2022/08/10 18:53:52 [emerg] 1#1: host not found in upstream "php-fpm:9000" in /etc/nginx/includes/upstream.conf:4
nginx: [emerg] host not found in upstream "php-fpm:9000" in /etc/nginx/includes/upstream.conf:4
```

**Workaround**: When this error happen I run `fin start` again, and then the web container can find the upstream server for `php-fpm`

**My opinion, what cause this problem**
My It seems like its a timing problem (the `php-fpm` service in the `cli` container isn't sometimes ready over Port 9000, when nginx is starting).

**Comment by matthensley1** [comment] 2022-08-16 16:53
This has been a pretty consistent problem for me since upgrading to 1.17 as well. Unfortunately, running fin start again doesn't usually resolve it for me - I end up having to dump the db and restart containers (and then re-import the db) to get things talking to each other.

**Comment by leevh** [comment] 2022-08-21 22:11
> This has been a pretty consistent problem for me since upgrading to 1.17 as well. Unfortunately, running fin start again doesn't usually resolve it for me - I end up having to dump the db and restart containers (and then re-import the db) to get things talking to each other.

Same for me.  Also restarting my machine seems to help as well.

**Comment by ChrisScrumping** [comment] 2022-09-15 15:29
I ran in to the same issue. Again mixed results with restarting, resetting and rebooting none seemed to work reliably.

In the end I ran ```docker container attach docksal-vhost-proxy``` and got

[error] 171#171: *5 no live upstreams while connecting to upstream, client: 192.168.64.1, server: mysite.docksal.site, request: "GET / HTTP/1.1", upstream: "http://mysite-web/", host: "mysite.docksal.site"

I had the resolver disabled (can't remember why probably a previous issue i ran into) https://docs.docksal.io/core/system-dns/ once I turned the back on and ```fin system reset``` everything cam back to life.

Could be a coincidence and it will break again tomorrow but for now seems okay.

**Comment by justcaldwell** [comment] 2022-09-15 18:51
Maybe you disabled the resolver because it's deprecated(?). That's what I did, due to the warning that displayed anytime I ran a fin command:
```
 WARNING:  '.docksal' base domain and local DNS resolver are deprecated
           Please update your Docksal and project configuration
           See https://docs.docksal.io/stack/configuration-variables/#docksal-dns-disabled
```
I tried re-enabling just now. It **briefly seemed** like it might work, but the warning came back, and the issues (502 bad gateway, proxy error, etc.) soon returned any time I stop/start a project.

For me, the only fix has been to completely remove the vm and start over each time.

**Comment by ChrisScrumping** [comment] 2022-09-16 12:49
Yes you're right @justcaldwell the depreciated notice is back now so must be a coincidence that it started working after removing that.

Maybe doing a ```fin system reset``` helped....

**Comment by justcaldwell** [comment] 2022-09-16 16:57
I think you're right @ChrisScrumping. Rather than removing the vm, I've started dumping the db, doing `fin system reset`, then re-import the db. I think that's what @matthensley1 was saying above. Seems to work reasonably well.

Not ideal for sure, but less time-intensive than rebuilding the vm.

**Comment by alexryall** [comment] 2023-02-24 16:47
Getting a similar issue, for me I think it's related to MacOS Ventura and possibly linked to this issue https://github.com/docksal/docksal/issues/1727 although the fix for that doesn't fix this.

**Comment by ivnish** [comment] 2023-03-13 08:37
`fin p reset` doesn't help me. Some services (mailhog, pma) get 502 error. Only `fin p start` again can fix this

**Comment by ivnish** [comment] 2023-03-13 08:38
@lmakarov can you help with this? I love docksal, but run `fin p start` twice make me nervous

**Comment by alexryall** [comment] 2023-03-14 19:16
@lmakarov I have managed to replicate the issue.

Firstly I did `fin project create` and created a new Laravel project, this worked fine every time after many restarts.
I then added `WEB_IMAGE="docksal/nginx:1.21"` to docksal.env and the below to docksal.yml
`services:
  web:
    extends:
      file: ${HOME}/.docksal/stacks/services.yml
      service: nginx`
I then ran a `fin restart` and the web container failed to start up
<img width="1045" alt="image" src="https://user-images.githubusercontent.com/8352646/225112128-36ae2e60-102c-4040-b90a-61fb388fb49b.png">
I then binned the web container in Docker Desktop and ran `fin start` which this time then successfully created and started the web container and I'm able to load the Laravel start page through Nginx.
I then did another `fin restart` and the web container failed to start up again so it wasn't only an issue the first time when switching from Apache to Nginx.

I do have a feeling this may only be an issue for ARM processors as I never used to get this issue with my previous MacBook Pro which had an Intel i9 but got an M2 Pro now.

**Comment by ivnish** [comment] 2023-03-15 08:25
@lmakarov 

docksal 1.18
Ubuntu 22.04

Now I have problem with additional services. My docksal.yml:

```
version: "2.1"

services:
  pma:
    hostname: pma
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_HOST=db
      - PMA_USER=root
      - PMA_PASSWORD=${MYSQL_ROOT_PASSWORD:-root}
      - UPLOAD_LIMIT=300M
    labels:
      - io.docksal.virtual-host=pma.${VIRTUAL_HOST}
  mail:
    extends:
      file: ${HOME}/.docksal/stacks/services.yml
      service: mail
```

may be problem here? After second `fin p start` these services works

docker logs docksal-vhost-proxy:

```
2023/03/15 08:03:55 [error] 459#459: *376 no live upstreams while connecting to upstream, client: 192.168.64.1, server: mail.mysite.docksal.site, request: "GET / HTTP/1.1", upstream: "http://mysite-mail/", host: "mail.mysite.docksal.site"
2023/03/15 08:03:55 [error] 459#459: *376 no live upstreams while connecting to upstream, client: 192.168.64.1, server: mail.mysite.docksal.site, request: "GET /favicon.ico HTTP/1.1", upstream: "http://mysite-mail/favicon.ico", host: "mail.mysite.docksal.site", referrer: "http://mail.mysite.docksal.site/"
```

**Closed** 2023-03-24 17:10 UTC

**Comment by lmakarov** [comment] 2023-03-24 17:30
I was able to reproduce the issue using the nginx web service container (thanks @alexryall for the tip).

Please try the fix in develop: `DOCKSAL_VERSION=develop fin update`

**Comment by ivnish** [comment] 2023-03-27 09:25
Look like fixed for me
