### ISSUE TITLE
Ability to list SSH keys so they're always added to VM after a restart?

### ISSUE THREAD

**Issue by lpeabody** [docksal/docksal#272] opened 2017-06-22 23:40 UTC
Enhancement request.

I would like to see a feature where you could provide a list of SSH keys that were always added to the ssh-agent service after the VM is started. Any key not named id_rsa, I have to add manually after each restart right now, it's just kind of tedious.

Would you list this in an environment variable in ~/.docksal/docksal.env? I'm happy to do some work on this, just wondering where you guys think the best place for this is.

**Comment by achekulaev** [comment] 2017-06-23 02:05
Just FYI a quick workaround: key names that loaded by h agent automatically are: `id_rsa`, `id_dsa`, `id_ecdsa`. So if you have 3 or less keys you can kind of cover you needs with this little trick. 

What if you had `fin ssh-add -A` command to add all keys you have? Would it work for your needs?

**Comment by lpeabody** [comment] 2017-06-23 03:23
-A is nice as well, though the key here would be automatically adding the keys or listed keys after the VM has started.

**Comment by lmakarov** [comment] 2017-06-23 03:41
@lpeabody out of curiosity - how often and on what occasions do you have to restart the VM?

**Comment by lpeabody** [comment] 2017-06-23 12:58
@lmakarov not frequently, whenever I reboot my system, so once a day on average. It would just be a pure convenience.

**Comment by achekulaev** [comment] 2017-06-26 19:21
I guess we could try if you're open to doing the work. docksal.env sounds like a good place for it.

**Comment by lmakarov** [comment] 2017-09-05 19:31
Closing as a dupe of https://github.com/docksal/docksal/issues/290 (that one has a more clear description).

**Closed by lmakarov** 2017-09-05 19:31 UTC
Labels: enhancement
