### ISSUE TITLE
"web" container can't reach "solr" container

### ISSUE THREAD

**Issue by xandermar** [docksal/docksal#1314] opened 2020-04-30 15:21 UTC
With a fresh Drupal 8.8.5 install, I added the solr service as stated [here](https://docs.docksal.io/tools/apache-solr/). I installed/enabled Drupal's "Search API Solr" module. When I created a server in Search API settings, the SOLR container cannot be reached.

Mac Docker Desktop 2.1
Docksal updated
Composer -> Drupal 8.8.5

Steps to reproduce:

1. mkdir temp
2. cd temp
3. composer create-project drupal/recommended-project
4. cd recommended-project
5. fin init 
6. composer require drupal/search_api_solr
7. vi .docksal/docksal.yml
8. added

service:
  solr:
    extends:
      file: ${HOME}/.docksal/stacks/services.yml
      service: solr

9. fin up (Docksal restarted, showed creation of solr container)
10. completed Drupal initial install in GUI
11. Checked solr GUI - http://solr.<VIRTUAL_HOST>/solr (worked as expected)
12. Configured Search API server settings

Name | Value
Protocol | HTTP
Host | solr
Port | 8983
Solr path | /solr
Solr core | collection1

13. Clicked save and checked Search API config page - says SOLR is unavailable
14. ran 'docker <web container> exec -it /bin/bash'
15. ran 'nmap -p 8983 solr' (successful)

Summary: Everything installs as expected but Drupal cannot connect to the SOLR container. 

(In the graphic, the protocol is 'HTTPS' - I tried both 'HTTP' and 'HTTPS' protocols to eliminate.)

![docksal-solr-1](https://user-images.githubusercontent.com/1800524/80728183-a5f1ab80-8ad4-11ea-8604-a7b2d6b9e2ff.png)
![docksal-solr-3](https://user-images.githubusercontent.com/1800524/80728186-a722d880-8ad4-11ea-96d3-212c4a841bf6.png)
![docksal-solr-4](https://user-images.githubusercontent.com/1800524/80728187-a722d880-8ad4-11ea-84c4-7d43b1116480.png)
![docksal-solr-2](https://user-images.githubusercontent.com/1800524/80728188-a7bb6f00-8ad4-11ea-858d-58fba2e28e1e.png)

**### fin config**
COMPOSE_PROJECT_NAME_SAFE: vanilla
COMPOSE_FILE:
/root/.docksal/stacks/volumes-bind.yml
/root/.docksal/stacks/stack-default.yml
/root/sites/vanilla/.docksal/docksal.yml
ENV_FILE:
/root/sites/vanilla/.docksal/docksal.env

PROJECT_ROOT: /root/sites/vanilla
DOCROOT: web
VIRTUAL_HOST: vanilla.<hidden>.<hidden>
VIRTUAL_HOST_ALIASES: *.vanilla.<hidden>.<hidden>
IP: 192.168.64.100
MYSQL: 192.168.64.100:32768

Docker Compose configuration
---------------------
services:
  cli:
    dns:
    - 192.168.64.100
    - 8.8.8.8
    environment:
      BLACKFIRE_CLIENT_ID: null
      BLACKFIRE_CLIENT_TOKEN: null
      COMPOSER_ALLOW_XDEBUG: '0'
      COMPOSER_DISABLE_XDEBUG_WARN: '0'
      DOCROOT: web
      DRUSH_ALLOW_XDEBUG: '0'
      DRUSH_OPTIONS_URI: vanilla.<hidden>.<hidden>
      GIT_USER_EMAIL: null
      GIT_USER_NAME: null
      HOST_GID: null
      HOST_UID: null
      MYSQL_DATABASE: default
      MYSQL_HOST: db
      MYSQL_PASSWORD: user
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
      PHP_IDE_CONFIG: null
      SECRET_ACAPI_EMAIL: null
      SECRET_ACAPI_KEY: null
      SECRET_PLATFORMSH_CLI_TOKEN: null
      SECRET_SSH_PRIVATE_KEY: null
      SECRET_TERMINUS_TOKEN: null
      SSH_AUTH_SOCK: /.ssh-agent/proxy-socket
      VIRTUAL_HOST: vanilla.<hidden>.<hidden>
      XDEBUG_CONFIG: remote_connect_back=0 remote_host=192.168.64.1
      XDEBUG_ENABLED: '0'
    extra_hosts:
      vanilla.<hidden>-test.com: 127.0.0.1
    hostname: cli
    image: docksal/cli:2.10-php7.3
    labels:
      io.docksal.shell: bash
      io.docksal.user: docker
    volumes:
    - docksal_ssh_agent:/.ssh-agent:ro
    - cli_home:/home/docker:rw
    - project_root:/var/www:rw,nocopy,cached
  db:
    dns:
    - 192.168.64.100
    - 8.8.8.8
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: null
      MYSQL_DATABASE: default
      MYSQL_INITDB_SKIP_TZINFO: null
      MYSQL_ONETIME_PASSWORD: null
      MYSQL_PASSWORD: user
      MYSQL_RANDOM_ROOT_PASSWORD: null
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
    hostname: db
    image: docksal/mysql:5.6-1.4
    ports:
    - 3306/tcp
    volumes:
    - db_data:/var/lib/mysql:rw
    - project_root:/var/www:ro,nocopy,cached
  web:
    depends_on:
      cli:
        condition: service_started
    dns:
    - 192.168.64.100
    - 8.8.8.8
    environment:
      APACHE_BASIC_AUTH_PASS: null
      APACHE_BASIC_AUTH_USER: null
      APACHE_DOCUMENTROOT: /var/www/web
      APACHE_FCGI_HOST_PORT: cli:9000
    hostname: web
    image: docksal/apache:2.4-2.3
    labels:
      io.docksal.cert-name: none
      io.docksal.permanent: "false"
      io.docksal.project-root: /root/sites/vanilla
    volumes:
    - project_root:/var/www:ro,nocopy,cached
version: '2.1'
volumes:
  cli_home: {}
  db_data: {}
  docksal_ssh_agent:
    external: true
    name: docksal_ssh_agent
  project_root:
    driver: local
    driver_opts:
      device: /root/sites/vanilla
      o: bind
      type: none

---------------------

**### fin sysinfo**
███  OS
Linux Ubuntu 18.04
Linux localhost 4.15.0-96-generic #97-Ubuntu SMP Wed Apr 1 03:25:46 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

███  ENVIRONMENT
MODE : Linux Kernel
DOCKER_HOST :

███  FIN
fin version: 1.93.0

███  DOCKER COMPOSE
EXPECTED VERSION: 1.24.1
docker-compose version 1.24.1, build 4667896b
docker-py version: 3.7.3
CPython version: 3.6.8
OpenSSL version: OpenSSL 1.1.0j  20 Nov 2018

███  DOCKER
EXPECTED VERSION: 19.03.4

Client: Docker Engine - Community
 Version:           19.03.8
 API version:       1.40
 Go version:        go1.12.17
 Git commit:        afacb8b7f0
 Built:             Wed Mar 11 01:25:46 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.8
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.17
  Git commit:       afacb8b7f0
  Built:            Wed Mar 11 01:24:19 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.2.13
  GitCommit:        7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683

███  DOCKSAL: PROJECTS
project             STATUS                    virtual host                                       project root
vanilla             Up 19 hours (unhealthy)   vanilla.<hidden>.<hidden>,*.vanilla.<hidden>.<hidden>,vanilla.<hidden>.<hidden>.*   /root/sites/vanilla

███  DOCKSAL: VIRTUAL HOSTS
*.vanilla.<hidden>.<hidden>
vanilla.<hidden>.<hidden>.*
vanilla.<hidden>.<hidden>

███  DOCKSAL: DNS
Successfully requested http://dns-test.docksal

███  DOCKER: RUNNING CONTAINERS
CONTAINER ID        IMAGE                     COMMAND                  CREATED             STATUS                    PORTS                                      NAMES
cea387a8a19c        docksal/apache:2.4-2.3    "httpd-foreground"       19 hours ago        Up 19 hours (unhealthy)   80/tcp, 443/tcp                            vanilla_web_1
3251e680850c        docksal/cli:2.10-php7.3   "/opt/startup.sh sup…"   19 hours ago        Up 19 hours (unhealthy)   22/tcp, 3000/tcp, 9000/tcp                 vanilla_cli_1
c2489359515a        docksal/ssh-agent:1.3     "docker-entrypoint.s…"   19 hours ago        Up 19 hours (unhealthy)                                              docksal-ssh-agent
50044ee10254        docksal/dns:1.1           "docker-entrypoint.s…"   19 hours ago        Up 19 hours (unhealthy)   192.168.64.100:53->53/udp                  docksal-dns
2183ede977a0        docksal/vhost-proxy:1.5   "docker-entrypoint.s…"   19 hours ago        Up 19 hours (unhealthy)   0.0.0.0:80->80/tcp, 0.0.0.0:443->443/tcp   docksal-vhost-proxy
f6cdba60074f        docksal/mysql:5.6-1.4     "docker-entrypoint.s…"   19 hours ago        Up 19 hours (unhealthy)   0.0.0.0:32768->3306/tcp                    vanilla_db_1

███  DOCKER: NETWORKS
NETWORK ID          NAME                DRIVER              SCOPE
94614b4b32d6        _default            bridge              local
a45c6bd3f0eb        bridge              bridge              local
9b26882378f6        host                host                local
4834cde44c41        none                null                local
890d5aa3b157        vanilla_default     bridge              local

███  HDD Usage
Filesystem             Size  Used Avail Use% Mounted on
udev                   207M     0  207M   0% /dev
tmpfs                   46M  1.2M   45M   3% /run
/dev/mapper/vg00-lv01   28G  5.6G   21G  22% /
tmpfs                  230M     0  230M   0% /dev/shm
tmpfs                  5.0M     0  5.0M   0% /run/lock
tmpfs                  230M     0  230M   0% /sys/fs/cgroup
/dev/sda1              464M  113M  323M  26% /boot
tmpfs                   46M     0   46M   0% /run/user/0
overlay                 28G  5.6G   21G  22% /var/lib/docker/overlay2/abed2b90f9725281aa4a024fc0f76ce74f751e8d23b5c5abfab333bc5c4830ae/merged
shm                     64M     0   64M   0% /var/lib/docker/containers/f6cdba60074f011f012809c0e7e61c4e6afb810013880efd2ed09b87df74d3d3/mounts/shm
overlay                 28G  5.6G   21G  22% /var/lib/docker/overlay2/aec413f80ce6f32485255fe83efddf36dbf2e384204c737f87562f415301980f/merged
overlay                 28G  5.6G   21G  22% /var/lib/docker/overlay2/8786ffc453cb330f9dc675d28aebe2ea77bafd9d04feb31bb5f241a2e9ea93be/merged
overlay                 28G  5.6G   21G  22% /var/lib/docker/overlay2/636b44a8c1d78e575d77c0f4970a4e92757b6ce71fe71b78c608218515a2527a/merged
overlay                 28G  5.6G   21G  22% /var/lib/docker/overlay2/7aa55d7929a5044b7c7489e46d50f6f12e0083e197d3487a467dd91fce3b706c/merged
shm                     64M     0   64M   0% /var/lib/docker/containers/3251e680850cc8b0f22927545c2f70c6319dc323b5d7bb67dc79d0fad1858a71/mounts/shm
overlay                 28G  5.6G   21G  22% /var/lib/docker/overlay2/08729e27d07b894b6df6c99748d4c751c41ced65d98ae0eb2e38c9366ab7ee21/merged
shm                     64M     0   64M   0% /var/lib/docker/containers/cea387a8a19cc57763bb20850577976371049fce5c1aa4c17a36409ef20f1b1c/mounts/shm

**Comment by xandermar** [comment] 2020-04-30 15:22
In the graphic, the protocol is 'HTTPS' - I tried both 'HTTP' and 'HTTPS' protocols to eliminate.

**Comment by lmakarov** [comment] 2020-04-30 18:40
What does `fin exec curl -I http://solr/solr` say? (this will try to connect from `cli`, where PHP-FPM is, to `solr`).

**Comment by cio-drupalteam-arlington** [comment] 2020-04-30 18:47
> What does `fin exec curl -I http://solr/solr` say? (this will try to connect from `cli`, where PHP-FPM is, to `solr`).

➜  recommended-project fin exec curl -I http://solr/solr
curl: (7) Failed to connect to solr port 80: Connection refused

➜  recommended-project fin exec curl -I http://solr:8983/solr
HTTP/1.1 302 Found
Location: http://solr:8983/solr/
Content-Length: 0

**Comment by xandermar** [comment] 2020-04-30 18:47
> What does `fin exec curl -I http://solr/solr` say? (this will try to connect from `cli`, where PHP-FPM is, to `solr`).

➜  recommended-project fin exec curl -I http://solr/solr
curl: (7) Failed to connect to solr port 80: Connection refused

➜  recommended-project fin exec curl -I http://solr:8983/solr
HTTP/1.1 302 Found
Location: http://solr:8983/solr/
Content-Length: 0

**Comment by lmakarov** [comment] 2020-04-30 19:41
oh, right, forgot the Solr port.

So Drupal can talk to Solr, but likely does not get what it expects.

This would probably be a dupe of https://github.com/docksal/docksal/issues/1152.
The docs need to be updated, as the Search API Solr setup became multi-step and quite complex...

**Comment by xandermar** [comment] 2020-04-30 19:49
> oh, right, forgot the Solr port.
> 
> So Drupal can talk to Solr, but likely does not get what it expects.
> 
> This would probably be a dupe of #1152.
> The docs need to be updated, as the Search API Solr setup became multi-step and quite complex...

Based on #1152, is the part I'm missing the config dump from Drupal? (i.e. ~/.docksal/etc/solr/conf)?

**Comment by lmakarov** [comment] 2020-04-30 21:04
I have not used Solr in a while, so cannot say for sure what the necessary setup steps are. The high level steps are outlines in https://github.com/docksal/docksal/issues/1152#issuecomment-545165765, assuming you use the **stock** Solr images from Docker Hub.

Unfortunately, both, Docksal Solr docs, as well as images, are outdated.

Let's continue the discussion in https://github.com/docksal/docksal/issues/1152

**Closed by lmakarov** 2020-04-30 21:04 UTC
Labels: investigation

**Comment by lucasantunes-ciandt** [comment] 2021-11-04 01:45
@xandermar Did you find a solution for this? I spent some days trying to configure Solr with Docksal and the docs seem very outdated. I'm running into this issue and don't know quite well how to fix it. #1152 is also still open and doesn't seem to be going anywhere.

**Comment by loopy3025** [comment] 2022-10-18 16:51
I was having this issue. It can be really finicky about what you put in. First of all, the documentation says to use "collection1" as your core. Your core may be named something different. Check the core name here:

http://solr.yoursite.docksal.site/solr/#/~cores/

You may not have ".site" at the end of your url. Check your `fin vhosts` for your actual url.

I had to set my drupal settings as follows:

> HTTP protocol: http
> Solr host: solr
> Solr port: 8983
> Solr path: /
> Solr core: user-owned

The big hurdle was figuring out that "Solr path" had to be set to "/", not "/solr". I figured that out when I tried running sapi-i and the error report spat out "http://solr:8983/solr/#/solr" or something like that.
