### ISSUE TITLE
Installation stuck on Ubuntu 18.04/19.04 Dell XPS 15

### ISSUE THREAD

**Issue by justRau** [docksal/docksal#1137] opened 2019-09-29 15:07 UTC
**Description**

Installation script gets stuck with no output and hangs forever when trying to install Docksal using command `bash <(curl -fsSL https://get.docksal.io)` provided in [https://docs.docksal.io/getting-started/setup/#install-linux-debian-fedora](https://docs.docksal.io/getting-started/setup/#install-linux-debian-fedora).

Machine: Ubuntu 18.04 and later upgraded to 19.04 - issue persisted - on Dell XPS 15.

**Steps to reproduce the issue:**

1. Run `bash <(curl -fsSL https://get.docksal.io)`.
2. Installation script gets stuck.

**Describe the results you received:**

`.docksal` file/folder tree in user `$HOME` is created. `fin` script to `/usr/local/bin/fin` is downloaded and looks okay.

Running any `fin` command, it just gets stuck with no output.

**Describe the results you expected:**

Command runs successfully.

**Output of `fin config`:**

<details>
  <summary>fin config output</summary>

  No output, as all attempted `fin` commands get stuck.
</details>

<br>

**Output of `fin sysinfo`:**

<details>
  <summary>fin sysinfo output</summary>

  No output, as all attempted `fin` commands get stuck.
</details>

**Workaround**

After sifting through `/usr/local/bin/fin` file's code and debugging, I've determined, that the script gets stuck when executing function `uuid_generate`. After running `od -x /dev/urandom | head -1` on the aforementioned machine, it outputs a UUID, but does not exit - the command keeps on running. Tried running this command in a VirtualBox VM with Ubuntu 18.04 - outputted a UUID and terminated the command, therefore Docksal was installed successfully.

Changed `uuid_generate`'s contents to just run `uuidgen` and then Docksal was installed successfully.

Now all commands run as expected, as, apparently, UUID generation is only used when Docksal does not have its instance's UUID set yet.

Let me know if I can provide any additional information to narrow down the possible issue.

**Comment by lmakarov** [comment] 2019-10-01 22:34
@justRau I was not able to reproduce this issue on a fresh Ubuntu 18.04 LTS as well as Ubuntu 19.04 instance on DigitalOcean.

```
$ od -x /dev/urandom | head -1 | awk '{OFS="-"; print $2$3,$4,$5,$6,$7$8$9}'
a2467992-a5de-4b42-19a9-16d3c1198035
```
> Changed uuid_generate's contents to just run uuidgen and then Docksal was installed successfully.

Unfortunately, we cannot rely on `uuidgen`, see https://github.com/docksal/docksal/issues/630

From https://stackoverflow.com/questions/3690273/did-i-understand-dev-urandom

> From the urandom manpage:
> 
> The random number generator gathers environmental noise from device drivers and other sources into an entropy pool. The generator also keeps an estimate of the number of bits of noise in the entropy pool. From this entropy pool random numbers are created.
> 
> When read, the /dev/random device will only return random bytes within the estimated number of bits of noise in the entropy pool. /dev/random should be suitable for uses that need very high quality randomness such as one-time pad or key generation. When the entropy pool is empty, reads from /dev/random will block until additional environmental noise is gathered.
> 
> A read from the /dev/urandom device will not block waiting for more entropy. 

More googling - https://unix.stackexchange.com/questions/442698/when-i-log-in-it-hangs-until-crng-init-done

=> try `sudo apt-get install rng-tools`

This seems to be a very narrow hardware/kernel issue. I don't think we'd want to include a workaround for it unless this issue is confirmed by more users.

**Comment by justRau** [comment] 2019-10-13 16:50
Thanks for a lengthy answer. Tried installing rng-tools, but that did not fix the
```bash
od -x /dev/urandom | head -1 | awk '{OFS="-"; print $2$3,$4,$5,$6,$7$8$9}'
```
command.

Anyway, it is just a trivial issue, as UUID is, AFAIK, only generated during Docksal installation and this issue does not inhibit of further `fin` usage. Could be closed, I guess.

**Comment by lmakarov** [comment] 2019-10-15 21:16
ok, closing. We can reconsider if we get more reports.

**Comment by vstanchev** [comment] 2019-11-28 08:16
I had the same issue as @justRau explained. `od -x /dev/urandom | head -1` outputs but does not exit.
The only difference in the setup is that I'm running the installer in an LXC container. Here's a recording https://asciinema.org/a/4oJJ5MKAGAJcL3HAgCGdqHH37 of the process. A workaround is to create a `screen` session where it works (not sure why).

It seems like `od` continues to read from `/dev/urandom` for some reason but fortunately it has an option

```
      -N, --read-bytes=BYTES
              limit dump to BYTES input bytes
```
So the invocation in the UUID generation can be replaced with 

`od -x -N16 /dev/urandom`

What's more is that in the `od` man page it says that by default it outputs 32 bytes but in reality it outputs 16. I suggest adding the `-w` option so that it's clear that we want only 16 bytes.
```
      -w[BYTES], --width[=BYTES]
              output BYTES bytes per output line; 32 is implied when BYTES is not specified
```

My final suggestion for the command is 

`od -x -N16 -w16 /dev/urandom | head -1 | awk '{OFS="-"; print $2$3,$4,$5,$6,$7$8$9}'`

**Comment by lmakarov** [comment] 2020-02-25 16:12
@vstanchev unfortunately, your suggestion does not work on Mac:

```
$ od -x -N16 -w16 /dev/urandom | head -1 | awk '{OFS="-"; print $2$3,$4,$5,$6,$7$8$9}'
od: illegal option -- w
```

**Comment by lmakarov** [comment] 2020-02-26 15:48
@justRau , @vstanchev can you try the following on the system where you previously had issues?

```
cat /dev/urandom | env LANG=C tr -dc 'a-f0-9' | head -c32
```

Also, just to double check, does this still hand for you?

```
od -x /dev/urandom | head -1 | awk '{OFS="-"; print $2$3,$4,$5,$6,$7$8$9}'
```

**Comment by achekulaev** [comment] 2020-02-27 16:14
@vstanchev @lmakarov @sergey-zabolotny try this

```bash
od -x /dev/urandom | head -1 | awk '{OFS="-"; srand($6); sub(/./,"4",$5); sub(/./,substr("89ab",rand()*4,1),$6); print $2$3,$4,$5,$6,$7$8$9}'
```

It is a fixed version of the currently existing function, without changing the approach as current approach seem very good except the issue with `tail` waiting forever.

**Comment by achekulaev** [comment] 2020-02-27 16:19
I don't think there is a need to use `-w` switch. I does not matter if `od ` produces more bytes than needed.

`od -x -N16 /dev/urandom | head -1 | awk '{OFS="-"; print $2$3,$4,$5,$6,$7$8$9}'`

**Comment by justRau** [comment] 2020-03-04 10:46
`cat /dev/urandom | env LANG=C tr -dc 'a-f0-9' | head -c32` returns
`cd0549312af19c844ad138588da9ea68tr: write error: Broken pipe
tr: write error`

`od -x /dev/urandom | head -1 | awk '{OFS="-"; print $2$3,$4,$5,$6,$7$8$9}'` still returns a UUID, but hangs.

`od -x -N16 /dev/urandom | head -1 | awk '{OFS="-"; print $2$3,$4,$5,$6,$7$8$9}'` returns a UUID and does not hang.

**Comment by vstanchev** [comment] 2020-03-04 10:53
> I don't think there is a need to use `-w` switch. I does not matter if `od ` produces more bytes than needed.
> 
> `od -x -N16 /dev/urandom | head -1 | awk '{OFS="-"; print $2$3,$4,$5,$6,$7$8$9}'`

Correct - this should work everywhere.

**Closed** 2020-03-04 20:08 UTC
Labels: os/linux, 🏷bug

**Comment by lmakarov** [comment] 2020-03-04 20:09
Thanks for confirming. Merged.
