### ISSUE TITLE
macOS Mojave compatibility

### ISSUE THREAD

**Issue by alexandar87** [docksal/docksal#796] opened 2018-10-08 06:39 UTC
**Description**

Is it safe to update to the latest macOS Mojave? Can someone confirm that he is using Docksal with the latest version of macOS?

**Comment by lmakarov** [comment] 2018-10-08 06:43
Several folks reported on [Gitter](https://gitter.im/docksal/community-support) that they had to update VirtualBox to the latest version to get it working with Mojave. No other known issues so far.

**Comment by jasonrsavino** [comment] 2018-10-09 00:08
After installing I have been working for three hours trying to get an existing project working after update to Mojave. I needed to update VirtualBox and it's extension packs as well as allow iTerm and VirtualBox access to FullDisk. Even wit hall this I still cannot get it to run smoothly. I have the following error:
`➔ ssh-agent
Unable to find image 'docksal/ssh-agent:1.0' locally
docker: Error response from daemon: Get https://registry-1.docker.io/v2/docksal/ssh-agent/manifests/1.0: unauthorized: incorrect username or password.
See 'docker run --help'.
 ERROR:  docksal-ssh-agent is not running
         Please report this issue, as this should not usually happen.
         Run fin system reset ssh-agent to start the service.`

**Comment by lmakarov** [comment] 2018-10-09 02:37
@jasonrsavino sounds like your Docker Hub credentials (stored in Keychain) got messed up after the upgrade.

If you are not using private repos on Docker Hub, then try removing (or just renaming) `~/.docker/config.json`. 

If you are using private repos on Docker Hub, then try running `fin docker login` and log in with your Docker Hub credentials.

**Comment by achekulaev** [comment] 2018-10-10 18:12
Error with registry is describe in the https://docs.docksal.io/en/master/troubleshooting/#issue-13-docker-unauthorized

**Comment by achekulaev** [comment] 2018-10-24 15:57
I am on Mojave for a week now. Everything seems to be smooth. Closing the issue.

**Closed by achekulaev** 2018-10-24 15:57 UTC
Labels: 🏷question

**Comment by samburgers** [comment] 2019-01-05 09:38
Seems you can login to the desktop Docker client with either your `email + password` OR `username + password`... i found that logging out and relogging in using my dockerhub `username + password` makes everything work a-ok!

**Comment by chu01** [comment] 2019-02-06 17:30
@achekulaev -- LIke you said the issue was with the VBox. I removed, and reinstall and restarted my host machine. That worked just fine. 
I think I should go ahead and close the issue. resolving the issue is in the Virtual Box.

**Comment by Nitebreed** [comment] 2019-06-03 09:46
I have problems with my Docksal file sharing on OSX Mojave. Every time my computer is rebooted, docksal seems to have lost it's file sharing. I have to set DOCKSAL_NFS_PATH every time, even it is already configured on a global level.

Do more people have this problem?

**Comment by lmakarov** [comment] 2019-06-03 16:39
@Nitebreed I don't think you issue is Mojave related. Please file a separate issue and provide the required diagnostic information.
