### ISSUE TITLE
Unable to install docksal on windows 10 pro (1903 build 18362.239)

### ISSUE THREAD

**Issue by alex-belyaev** [docksal/docksal#1103] opened 2019-07-22 15:40 UTC
**Description**

Trying to install docksal on newly installed Win 10, during `bash <(curl -fsSL https://get.docksal.io)` got 
```alex@Umbrella:~$ bash <(curl -fsSL https://get.docksal.io)
ATTENTION: Installer requires administrative privileges to continue with Docksal setup.
           On macOS and Linux please enter your current user password,
           in Ubuntu App for Windows 10 use Linux user password in this step.
           For more information, see https://docs.docksal.io/getting-started/setup/#install
[sudo] password for alex:
'\\wsl$\Ubuntu-18.04\home\alex'
CMD.EXE was started with the above path as the current directory.
UNC paths are not supported.  Defaulting to Windows directory.
[STEP 1/4] Updating fin...
'\\wsl$\Ubuntu-18.04\home\alex'
CMD.EXE was started with the above path as the current directory.
UNC paths are not supported.  Defaulting to Windows directory.
fin 1.86.2 downloaded...
'\\wsl$\Ubuntu-18.04\home\alex'
CMD.EXE was started with the above path as the current directory.
UNC paths are not supported.  Defaulting to Windows directory.
[STEP 2/4] Updating stack files...
overrides-ide.yml
overrides-osxfs.yml
services.yml
stack-acquia.yml
stack-default.yml
stack-default-nodb.yml
stack-node.yml
stack-pantheon.yml
volumes-bind.yml
volumes-nfs.yml
volumes-none.yml
volumes-unison.yml
Configuring network settings...
[STEP 3/4] Updating tools...
'\\wsl$\Ubuntu-18.04\home\alex'
CMD.EXE was started with the above path as the current directory.
UNC paths are not supported.  Defaulting to Windows directory.
Installing docker-machine v0.16.1...
Downloading docker-machine-Windows-x86_64.exe...
############################################################################################################### 100.0%
chmod: changing permissions of '/c/Users/Alex/.docksal/bin/docker-machine.exe': Operation not permitted
Check file permissions and internet connection.
```
Also tried:
```
alex@Umbrella:~$ chmod +x /c/Users/Alex/.docksal/bin/docker-machine.exe
chmod: changing permissions of '/c/Users/Alex/.docksal/bin/docker-machine.exe': Operation not permitted
alex@Umbrella:~$ chmod +x /mnt/c/Users/Alex/.docksal/bin/docker-machine.exe
chmod: changing permissions of '/mnt/c/Users/Alex/.docksal/bin/docker-machine.exe': Operation not permitted
```

**Output of `fin config`:**

<details>
  <summary>fin config output</summary>

```
alex@Umbrella:~$ fin config
'\\wsl$\Ubuntu-18.04\home\alex'
CMD.EXE was started with the above path as the current directory.
UNC paths are not supported.  Defaulting to Windows directory.
 ERROR:  Cannot detect project root.
        Please make sure you have .docksal directory in the root of your project.
        To setup a basic Docksal stack in the current directory run fin config generate
```

</details>

<br>

**Output of `fin sysinfo`:**

<details>
  <summary>fin sysinfo output</summary>

  ```
alex@Umbrella:~$ fin sysinfo
'\\wsl$\Ubuntu-18.04\home\alex'
CMD.EXE was started with the above path as the current directory.
UNC paths are not supported.  Defaulting to Windows directory.
███  OS
WSL Ubuntu 18.04
Linux Umbrella 4.4.0-18362-Microsoft #1-Microsoft Mon Mar 18 12:02:00 PST 2019 x86_64 x86_64 x86_64 GNU/Linux

███  ENVIRONMENT
MODE : VirtualBox VM
DOCKER_HOST :

███  FIN
fin version: 1.86.2

███  DOCKER COMPOSE
EXPECTED VERSION: 1.23.2
docker-compose version 1.23.2, build 1110ad01
docker-py version: 3.6.0
CPython version: 3.6.7
OpenSSL version: OpenSSL 1.1.0f  25 May 2017

███  DOCKER
EXPECTED VERSION: 18.09.2

Client: Docker Engine - Community
 Version:           18.09.2
 API version:       1.39
 Go version:        go1.10.8
 Git commit:        6247962
 Built:             Sun Feb 10 04:11:47 2019
 OS/Arch:           linux/amd64
 Experimental:      false
Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?

███  DOCKER MACHINE
EXPECTED VERSION: 0.16.1
/usr/local/bin/fin: line 5697: docker-machine: command not found

/usr/local/bin/fin: line 5699: docker-machine: command not found
███  DOCKER: DOCKER IS NOT RUNNING


███  HDD Usage
docker-machine executable was not found. (Try running 'fin update')
  ```

</details>

**Comment by Martins15** [comment] 2019-07-31 12:18
I have the same issue after installing windows update. @lmakarov please investigate.

**Comment by Martins15** [comment] 2019-08-06 14:51
I've had a similar problem when I used windows ubuntu console. Then I've tried to install manually the latest virtualbox and latest babun, then install docksal using these 2 commands: https://docksal.io/installation#windows-virtualbox

And it worked!

**Comment by sean-e-dietrich** [comment] 2019-08-08 15:39
Thanks @Martins15 was able to confirm a similar but different issue

```
sean@DESKTOP-DAN4NA6:~$ curl -fsSL get.docksal.io | bash
'\\wsl$\Legacy\home\sean'
CMD.EXE was started with the above path as the current directory.
UNC paths are not supported.  Defaulting to Windows directory.
wslpath: Invalid argument
[STEP 1/4] Updating fin...
'\\wsl$\Legacy\home\sean'
CMD.EXE was started with the above path as the current directory.
UNC paths are not supported.  Defaulting to Windows directory.
wslpath: Invalid argument
fin 1.86.2 downloaded...
'\\wsl$\Legacy\home\sean'
CMD.EXE was started with the above path as the current directory.
UNC paths are not supported.  Defaulting to Windows directory.
wslpath: Invalid argument
[STEP 2/4] Updating stack files...
overrides-ide.yml
overrides-osxfs.yml
services.yml
stack-acquia.yml
stack-default.yml
stack-default-nodb.yml
stack-node.yml
stack-pantheon.yml
volumes-bind.yml
volumes-nfs.yml
volumes-none.yml
volumes-unison.yml
Configuring network settings...
[STEP 3/4] Updating tools...
'\\wsl$\Legacy\home\sean'
CMD.EXE was started with the above path as the current directory.
UNC paths are not supported.  Defaulting to Windows directory.
wslpath: Invalid argument
Installing docker-machine v0.16.1...
Downloading docker-machine-Windows-x86_64.exe...
######################################################################## 100.0%
 ALERT:  VirtualBox version should be 5.2.26 or higher
'\\wsl$\Legacy\home\sean'
CMD.EXE was started with the above path as the current directory.
UNC paths are not supported.  Defaulting to Windows directory.
wslpath: Invalid argument
Downloading and installing VirtualBox 5.2.26
Warning: Failed to create the file Usage: -a force result to absolute path
Warning: format -u translate from a Windows path to a WSL path (default) -w
Warning: translate from a WSL path to a Windows path -m translate from a WSL
Warning: path to a Windows path, with '/' instead of '\' EX: ws
curl: (23) Failed writing body (0 != 1492)
```

**Comment by lmakarov** [comment] 2019-08-16 21:40
There are two issues here. Both were introduced in the recent Windows 10 v1903 update, which added a new feature in WSL - [Accessing Linux files from Windows](https://devblogs.microsoft.com/commandline/whats-new-for-wsl-in-windows-10-version-1903/).

From that article:

> Known issues:
> ...
> Accessing Linux files is treated the same as accessing a network resource, and any rules for accessing network resources will still apply e.g: When using CMD, cd \\wsl$\Ubuntu\home will not work (as CMD does not support UNC paths as current directories), however copy \\wsl$\Ubuntu\home\somefile.txt C:\dev\ will work
> ...

So Windows binaries in WSL are now launched with their working directory set to a UNC path like `\\wsl$\Ubuntu\<working directory in WSL>`, which results in the first issue.

**Issue 1: `CMD.EXE` does not understand UNC paths**

```
CMD.EXE was started with the above path as the current directory.
UNC paths are not supported.  Defaulting to Windows directory.
```

This is a non-fatal warning, which shows up whenever `cmd.exe` is invoked by `fin`.
It is a mere annoyance and will not cause any issues.

It only happens when running `fin` within a Linux directory (e.g. Linux user's home). Switching to a Windows directory (e.g., `/mnt/c/`) can be used as a workaround.

Looks like the issue is considered expected and may not get fixed in the new versions of WSL:
https://github.com/microsoft/WSL/issues/3809#issuecomment-476264368

Moving on.

**Issue 2: Broken symlink resolution to Windows paths in WSL**

This one is not obvious right away. The symptoms look like this

```
user@HTPC:/mnt/c$ bash <(curl -fsSL https://get.docksal.io)
...
[STEP 3/4] Updating tools...
Installing docker-machine v0.16.1...
Downloading docker-machine-Windows-x86_64.exe...
################################################################################################################# 100.0%
Creating docker machine 'docksal'...
 ERROR:  Proper creation of virtual machine has failed
        For details please refer to the log above.
        It is recommended to remove malfunctioned virtual machine.
Remove docksal? [y/n]:  
```
What actually happens their is calls to `docker-machine` binary fail silently. This is a fatal error and prevents `fin` from creating the VM.

Here's a more clear demonstration of the issue:

```
# broken
user@HTPC:~$ ~/.docksal/bin/docker-machine --version

# workaround
user@HTPC:~$ $(readlink ~/.docksal/bin/docker-machine) --version
docker-machine.exe version 0.16.1, build cce350d7
```

Note: `wslpath` binary also has issue with correctly resolving symlinks, which may be related to the Issue 2 above.

```
# broken
user@HTPC:~$ wslpath -w ~/.docksal/bin/docker-machine
\\wsl$\Ubuntu-18.04\home\user\.docksal\bin\docker-machine

# workaround
user@HTPC:~$ wslpath -w $(readlink ~/.docksal/bin/docker-machine)
C:\Users\htpc\.docksal\bin\docker-machine.exe
```

A relevant issue upstream: https://github.com/microsoft/WSL/issues/4078

Note: I've been comparing the behavior using WSL on the following Windows versions:

- Windows 10 v1903 (build 10.0.18362.295) - issues described above
- Windows 10 v1803 (build 10.0.17134.950) - works as expected

**Comment by lmakarov** [comment] 2019-08-16 22:09
Pushed fixes for both issues (fin v1.87.1).
Until this gets into a release, you can use install the development version of Docksal like this:

```
DOCKSAL_VERSION=develop bash <(curl -fsSL https://get.docksal.io)
```

**Comment by froboy** [comment] 2019-09-06 21:07
I'm running into this same issue and the develop version hasn't resolved them. 

I removed `.docksal` from both my Ubuntu home directory and Windows home, then ran the command above and still receive this error:
```
chmod: changing permissions of '/c/Users/aschwab_ct/.docksal/bin/docker-machine.exe': Operation not permitted
```

I realize this is closed, should I open a new ticket?

**Comment by froboy** [comment] 2019-09-09 16:03
Update: here're my details:

Windows 10, v1903, build 18362.295

Remove all teh things and install:
```
aschwab@L36718-Win10:~$ rm -rf /c/Users/aschwab_ct/.docksal/
aschwab@L36718-Win10:~$ rm -rf ~/.docksal/
aschwab@L36718-Win10:~$ sudo rm -f /usr/local/bin/fin
aschwab@L36718-Win10:~$ DOCKSAL_VERSION=develop bash <(curl -fsSL https://get.docksal.io)
[!] Using Docksal version: develop
[STEP 1/4] Updating fin...
fin 1.87.1 downloaded...
[STEP 2/4] Updating stack files...
overrides-ide.yml
overrides-osxfs.yml
services.yml
stack-acquia.yml
stack-default.yml
stack-default-nodb.yml
stack-node.yml
stack-pantheon.yml
volumes-bind.yml
volumes-nfs.yml
volumes-none.yml
volumes-unison.yml
Configuring network settings...
[STEP 3/4] Updating tools...
Installing docker client v18.09.2...
Downloading docker-18.09.2.tgz...
################################################################################################################# 100.0%
Installing docker-compose v1.23.2...
Downloading docker-compose-Linux-x86_64...
################################################################################################################# 100.0%
Installing docker-machine v0.16.1...
Downloading docker-machine-Windows-x86_64.exe...
################################################################################################################# 100.0%
chmod: changing permissions of '/c/Users/aschwab_ct/.docksal/bin/docker-machine.exe': Operation not permitted
Check file permissions and internet connection.
```

output of `fin sysinfo`:
<details>
```
aschwab@L36718-Win10:~$ fin sysinfo
███  OS
WSL Ubuntu 18.04
Linux L36718-Win10 4.4.0-18362-Microsoft #1-Microsoft Mon Mar 18 12:02:00 PST 2019 x86_64 x86_64 x86_64 GNU/Linux

███  ENVIRONMENT
MODE : VirtualBox VM
DOCKER_HOST :

███  FIN
fin version: 1.87.1

███  DOCKER COMPOSE
EXPECTED VERSION: 1.23.2
docker-compose version 1.23.2, build 1110ad01
docker-py version: 3.6.0
CPython version: 3.6.7
OpenSSL version: OpenSSL 1.1.0f  25 May 2017

███  DOCKER
EXPECTED VERSION: 18.09.2

Client: Docker Engine - Community
 Version:           18.09.2
 API version:       1.39
 Go version:        go1.10.8
 Git commit:        6247962
 Built:             Sun Feb 10 04:11:47 2019
 OS/Arch:           linux/amd64
 Experimental:      false
Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?

███  DOCKER MACHINE
EXPECTED VERSION: 0.16.1
/usr/local/bin/fin: line 443: --version: command not found

███  DOCKER: DOCKER IS NOT RUNNING


███  VIRTUALBOX
EXPECTED VERSION: 5.2.26
6.0.12r133076

███  HDD Usage
docker-machine executable was not found. (Try running 'fin update')
```
</details>

**Comment by achekulaev** [comment] 2019-09-10 21:41
The problem with the comment above is that for some reason WSL sees all files on Windows filesystem  as owned by `root`. Surprisingly user is able to create/delete files, but not able to chmod successfully, at the same time however sudo chmod does not fail.

**Comment by froboy** [comment] 2019-09-11 18:52
@achekulaev thanks for all your help here and in Slack. your last tip last night was a winner. I used the instructions in https://devblogs.microsoft.com/commandline/automatically-configuring-wsl/ to add `options = "metadata"` in the `wsl.conf` file, rebooted, and the installation is proceeding as expected now. I'm not quite through the woods yet, but this issue seem to be resolved. Thanks again!

**Closed** 2019-09-11 19:31 UTC
Labels: os/windows, os/wsl, 🏷bug

**Comment by marcusanderss** [comment] 2019-11-04 23:55
I tried to follow the instruction for docksalubuntu installation on windows 10:
https://docksal.io/installation#windows-virtualbox
I could not get it up and running. I have version 1809 build 17763.805

**Comment by marcusanderss** [comment] 2019-11-04 23:57
ALERT:  VirtualBox version should be 5.2.32 or higher
wslpath: Invalid argument
Do you want to download VirtualBox 5.2.32 to 'Usage: -a force result to absolute path format -u translate from a Windows path to a WSL path (default) -w translate from a WSL path to a Windows path -m translate from a WSL path to a Windows path, with '/' instead of '\' EX: wslpath 'c:\users'/Downloads/VirtualBox-5.2.32-132073-Win.exe' and install it? [y/n]: y
Warning: Failed to create the file Usage: -a force result to absolute path
Warning: format -u translate from a Windows path to a WSL path (default) -w
Warning: translate from a WSL path to a Windows path -m translate from a WSL
Warning: path to a Windows path, with '/' instead of '\' EX: wslpath
Warning: 'c:\users'/Downloads/VirtualBox-5.2.32-132073-Win.exe: No such file
Warning: or directory
                                                                                                                    0.0%
curl: (23) Failed writing body (0 != 1495)

**Comment by marcusanderss** [comment] 2019-11-05 00:12
I uninstalled everything and downloaded latest virtualbox version.
~$ fin system start
wslpath: Invalid argument
Configuring network settings...
docker-machine executable was not found. (Try running 'fin update') doesn't work unfortunately

**Comment by digitalsanity** [comment] 2020-05-20 02:59
> 
> 
> @achekulaev thanks for all your help here and in Slack. your last tip last night was a winner. I used the instructions in https://devblogs.microsoft.com/commandline/automatically-configuring-wsl/ to add `options = "metadata"` in the `wsl.conf` file, rebooted, and the installation is proceeding as expected now. I'm not quite through the woods yet, but this issue seem to be resolved. Thanks again!

Thank you!  This should be on the FAQ at least .. May 19, 2020 and I just spent a couple of hours tracking this down ..
