### ISSUE TITLE
The docker-modes.md file has an incorrect link 

### ISSUE THREAD

**Issue by AmyJuneH** [docksal/docksal#953] opened 2019-02-07 04:47 UTC
**Description**
The docker-modes.md file has an incorrect link (line 18)
(/getting-started/setup/)

Problem/feature description...
 Setup docs link leads to a 404 page.

**Comment by shelane** [comment] 2019-02-07 17:01
From the [Switching Docker Modes](https://docs.docksal.io/getting-started/docker-modes/) page, the link to [Installing Docksal](https://docs.docksal.io/getting-started/setup/) page appears to be working. This is the link found on line 18 of /getting-started/docker-modes.md.

**Comment by achekulaev** [comment] 2019-02-07 19:07
@shelane I guess what is meant is that it is not working when clicked on GitHub.

If you open https://github.com/docksal/docksal/blob/develop/docs/content/getting-started/docker-modes.md and click `setup docs` link

**Comment by AmyJuneH** [comment] 2019-02-07 19:28
Yes ^^

**Comment by shelane** [comment] 2019-02-07 19:36
Ah, I see. Yes, links are absolute to the root of the doc site and those links wouldn't work within GitHub. We could look at making links more relative, but they aren't really intended to be view through GitHub.

**Comment by achekulaev** [comment] 2019-02-07 20:09
I guess it is won't fix / works as intended now. @shelane maybe there is a sense to point out that docs should be read through docs.docksal.io somewhere on the main page of the docs

**Closed by achekulaev** 2019-02-07 20:09 UTC
Labels: wontfix, 🏷documentation
