### ISSUE TITLE
"Extending stock Docksal images" fails for Windows

### ISSUE THREAD

**Issue by charginghawk** [docksal/docksal#451] opened 2018-01-16 19:15 UTC
**Description**

The [documentation for extending stock Docksal images](https://docksal.readthedocs.io/en/master/advanced/extend-images/) doesn't work for Windows because of an issue with PROJECT_ROOT, namely that it's prefixed with`/c/` instead of `C:/`.

The instructions for extending Docksal images has this tidbit for docksal.yml:

```
version: "2.1"

services:
  <service-name>:
    image: ${COMPOSE_PROJECT_NAME_SAFE}_<service-name>
    build: ${PROJECT_ROOT}/.docksal/services/<service-name>
```

In our case it's like so (minor differences, but works all the same):

```
services:
  web:
    hostname: web
    build: ${PROJECT_ROOT}/.docksal/web
```

However, this method breaks on Windows installs because it's can't find the directory, with this error:

```
{ pegawwwd8 } develop » fin project start                                  ~/projects/pegawwwd8 1
Starting services...
build path C:\c\Users\chart\.babun\cygwin\home\chart\projects\pegawwwd8\.docksal\web either does  exist, is not accessible, or is not a valid URL.
Virtual Host: pegawwwd8.docksal
```

With the weird build path prefix there, `C:\c\`, I reckon this is likely because the normal image paths and PROJECT_ROOT aren't using the same path format:

```
{ pegawwwd8 } develop » fin config show                                      ~/projects/pegawwwd8
...
COMPOSE_FILE:
C:/Users/chart/.babun/cygwin/home/chart/.docksal/stacks/volumes-bind.yml
C:/Users/chart/.babun/cygwin/home/chart/projects/pegawwwd8/.docksal/docksal.yml
ENV_FILE:
C:/Users/chart/.babun/cygwin/home/chart/projects/pegawwwd8/.docksal/docksal.env
C:/Users/chart/.babun/cygwin/home/chart/projects/pegawwwd8/.docksal/docksal-local.env

PROJECT_ROOT: /c/Users/chart/.babun/cygwin/home/chart/projects/pegawwwd8
...
```

Note that the stack config filepaths start with `C:/`, while PROJECT_ROOT starts with `/c/`.

It works if I edit my docksal.yml to replace `${PROJECT_ROOT}` with a variable set to `C:/Users/chart/.babun/cygwin/home/chart/projects/pegawwwd8`.

**Steps to reproduce the issue:**

1. Setup config to extend Docksal image per instructions.
2. Try to use it on Windows using the recommended install.

**Describe the results you received:**

It can't find your custom setup because it's looking in `/c/`, not `C:/`.

**Describe the results you expected:**

It's works.

**Output of `fin config`:**

<details>
  <summary>fin config output</summary>

```
{ pegawwwd8 } develop » fin config show                                      ~/projects/pegawwwd8
---------------------
COMPOSE_PROJECT_NAME_SAFE: pegawwwd8
COMPOSE_FILE:
C:/Users/chart/.babun/cygwin/home/chart/.docksal/stacks/volumes-bind.yml
C:/Users/chart/.babun/cygwin/home/chart/projects/pegawwwd8/.docksal/docksal.yml
ENV_FILE:
C:/Users/chart/.babun/cygwin/home/chart/projects/pegawwwd8/.docksal/docksal.env
C:/Users/chart/.babun/cygwin/home/chart/projects/pegawwwd8/.docksal/docksal-local.env

PROJECT_ROOT: /c/Users/chart/.babun/cygwin/home/chart/projects/pegawwwd8
DOCROOT: docroot
VIRTUAL_HOST: pegawwwd8.docksal
VIRTUAL_HOST_ALIASES: *.pegawwwd8.docksal
IP: 192.168.64.100
MYSQL:

Docker Compose configuration
---------------------
build path C:\c\Users\chart\.babun\cygwin\home\chart\projects\pegawwwd8\.docksal\web either does not exist, is not accessible, or is not a valid URL.
```

</details>

<br>

**Output of `fin sysinfo`:**

<details>
  <summary>fin sysinfo output</summary>

  ```
{ pegawwwd8 } develop » fin sysinfo
 API version:  1.32
 Go version:   go1.8.3
 Git commit:   afdb6d4
 Built:        Tue Sep 26 22:40:09 2017
 OS/Arch:      windows/amd64

Server:
 Version:      17.09.0-ce
 API version:  1.32 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   afdb6d4
 Built:        Tue Sep 26 22:45:38 2017
 OS/Arch:      linux/amd64
 Experimental: false

███  DOCKER INFO
Containers: 7
 Running: 7
 Paused: 0
 Stopped: 0
Images: 15
Server Version: 17.09.0-ce
Storage Driver: aufs
 Root Dir: /mnt/sda1/var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 99
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 06b9cb35161009dcb7123345749fef02f7cea8e0
runc version: 3f2f8b84a77f73d38244dd690525642a72156c64
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.4.89-boot2docker
Operating System: Boot2Docker 17.09.0-ce (TCL 7.2); HEAD : 06d5c35 - Wed Sep 27 23:22:43 UTC 2017
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 1.955GiB
Name: docksal
ID: W6KR:T3GX:ACZF:X7RE:MXMO:UQC5:HVS5:DB4E:YWBF:4QG6:5N3G:7NLC
Docker Root Dir: /mnt/sda1/var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 109
 Goroutines: 76
 System Time: 2018-01-16T19:07:38.258441054Z
 EventsListeners: 2
Registry: https://index.docker.io/v1/
Labels:
 provider=virtualbox
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

███  DOCKER COMPOSE
EXPECTED VERSION: 1.17.1
docker-compose version 1.17.1, build 6d101fb0
docker-py version: 2.5.1
CPython version: 2.7.14
OpenSSL version: OpenSSL 1.0.2k  26 Jan 2017

███  DOCKER MACHINE
EXPECTED VERSION: 0.13.0
docker-machine.exe version 0.13.0, build 9ba6da9

NAME      ACTIVE   DRIVER       STATE     URL                         SWARM   DOCKER        ERRORS
docksal   *        virtualbox   Running   tcp://192.168.64.100:2376           v17.09.0-ce

███  DOCKER: IMAGES
REPOSITORY            TAG                 IMAGE ID            CREATED             SIZE
pegawwwd8_web         latest              4806e8971e90        37 minutes ago      207MB
pegawwwd8_cli         latest              9cf975fb954a        38 minutes ago      989MB
memcached             latest              5fdb3385afc9        3 weeks ago         58.6MB
docksal/cli           1.3-php7            19bdddfeab89        3 months ago        759MB
docksal/vhost-proxy   1.1                 898fb21e7f2d        5 months ago        158MB
docksal/dns           1.0                 20c7a535479d        12 months ago       61.6MB
docksal/ssh-agent     1.0                 148220cc033d        12 months ago       12.2MB
docksal/web           1.0-apache2.2       a9c03f8a5f0f        12 months ago       188MB
docksal/db            1.0-mysql-5.7       35f1494f03b6        12 months ago       400MB

███  DOCKER: CONTAINERS
CONTAINER ID        IMAGE                      COMMAND                  CREATED             STATUS                    PORTS                                                    NAMES
d8c64a34c1cf        pegawwwd8_web              "/opt/startup.sh a..."   37 minutes ago      Up 37 minutes             80/tcp, 443/tcp                                          pegawwwd8_web_1
3e99012c88a6        docksal/db:1.0-mysql-5.7   "/entrypoint.sh my..."   37 minutes ago      Up 37 minutes             0.0.0.0:32769->3306/tcp                                  pegawwwd8_db_1
64a576968056        memcached                  "docker-entrypoint..."   37 minutes ago      Up 37 minutes             0.0.0.0:32768->11211/tcp                                 pegawwwd8_memcached_1
b1968c6ff90c        pegawwwd8_cli              "/opt/startup.sh s..."   37 minutes ago      Up 37 minutes (healthy)   22/tcp, 9000/tcp                                         pegawwwd8_cli_1
b85cab7c5b4d        docksal/ssh-agent:1.0      "/run.sh ssh-agent"      2 hours ago         Up 2 hours                                                                         docksal-ssh-agent
ad26e4f66456        docksal/dns:1.0            "/opt/entrypoint.s..."   2 hours ago         Up 2 hours                192.168.64.100:53->53/udp                                docksal-dns
11a8a75a0ee6        docksal/vhost-proxy:1.1    "docker-entrypoint..."   2 hours ago         Up 2 hours                192.168.64.100:80->80/tcp, 192.168.64.100:443->443/tcp   docksal-vhost-proxy

███  VIRTUALBOX
EXPECTED VERSION: 5.1.28
5.1.28r117968

███  VIRTUALBOX NETWORK INTERFACES
Name:            VirtualBox Host-Only Ethernet Adapter
GUID:            330c12a9-9d6a-4210-9653-4cfcc278ea00
DHCP:            Disabled
IPAddress:       192.168.56.1
NetworkMask:     255.255.255.0
IPV6Address:     fe80:0000:0000:0000:e48b:8b40:58b6:8e79
IPV6NetworkMaskPrefixLength: 64
HardwareAddress: 0a:00:27:00:00:2b
MediumType:      Ethernet
Status:          Up
VBoxNetworkName: HostInterfaceNetworking-VirtualBox Host-Only Ethernet Adapter

Name:            VirtualBox Host-Only Ethernet Adapter #2
GUID:            bc5c9517-b9f1-4da6-aa6c-4cd74b74b95d
DHCP:            Disabled
IPAddress:       192.168.64.1
NetworkMask:     255.255.255.0
IPV6Address:     fe80:0000:0000:0000:0cc3:947f:336d:5e71
IPV6NetworkMaskPrefixLength: 64
HardwareAddress: 0a:00:27:00:00:33
MediumType:      Ethernet
Status:          Up
VBoxNetworkName: HostInterfaceNetworking-VirtualBox Host-Only Ethernet Adapter #2


███  DOCKSAL MOUNTS
//192.168.64.1/docksal-c on /c type cifs (rw,relatime,vers=1.0,sec=ntlmssp,cache=strict,username=chart,domain=RPEGA,uid=0,noforceuid,gid=0,noforcegid,addr=192.168.64.1,file_mode=0777,dir_mode=0777,nounix,serverino,mapposix,nobrl,mfsymlinks,noperm,rsize=61440,wsize=65536,actimeo=1)
//192.168.64.1/docksal-c on /mnt/sda1/var/lib/docker/volumes/pegawwwd8_project_root/_data type cifs (rw,relatime,vers=1.0,sec=ntlmssp,cache=strict,username=chart,domain=RPEGA,uid=0,noforceuid,gid=0,noforcegid,addr=192.168.64.1,file_mode=0777,dir_mode=0777,nounix,serverino,mapposix,nobrl,mfsymlinks,noperm,rsize=61440,wsize=65536,actimeo=1)

███  HDD Usage
Filesystem                Size      Used Available Use% Mounted on
/dev/sda1                46.3G      2.5G     41.3G   6% /mnt/sda1

███  RAM Usage
             total       used       free     shared    buffers     cached
Mem:       2050284    1946856     103428     203548     128660    1142400
-/+ buffers/cache:     675796    1374488
Swap:      1443944       4448    1439496

███  RAM Usage per container
CONTAINER               CPU %               MEM USAGE / LIMIT     MEM %               NET I/O             BLOCK I/O           PIDS
pegawwwd8_web_1         0.01%               5.441MiB / 1.955GiB   0.27%               4.23kB / 2.98kB     90.1kB / 0B         57
pegawwwd8_db_1          0.06%               208.5MiB / 1.955GiB   10.41%              1.17kB / 0B         32MB / 287MB        27
pegawwwd8_memcached_1   0.03%               2.859MiB / 1.955GiB   0.14%               1.26kB / 0B         2.52MB / 0B         10
pegawwwd8_cli_1         0.07%               30.06MiB / 1.955GiB   1.50%               1.34kB / 0B         45.7MB / 12.3kB     8
docksal-ssh-agent       0.00%               628KiB / 1.955GiB     0.03%               816B / 0B           0B / 0B             2
docksal-dns             0.29%               11.64MiB / 1.955GiB   0.58%               1.09MB / 1.18MB     0B / 0B             9
docksal-vhost-proxy     0.27%               16.79MiB / 1.955GiB   0.84%               10.7kB / 14.9k
```

</details>

**Comment by achekulaev** [comment] 2018-01-17 03:43
If you don't need your docksal.yml file to be cross platform you can use `${PROJECT_ROOT_WIN}` instead of `${PROJECT_ROOT}` for now. 

```yml
version: "2.1"

services:
  <service-name>:
    image: ${COMPOSE_PROJECT_NAME_SAFE}_<service-name>
    build: ${PROJECT_ROOT_WIN}/.docksal/services/<service-name>
```

To mitigate this issue I will implement a change, so that `docker-compose build` will always run from the project root. After that change one will be able to write

```yml
   ...
    build: ./.docksal/services/<service-name>
```

This should be cross-platform enough.

**Comment by lmakarov** [comment] 2018-01-17 03:58
This is a dupe of #398.
See the workaround described [there](https://github.com/docksal/docksal/issues/398#issuecomment-346355752) for a cross-platform solution.

**Closed by lmakarov** 2018-01-17 03:58 UTC
Labels: bug, os/windows

**Comment by achekulaev** [comment] 2018-01-29 22:05
Once `docker-compose` fixes this https://github.com/docker/compose/issues/5624 the issue can be solved without "hacks"
