### ISSUE TITLE
PROJECT_ROOT set incorrectly when using `fin exec...`

### ISSUE THREAD

**Issue by mike-potter** [docksal/docksal#1346] opened 2020-05-14 19:35 UTC
fin 1.93.0

This might be a simple support question or user error.  I have a very simple `script.sh` file:
```
#!/bin/bash
echo "PROJECT ROOT: $PROJECT_ROOT"
```
and when I run this with `fin exec ./script.sh` I get the output:
```
PROJECT ROOT: /var/www DOCROOT=build/docroot VIRTUAL_HOST=myproject.docksal /bin/bash -c ./script.sh
```
That doesn't seem right.  Seems like it should just be `/var/www`.  Looking at the `fin` source, this seems to come from the line 8022:
```
_exec "PROJECT_ROOT=/var/www DOCROOT=$DOCROOT VIRTUAL_HOST=$VIRTUAL_HOST /bin/bash -c $script_to_run" "$@"
```
If I do a `fin bash` and then `echo $PROJECT_ROOT` it works fine.  So this is only an issue when trying to use `fin exec` to run a specific script or command.  Is this a bug?  Or am I doing something wrong?

**Comment by lmakarov** [comment] 2020-05-14 19:45
```
$ fin exec bash -c ./script.sh
PROJECT ROOT: /var/www
```

**Comment by achekulaev** [comment] 2020-05-15 16:43
@mike-potter this is already fixed in the latest development version that is why @lmakarov cannot reproduce it

**Closed by achekulaev** 2020-05-15 16:43 UTC
Labels: 🏷question
