### ISSUE TITLE
`fin project create` does not work with "Drupal 8 (Composer Version)"

### ISSUE THREAD

**Issue by MKorostoff** [docksal/docksal#1098] opened 2019-07-10 15:15 UTC
**Description**

When I run `fin project create` and then select "Drupal 8 (Composer Version)" no site is created.

**Steps to reproduce the issue:**

1. Give the command `fin project create`
2. At the prompt "Name your project" type "mydir"
3. At the prompt "What would you like to install?" select "2.  Drupal 8 (Composer Version)"
4. At the prompt "do you wish to proceed" answer "yes"
5. See that the project is cloned with git
6. See the error: "/usr/local/bin/fin: line 3249: cd: mydir: No such file or directory" <--- Bug

<img width="621" alt="no_dir" src="https://user-images.githubusercontent.com/1197335/60979639-0d99f880-a301-11e9-942b-5598be229f0c.png">

**Describe the results you received:**

No site was created.  Note, I _am_ able to create a drupal site by manually cloning the [Drupal 8 boilerplate](https://github.com/docksal/boilerplate-drupal8-composer) and then running `fin init`

**Describe the results you expected:**

That a drupal 8 site would be created

**Output of `fin config`:**

<details>
  <summary>fin config output</summary>

```
N/A because the project never gets created, so there is no config
```

</details>

<br>

**Output of `fin sysinfo`:**

<details>
  <summary>fin sysinfo output</summary>

  ```
███  OS
Darwin Mac OS X 10.14.5
Darwin Matts-MBP.fios-router.home 18.6.0 Darwin Kernel Version 18.6.0: Thu Apr 25 23:16:27 PDT 2019; root:xnu-4903.261.4~2/RELEASE_X86_64 x86_64

███  ENVIRONMENT
MODE : VirtualBox VM
DOCKER_HOST : tcp://192.168.64.100:2376
DOCKSAL_NFS_PATH : /Users
NFS EXPORTS:

# <ds-nfs docksal
/Users 192.168.64.1 192.168.64.100 -alldirs -maproot=0:0
# ds-nfs>

███  FIN
fin version: 1.86.2

███  DOCKER COMPOSE
EXPECTED VERSION: 1.23.2
docker-compose version 1.23.2, build 1110ad01
docker-py version: 3.6.0
CPython version: 3.6.6
OpenSSL version: OpenSSL 1.1.0h  27 Mar 2018

███  DOCKER
EXPECTED VERSION: 18.09.2

Client: Docker Engine - Community
 Version:           18.09.2
 API version:       1.39
 Go version:        go1.10.8
 Git commit:        6247962
 Built:             Sun Feb 10 04:12:39 2019
 OS/Arch:           darwin/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.2
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.6
  Git commit:       6247962
  Built:            Sun Feb 10 04:20:28 2019
  OS/Arch:          linux/amd64
  Experimental:     false

███  DOCKER MACHINE
EXPECTED VERSION: 0.16.1
docker-machine version 0.16.1, build cce350d7

NAME      ACTIVE   DRIVER       STATE     URL                         SWARM   DOCKER     ERRORS
docksal   *        virtualbox   Running   tcp://192.168.64.100:2376           v18.09.2   

███  DOCKSAL: PROJECTS
project             STATUS                   virtual host                                    project root
mydir               Up 3 minutes (healthy)   mydir.docksal,*.mydir.docksal,mydir.docksal.*   /Users/matt/Sites/mydir

███  DOCKSAL: VIRTUAL HOSTS
*.mydir.docksal
mydir.docksal.*
mydir.docksal

███  DOCKSAL: DNS
Successfully requested http://dns-test.docksal

███  DOCKER: RUNNING CONTAINERS
CONTAINER ID        IMAGE                     COMMAND                  CREATED             STATUS                   PORTS                                                    NAMES
095563dae4d3        docksal/apache:2.4-2.3    "httpd-foreground"       3 minutes ago       Up 3 minutes (healthy)   80/tcp, 443/tcp                                          mydir_web_1
2dcd6ad13880        docksal/cli:2.6-php7.2    "/opt/startup.sh sup…"   3 minutes ago       Up 3 minutes (healthy)   22/tcp, 3000/tcp, 9000/tcp                               mydir_cli_1
124bda6d6ce0        docksal/mysql:5.6-1.4     "docker-entrypoint.s…"   3 minutes ago       Up 3 minutes (healthy)   0.0.0.0:32770->3306/tcp                                  mydir_db_1
1f9a627c1b2d        docksal/ssh-agent:1.2     "docker-entrypoint.s…"   7 days ago          Up 2 hours (healthy)                                                              docksal-ssh-agent
177f687f155b        docksal/dns:1.1           "docker-entrypoint.s…"   7 days ago          Up 2 hours (healthy)     192.168.64.100:53->53/udp                                docksal-dns
d0ebe07be7b8        docksal/vhost-proxy:1.5   "docker-entrypoint.s…"   7 days ago          Up 2 hours (healthy)     192.168.64.100:80->80/tcp, 192.168.64.100:443->443/tcp   docksal-vhost-proxy

███  DOCKER: NETWORKS
NETWORK ID          NAME                DRIVER              SCOPE
858b3672bc12        _default            bridge              local
e2e74f060c68        bridge              bridge              local
a2a66f5f0a70        host                host                local
03b64ca83c7b        mydir_default       bridge              local
9aa94e6512f9        newell_default      bridge              local
c393a81b40de        none                null                local

███  VIRTUALBOX
EXPECTED VERSION: 5.2.26
5.2.30r130521

███  DOCKSAL MOUNTS
 ERROR:  Mounts matching 192.168.64* were not found!

███  HDD Usage
Filesystem                Size      Used Available Use% Mounted on
/dev/sda1                46.1G      5.1G     38.6G  12% /mnt/sda1
  ```

</details>

**Comment by lmakarov** [comment] 2019-10-03 19:07
Ping @achekulaev

**Comment by shelane** [comment] 2019-10-21 22:06
I just did a local test with the latest develop and this site was able to build from `project create`.

**Comment by achekulaev** [comment] 2019-10-22 12:00
Thanks Shelane. Closing as cannot reproduce or fixed with something else then.

**Closed by achekulaev** 2019-10-22 12:00 UTC
