### ISSUE TITLE
Docksal 1.6 breaks file permissions and UID/GID mapping when using older docksal.yml 

### ISSUE THREAD

**Issue by charginghawk** [docksal/docksal#434] opened 2018-01-03 17:45 UTC
**Description**

Docksal 1.6.0 removes _set_cli_uid from fin, which had been setting the docker user's uid and gid in the container to those values for the user on the host. This made it so the docker had the same file permissions in the container that the user had on host.

In May 2017, the Docksal stacks were updated to give cli > environment HOST_UID/HOST_GID arguments that handle this functionality. See:

https://github.com/docksal/docksal/blob/develop/stacks/stack-default-static.yml#L50-L51

If you, like me, are using a docksal.yml that was a copy of one the Docksal stack yml files from before May 2017, you don't have these arguments, and _set_cli_uid was the only thing keeping your file permissions in order.

**Steps to reproduce the issue:**

1. Be on Docksal 1.5.1.
2. Use docksal.yml that's a copy of Docksal's services.yml or stack-default-static.yml from before May 2017.
3. Upgrade to latest Docksal.

**Describe the results you received:**

docker user in the container can't write files anymore (eg npm install in container, it can't create node_modules directory).

```
npm ERR! code EIO
npm ERR! errno -5 
npm ERR! syscall mkdir 
npm ERR! EIO: i/o error, mkdir 'node_modules'
```

**Describe the results you expected:**

File permissions work.

**Local Fix**

Update your docksal.yml so that cli > environment has HOST_UID/HOST_GID arguments, like so:
https://github.com/docksal/docksal/blob/develop/stacks/stack-default-static.yml#L50-L51

**Comment by achekulaev** [comment] 2018-01-04 02:19
@charginghawk you are absolutely correct in your investigations. And I imagine you spend some time investigating the issue since you are pinpointing exactly what happened. I appreciate that.  

However what you call a local fix is the correct way to fix it. Basically removal of `_set_cli_uid` is a feature not a bug. The issue with "full static" `docksal.yml` is that we can not upgrade it for you in your old projects, at the same time keeping too much of legacy compatibility is an effort. We have been keeping `_set_cli_uid` legacy for a year, before finally removing it this December.

You can avoid a need of updating your `docksal.yml` by using Default Stack (or Acquia Stack) in your projects and only extend/override it with `docksal.yml`. Please see my post here: https://blog.docksal.io/docksal-project-configuration-less-is-more-8c6e996b2e48

In that case you would not need to worry about changes like that.

Best,
Alexei

**Comment by lmakarov** [comment] 2018-01-12 20:49
We can close this once https://github.com/docksal/docksal/issues/433 is done.

**Comment by achekulaev** [comment] 2018-02-01 20:02
Closing since #433 is closed now.

**Closed by achekulaev** 2018-02-01 20:02 UTC
Labels: pending, question
