### ISSUE TITLE
Love Docksal! A few minor issues.

### ISSUE THREAD

**Issue by chrisroane** [docksal/docksal#603] opened 2018-06-11 19:04 UTC
We were using lando for a large Drupal 7 site, and it was very slow (mainly because of docker on mac + windows) and had other issues. I've converted the site to use Docksal and things are blazingly fast!

I pretty much got everything working, including full integration with the process on Pantheon. There are a few minor issues that I thought I would bring up, just in case they are bugs or I am doing something wrong:

1. The `fin drush` command works, but we have to first cd into the document root of the site. It would be awesome if fin could update that command to do that automatically and save a step. The idea is that you could run `find drush cc all` from the project directory and it would work. Right now if I do that from the project root, I see the message `No Drupal site found, only 'drush' cache was cleared.`.

2. I got a custom php.ini file loaded, but the `memory_limit` value isn't getting updated. [This](https://gist.github.com/chrisroane/b1c13300c478123a9779c59027198476) is what is in my .docksal/etc/php/php.ini file. Not a huge deal, but the pantheon environment has that setup as 512M and docksal isn't letting me update that from 256M.

3. I got varnish installed and working, but every request is considered a MISS. Not a huge deal, but it would be great if I could get this working in a similar way to what pantheon does. I haven't setup a custom VCL, and I'm wondering if anyone has this working on a drupal site locally... where varnish actually returns a cached page?

I'm sharing this more for the community, just in case people find it useful. But also to see if this is the right way to do this. I created two custom commands:

[init](https://gist.github.com/chrisroane/611404625d83ded12f7323b39ace1a34): This sets the correct node version, runs npm install, composer install, global node module, etc.. Doing this allows us to run one command for the initial setup. We can then run all gulp tasks using `fin bash` and don't have to set this up on the host machine. This is a huge win!

[import-db](https://gist.github.com/chrisroane/fdf25ed4f16dc9641c57e436278ef3a3): This grabs the latest db backup from pantheon via terminus and imports it into the drupal site.

I'm wondering if any of this could be converted to a custom service or addon for better pantheon integration? I was able to get redis, varnish and solr working locally on the site.

I want to thank the team for this software. I can't tell you how happy I am to use what appears to be a solid local site setup.

**Comment by lmakarov** [comment] 2018-06-11 19:37
@chrisroane thanks for the kind words! We are all happy you are enjoying Docksal ❤️ 

> The `fin drush` command works, but we have to first cd into the document root of the site.

With a locally installed Drush you would have to switch into a Drupal docroot directory in order for Drush to pick it up correctly. We intentionally keep this behavior identical and transparent.

> I got a custom php.ini file loaded, but the memory_limit value isn't getting updated

Please provide the necessary debug information as described in the New issues template (`fin sysinfo` and `fin config`). We have this exact case covered in the [automated tests](https://github.com/docksal/service-cli/blob/develop/tests/.docksal/etc/php/php.ini) for `docksal/cli`, so there's most likely something wrong with your local setup.

> I got varnish installed and working, but every request is considered a MISS.

@sean-e-dietrich has been recently looking into updating the `docksal/service-varnish` image and may be able to comment on this.

**Comment by chrisroane** [comment] 2018-06-11 19:47
The drush thing is minor, but that is how lando drush works. It seems that in most cases, when someone would run `fin drush` in the project directory, they expect to have it connect to the docksal drush instance. But I understand your point too.... not a huge deal.

[Here](https://gist.github.com/chrisroane/3c4169385279758ceb1d692ed99a254a) is the results from fin sysinfo and fin config. It is really weird why memory_limit is the only option that doesn't get updated on the box, and the other settings take effect.

Thanks for your quick response!

**Comment by chrisroane** [comment] 2018-06-11 19:58
Looking back at the lando config we were using, it looks like we created a custom command to run drush from the docroot:

drush:
    service: appserver
    cmd:
      - drush
      - '@medstat.local'
      - '--root=/app/build'

So if we wanted this to work the same, we could create a custom command in docksal to do the same thing.

**Comment by achekulaev** [comment] 2018-06-11 20:11
Hi @chrisroane 

On `php.ini` question. You probably expect it to override WEB settings, but `php.ini` only affects command line settings. For WEB override you need to use `.docksal/etc/php/php-fpm.conf`. ([See this doc for details](https://docs.docksal.io/en/v1.9.0/advanced/stack-settings/#php-and-mysql-configuration)). This is not a quirk of Docksal, but the way the official PHP Docker images implement configuration overrides.

On Drush. The only issue with overriding `drush` with your custom script would be that for security reasons built-ins always have precedence, so you can't override `fin drush`, you would need to name your [custom command](https://docs.docksal.io/en/v1.9.0/fin/custom-commands/) something else (`rush`, `_drush`... ) but otherwise you can totally do it

**.docksal/commands/_drush** 

```bash
#!/bin/bash

cd "$PROJECT_ROOT/$DOCROOT"
fin drush "$@"
```

**Comment by chrisroane** [comment] 2018-06-11 20:31
Hmm, the docs say php.ini should apply to both web and cli ".docksal/etc/php/php.ini - global PHP (web and cli) settings overrides". Maybe the docs for that are out of date? It seems the only setting from there that didn't affect the web was memory limit. I added php-fpm.conf for memory limit and it took effect. Thanks!

**Comment by achekulaev** [comment] 2018-06-11 20:35
> the docs say php.ini should apply to both web and cli 

If you could point to the docs that say this please do. It's an error that needs to be corrected.

**Comment by achekulaev** [comment] 2018-06-11 20:40
> the docs say php.ini should apply to both web and cli 

It's... complicated. php.ini affects both, but php-fpm.conf takes precedence for FPM settings and since there is [default php-fpm.conf](https://github.com/docksal/service-cli/blob/develop/7.0/config/php/zz-php-fpm.conf) built-in into the official image it overrides some settings that you set in your php.ini (like memory).

**Comment by chrisroane** [comment] 2018-06-11 20:42
Here is the doc page I was referencing: https://docs.docksal.io/en/v1.9.0/advanced/stack-settings/#php-and-mysql-configuration

**Comment by achekulaev** [comment] 2018-06-12 11:57
@lmakarov we might need to revise wording there ^

**Comment by lmakarov** [comment] 2018-06-12 17:30
Apparently, this update to docs never took place:
https://github.com/docksal/service-cli/issues/21#issuecomment-357071939

Also, the `php.ini` vs `php-fpm.conf` and what takes precedence when needs to be covered better, indeed.

**Comment by achekulaev** [comment] 2018-06-12 21:20
@lmakarov I guess the problem is the wording `global (applies to both cli and fpm)` is untrue for options, that pre-exist in `php-fpm.conf` that is [contained within the image](https://github.com/docksal/service-cli/blob/develop/7.0/config/php/zz-php-fpm.conf). `php.ini` will not override those options for FPM, while it can override other options

**Comment by achekulaev** [comment] 2018-06-13 02:54
Closing in favor of #608

**Closed by achekulaev** 2018-06-13 02:54 UTC
Labels: 🏷question
