### ISSUE TITLE
Cross-platform .yml issue

### ISSUE THREAD

**Issue by ComboPrime** [docksal/docksal#99] opened 2017-01-05 21:11 UTC
Hi--hoping this is a simple fix, as Docksal is the best of the Drupal VMs I've tested so far. I installed and configured a local environment on my Mac, and successfully had a colleague pull the Git repo for the installation and get running on her Mac. But I've hit a wall trying to get the same install running on Windows.

fin 0.15.3 complains about docksal.yml paths having bad characters (username and project name replaced below):

ERROR: for db  Cannot create container for service db: {"message":"create \\c\\Users\\xxxxx\\Sites\\xxxxx\\.docksal\\etc\\mysql\\my.cnf: \"\\\\c\\\\Users\\\\ xxxxx\\\\Sites\\\\ xxxxx\\\\.docksal\\\\etc\\\\mysql\\\\my.cnf\" includes invalid characters for a local volume name, only \"[a-zA-Z0-9][a-zA-Z0-9_.-]\" are allowed"}

ERROR: for cli  Cannot create container for service cli: {"message":"Invalid bind mount spec \"C:\\\\Users\\\\ xxxxx\\\\.babun\\\\cygwin\\\\home\\\\ xxxxx:/.home:ro\": Invalid volume specification: 'C:\\Users\\ xxxxx\\.babun\\cygwin\\home\\ xxxxx:/.home:ro'"}

Thanks for your help, and happy new year--

**Comment by achekulaev** [comment] 2017-01-05 22:40
Hi @ComboPrime 
I need to see your docksal.yml please.

**Comment by achekulaev** [comment] 2017-01-05 23:21
So it's quite possible that a docker-compose bug affected you. 
I would recommend updating fin with `fin update` in your colleague Windows PC. It should update to fin 0.15.4. Where we worked around that bug. After that  `fin start` should work fine. 

I still encourage you to share your `docksal.yml`

**Comment by ComboPrime** [comment] 2017-01-06 05:19
Thank you for the prompt response! Unfortunately, I may not be in the office tomorrow. I’ll update fin and send the docksal.yml file as soon as possible, though.

**Comment by ComboPrime** [comment] 2017-01-06 18:14
Was able to pull the .yml file remotely from my office Mac, but will have to wait until Monday to update fin on the Windows box. Thanks again for help!
[docksal.yml.txt](https://github.com/docksal/docksal/files/690501/docksal.yml.txt)

**Comment by ComboPrime** [comment] 2017-01-09 20:06
Looks like 0.15.4 did indeed fix this. (About your update question: I work primarily on a Mac, but I'm trying to replicate the VM on Windows boxes for my colleagues.)

Thanks again!

**Comment by achekulaev** [comment] 2017-01-09 21:01
@ComboPrime 

> I work primarily on a Mac, but I'm trying to replicate the VM on Windows boxes for my colleagues

This is exactly what Docksal is made for!

I looked at your docksal.yml and indeed 0.15.4 was intended to fix a bug that was bugging your colleague. After docker-compose updated to 1.9.0 the $PROJECT_ROOT variable on Windows was not resolving properly. We had to workaround that. Resolved in https://github.com/docksal/docksal/commit/c9191ca5a2f05a987cad2f4ef53a3640f4f7e752

Closing this one. Thanks for report.

**Closed by achekulaev** 2017-01-09 21:01 UTC
Labels: bug

**Comment by ComboPrime** [comment] 2017-01-16 19:26
Hi Alexei--thanks again for your prompt help on the previous reported issue. It's happening again even with 0.15.4 (or at least something similar is happening). Here are the errors reported when trying to run fin up:

ERROR: for db  Cannot start service db: {"message":"invalid header field value \"oci runtime error: container_linux.go:247: starting container process caused \\\"process_linux.go:359: container init caused \\\\\\\"rootfs_linux.go:53: mounting \\\\\\\\\\\\\\\"/c/Users/user/Sites/project/.docksal/etc/mysql/my.cnf\\\\\\\\\\\\\\\" to rootfs \\\\\\\\\\\\\\\"/mnt/sda1/var/lib/docker/aufs/mnt/059fb3104d97efec7a0994453a0bc92eb36034a4fcbc74e84b761a66d21b42a9\\\\\\\\\\\\\\\" at \\\\\\\\\\\\\\\"/mnt/sda1/var/lib/docker/aufs/mnt/059fb3104d97efec7a0994453a0bc92eb36034a4fcbc74e84b761a66d21b42a9/opt/mysql.conf.d/z_my.cnf\\\\\\\\\\\\\\\" caused \\\\\\\\\\\\\\\"not a directory\\\\\\\\\\\\\\\"\\\\\\\"\\\"\\n\""}

ERROR: for cli  Cannot start service cli: {"message":"invalid header field value \"oci runtime error: container_linux.go:247: starting container process caused \\\"process_linux.go:359: container init caused \\\\\\\"rootfs_linux.go:53: mounting \\\\\\\\\\\\\\\"/c/Users/user/Sites/project/.docksal/etc/php/php-cli.ini\\\\\\\\\\\\\\\" to rootfs \\\\\\\\\\\\\\\"/mnt/sda1/var/lib/docker/aufs/mnt/52220fc3b89eceb1e70d06cb8603366b0e270419855d693925f7afd4c28e855c\\\\\\\\\\\\\\\" at \\\\\\\\\\\\\\\"/mnt/sda1/var/lib/docker/aufs/mnt/52220fc3b89eceb1e70d06cb8603366b0e270419855d693925f7afd4c28e855c/etc/php5/cli/conf.d/z_php.ini\\\\\\\\\\\\\\\" caused \\\\\\\\\\\\\\\"not a directory\\\\\\\\\\\\\\\"\\\\\\\"\\\"\\n\""}
Encountered errors while bringing up the project.
