### ISSUE TITLE
CLI Container startup fails sometimes on lua script project start

### ISSUE THREAD

**Issue by ey-** [docksal/docksal#1288] opened 2020-02-26 23:21 UTC
**Description**

_Sometimes_ the project startup fails when the project is on a paused state and you hit the url via a browser. All containers are started without an issue, except the cli container.
Following can be found in the logs for the vhost-proxy when this happens:

```
2020-02-26 22:56:52 [proxyctl] [lookup]
2020-02-26 22:56:52 [proxyctl] [lookup] Found a project stack 'my-project'...
2020-02-26 22:56:52 [proxyctl] [start]
2020-02-26 22:56:52 [proxyctl] [start] Starting project stack for 'my-project'...
2020-02-26 22:56:52 [proxyctl] [start] Connected proxy to network 'my-project_default'.
2020-02-26 22:56:53 [proxyctl] [start] Stopping docker-gen...
2020-02-26 22:56:53,354 INFO waiting for docker-gen to stop
2020/02/26 22:56:53 Received signal: terminated
2020/02/26 22:56:53 Received signal: terminated
2020-02-26 22:56:53,356 INFO stopped: docker-gen (exit status 0)
docker-gen: stopped
2020-02-26 22:56:53 [proxyctl] [start] Starting containers for my-project...
2020-02-26 22:56:53 [proxyctl] [start] Pass #1...
5bb4250c1b4e
Error response from daemon: OCI runtime create failed: container_linux.go:345: starting container process caused "process_linux.go:430: container init caused \"rootfs_linux.go:58: mounting \\\"/tmp/ssh-XYZQWER/agent.4555\\\" to rootfs \\\"/var/lib/docker/overlay2/SOMEHasH/merged\\\" at \\\"/var/lib/docker/overlay2/SOMEHasH/merged/tmp/ssh-XYZQWER/agent.4555\\\" caused \\\"not a directory\\\"\"": unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type
4854468cc19d
14c75c4daf1b
9f2709ff8492
73628b2e1bb8
Error: failed to start containers: 6c69526e9ba9
crond: USER root pid 13852 cmd /usr/local/bin/proxyctl cron
2020-02-26 22:57:00 [proxyctl] [start] Pass #2...
2020-02-26 22:57:00 [proxyctl] [cron]
2020-02-26 22:57:01 [proxyctl] [stop]
5bb4250c1b4e
Error response from daemon: OCI runtime create failed: container_linux.go:345: starting container process caused "process_linux.go:430: container init caused \"rootfs_linux.go:58: mounting \\\"/tmp/ssh-XYZQWER/agent.4555\\\" to rootfs \\\"/var/lib/docker/overlay2/SOMEHasH/merged\\\" at \\\"/var/lib/docker/overlay2/SOMEHasH/merged/tmp/ssh-XYZQWER/agent.4555\\\" caused \\\"not a directory\\\"\"": unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type
4854468cc19d
14c75c4daf1b
9f2709ff8492
Error: failed to start containers: 6c69526e9ba9
2020-02-26 22:57:01 [proxyctl] [start] Pass #3...
73628b2e1bb8
5bb4250c1b4e
Error response from daemon: OCI runtime create failed: container_linux.go:345: starting container process caused "process_linux.go:430: container init caused \"rootfs_linux.go:58: mounting \\\"/tmp/ssh-XYZQWER/agent.4555\\\" to rootfs \\\"/var/lib/docker/overlay2/SOMEHasH/merged\\\" at \\\"/var/lib/docker/overlay2/SOMEHasH/merged/tmp/ssh-XYZQWER/agent.4555\\\" caused \\\"not a directory\\\"\"": unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type
4854468cc19d
14c75c4daf1b
9f2709ff8492
73628b2e1bb8
Error: failed to start containers: 6c69526e9ba9
2020-02-26 22:57:01 [proxyctl] [start] Starting docker-gen...
2020-02-26 22:57:02,057 INFO spawned: 'docker-gen' with pid 13917
2020/02/26 22:57:02 Generated '/etc/nginx/conf.d/vhosts.conf' from 13 containers
2020/02/26 22:57:02 Running 'proxyctl notify'
2020/02/26 22:57:02 [proxyctl notify]: nginx: the configuration file /usr/local/openresty/nginx/conf/nginx.conf syntax is ok
2020/02/26 22:57:02 [proxyctl notify]: nginx: configuration file /usr/local/openresty/nginx/conf/nginx.conf test is successful
2020/02/26 22:57:02 [proxyctl notify]: 2020/02/26 22:57:02 [notice] 13928#13928: signal process started
2020/02/26 22:57:02 Watching docker events
2020/02/26 22:57:02 Contents of /etc/nginx/conf.d/vhosts.conf did not change. Skipping notification 'proxyctl notify'
2020-02-26 22:57:03,511 INFO success: docker-gen entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
docker-gen: started
```

**Steps to reproduce the issue:**

Feels randomly.

**Describe the results you received:**

CLI Container fails to start when project is in a paused state on gets hit via browser so it is triggered via the lua script from vhost-proxy.

**Describe the results you expected:**

All project related container start without problems.

**Output of `fin config`:**

<details>
  <summary>fin config output</summary>

```
---------------------
COMPOSE_PROJECT_NAME_SAFE: my-project
COMPOSE_FILE:
/home/build-agent/.docksal/stacks/volumes-bind.yml
/home/build-agent/.docksal/stacks/stack-default.yml
/home/build-agent/builds/my-project/.docksal/docksal.yml
ENV_FILE:
/home/build-agent/builds/my-project/.docksal/docksal.env
/home/build-agent/builds/my-project/.docksal/docksal-local.env

PROJECT_ROOT: /home/build-agent/builds/my-project
DOCROOT: .
VIRTUAL_HOST: develop--my-project.my-domain.example
VIRTUAL_HOST_ALIASES: *.develop--my-project.my-domain.example
IP: 192.168.64.100
MYSQL: 192.168.64.100:12345

Docker Compose configuration
---------------------
services:
  cli:
    dns:
    - 192.168.64.100
    - 8.8.8.8
    environment:
      BLACKFIRE_CLIENT_ID: null
      BLACKFIRE_CLIENT_TOKEN: null
      CLI_IMAGE: docksal/cli:php7.2
      COMPOSER_ALLOW_XDEBUG: '1'
      COMPOSER_DISABLE_XDEBUG_WARN: '1'
      DB_IMAGE: docksal/mariadb:10.3
      DOCKSAL_STACK: default
      DOCROOT: .
      DRUSH_ALLOW_XDEBUG: '1'
      DRUSH_OPTIONS_URI: develop--my-project.my-domain.example
      ELASTICSEARCH_HOST: elasticsearch
      ELASTICSEARCH_PORT: '9200'
      GIT_USER_EMAIL: ''
      GIT_USER_NAME: ''
      HOST_GID: '1100'
      HOST_UID: '1100'
      MEMCACHE_HOST: memcached
      MEMCACHE_PORT: '11211'
      MYSQL_DATABASE: drupal
      MYSQL_HOST: db
      MYSQL_PASSWORD: drupal
      MYSQL_PORT: '3306'
      MYSQL_ROOT_PASSWORD: root
      MYSQL_SNAPSHOT_SSH_HOST: my-domain.example
      MYSQL_SNAPSHOT_SSH_PATH: ./db/ffw.sql.gz
      MYSQL_SNAPSHOT_SSH_PORT: '2212'
      MYSQL_SNAPSHOT_SSH_USER: storage
      MYSQL_USER: drupal
      PHP_IDE_CONFIG: null
      SECRET_ACAPI_EMAIL: null
      SECRET_ACAPI_KEY: null
      SECRET_PLATFORMSH_CLI_TOKEN: null
      SECRET_SSH_PRIVATE_KEY: null
      SECRET_TERMINUS_TOKEN: null
      SSH_AUTH_SOCK: /.ssh-agent/proxy-socket
      VIRTUAL_HOST: develop--my-project.my-domain.example
      XDEBUG_CONFIG: remote_connect_back=0 remote_host=192.168.64.1
      XDEBUG_ENABLED: '1'
    hostname: cli
    image: docksal/cli:php7.2
    labels:
      io.docksal.shell: bash
      io.docksal.user: docker
    volumes:
    - docksal_ssh_agent:/.ssh-agent:ro
    - cli_home:/home/docker:rw
    - project_root:/var/www:rw,nocopy,cached
  db:
    dns:
    - 192.168.64.100
    - 8.8.8.8
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: null
      MYSQL_DATABASE: db
      MYSQL_INITDB_SKIP_TZINFO: null
      MYSQL_ONETIME_PASSWORD: null
      MYSQL_PASSWORD: pw
      MYSQL_RANDOM_ROOT_PASSWORD: null
      MYSQL_ROOT_PASSWORD: pw
      MYSQL_USER: drupal
    hostname: db
    image: docksal/mariadb:10.3
    ports:
    - 3306/tcp
    volumes:
    - /home/build-agent/builds/my-project/.docksal/db:/docker-entrypoint-initdb.d:ro
    - db_data:/var/lib/mysql:rw
    - project_root:/var/www:ro,nocopy,cached
  elasticsearch:
    environment:
      discovery.type: single-node
    hostname: elasticsearch
    image: elasticsearch:5.6
    labels:
      io.docksal.virtual-host: elastic.develop--my-project.my-domain.example
    volumes:
    - data01:/usr/share/elasticsearch/data:rw
  mail:
    dns:
    - 192.168.64.100
    - 8.8.8.8
    hostname: mail
    image: mailhog/mailhog
    labels:
      io.docksal.cert-name: none
      io.docksal.virtual-host: mail.develop--my-project.my-domain.example,mail.develop--my-project.my-domain.example.*
      io.docksal.virtual-port: '8025'
    volumes:
    - project_root:/var/www:ro,nocopy,cached
  memcached:
    command:
    - -m
    - '128'
    dns:
    - 192.168.64.100
    - 8.8.8.8
    hostname: memcached
    image: memcached:1.4-alpine
  web:
    depends_on:
      cli:
        condition: service_started
    dns:
    - 192.168.64.100
    - 8.8.8.8
    environment:
      APACHE_BASIC_AUTH_PASS: auth
      APACHE_BASIC_AUTH_USER: pass
      APACHE_DOCUMENTROOT: /var/www/.
      APACHE_FCGI_HOST_PORT: cli:9000
    hostname: web
    image: docksal/apache:2.4-2.3
    labels:
      io.docksal.cert-name: none
      io.docksal.permanent: "false"
      io.docksal.project-root: /home/build-agent/builds/my-project
      io.docksal.virtual-host: develop--my-project.my-domain.example,*.develop--my-project.my-domain.example,develop--my-project.my-domain.example.*
    volumes:
    - project_root:/var/www:ro,nocopy,cached
version: '2.1'
volumes:
  cli_home: {}
  data01:
    driver: local
  db_data: {}
  docksal_ssh_agent:
    external: true
    name: docksal_ssh_agent
  project_root:
    driver: local
    driver_opts:
      device: /home/build-agent/builds/my-project
      o: bind
      type: none

---------------------

```

</details>

<br>

**Output of `fin sysinfo`:**

<details>
  <summary>fin sysinfo output</summary>

  ```
███  OS
Linux Ubuntu 18.04
Linux panasonic 4.15.0-76-generic #86-Ubuntu SMP Fri Jan 17 17:24:28 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

███  ENVIRONMENT
MODE : Linux Kernel
DOCKER_HOST :

███  FIN
fin version: 1.93.0

███  DOCKER COMPOSE
EXPECTED VERSION: 1.24.1
docker-compose version 1.24.1, build 4667896b
docker-py version: 3.7.3
CPython version: 3.6.8
OpenSSL version: OpenSSL 1.1.0j  20 Nov 2018

███  DOCKER
EXPECTED VERSION: 19.03.4

Client: Docker Engine - Community
 Version:           19.03.4
 API version:       1.40
 Go version:        go1.12.10
 Git commit:        9013bf583a
 Built:             Fri Oct 18 15:54:09 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.4
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.10
  Git commit:       9013bf583a
  Built:            Fri Oct 18 15:52:40 2019
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.2.6
  GitCommit:        894b81a4b802e4eb2a91d1ce216b8817763c29fb
 runc:
  Version:          1.0.0-rc8
  GitCommit:        425e105d5a03fabd737a126ad93d62a9eeede87f
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683

███  DOCKSAL: PROJECTS
project                       STATUS                    virtual host                                                                                                                                                                     project root
my-project         Up 18 minutes (healthy)   my-project.example,*.my-project.example,my-project.example.*                                                                              /home/build-agent/builds/my-project

███  DOCKSAL: VIRTUAL HOSTS
*.my-project.example
my-project.example.*
my-project.example
elastic.my-project.example
mail.my-project.example.*
mail.my-project.example
styleguide-my-project.example
varnish.my-project.example

███  DOCKSAL: DNS
curl: (6) Could not resolve host: dns-test.docksal
ERROR: Requesting http://dns-test.docksal failed!

███  DOCKER: RUNNING CONTAINERS
CONTAINER ID        IMAGE                     COMMAND                  CREATED             STATUS                    PORTS                                      NAMES
4a05d8d3373a        docksal/apache:2.4-2.3    "httpd-foreground"       13 hours ago        Up 19 minutes (healthy)   80/tcp, 443/tcp                            my-project_web_1
f32a007ba27a        docksal/cli:php7.3        "/opt/startup.sh sup…"   13 hours ago        Up 18 minutes (healthy)   22/tcp, 3000/tcp, 9000/tcp                 my-project_cli_1
8eb4db65e4d9        docksal/ssh-agent:1.3     "docker-entrypoint.s…"   16 hours ago        Up 16 hours (healthy)                                                docksal-ssh-agent
d2a4e189ae01        docksal/dns:1.1           "docker-entrypoint.s…"   16 hours ago        Up 16 hours (healthy)     192.168.64.100:53->53/udp                  docksal-dns
beb417aa83a0        docksal/vhost-proxy:1.5   "docker-entrypoint.s…"   16 hours ago        Up 16 hours (healthy)     0.0.0.0:80->80/tcp, 0.0.0.0:443->443/tcp   docksal-vhost-proxy
88d29f3951f0        emgag/varnish:6.0         "/init.sh"               12 days ago         Up 18 minutes             80/tcp, 6082/tcp                           my-project_varnish_1
ad85d9fb1f6f        docksal/mariadb:10.3      "docker-entrypoint.s…"   13 days ago         Up 18 minutes (healthy)   0.0.0.0:33019->3306/tcp                    my-project_db_1
4a02c679f419        mailhog/mailhog           "MailHog"                13 days ago         Up 18 minutes             1025/tcp, 8025/tcp                         my-project_mail_1
b15c7e1ebdb5        elasticsearch:7.1.0       "/usr/local/bin/dock…"   2 weeks ago         Up 18 minutes             9200/tcp, 9300/tcp                         my-project_elasticsearch_1
a9f37689dca0        memcached:1.4-alpine      "docker-entrypoint.s…"   3 months ago        Up 18 minutes             11211/tcp                                  my-project_memcached_1

███  DOCKER: NETWORKS
NETWORK ID          NAME                                  DRIVER              SCOPE
8da44bc1fc20        bridge                                bridge              local
19bbd540ad6c        host                                  host                local
a1ba12972de9        none                                  null                local
6049f83dd4af        my-project_default         bridge              local


███  HDD Usage
Filesystem      Size  Used Avail Use% Mounted on
udev            7.7G     0  7.7G   0% /dev
tmpfs           1.6G  2.2M  1.6G   1% /run
/dev/sda2        79G   75G   89M 100% /
tmpfs           7.7G     0  7.7G   0% /dev/shm
tmpfs           5.0M     0  5.0M   0% /run/lock
tmpfs           7.7G     0  7.7G   0% /sys/fs/cgroup
/dev/loop1       92M   92M     0 100% /snap/core/8592
/dev/loop2       92M   92M     0 100% /snap/core/8689
tmpfs           1.6G     0  1.6G   0% /run/user/1100
  ```

</details>

**Comment by BR0kEN-** [comment] 2020-02-27 19:42
Could it be somehow related to the `docksal_ssh_agent` volume? In my observation this happens only for ci-agent stacks.

**Comment by lmakarov** [comment] 2020-03-03 17:37
@sergey-zabolotny and I looked into this further. The issue is indeed with the CI builds only and is caused by the recently added support for the SSH Agent Forwarding feature in CI (https://github.com/docksal/docksal/pull/1080).

In a nutshell, the ssh-agent socket that is passed to the server during the build gets written into the stack config of a project during the build. The socket is mounted as a bind mount from the host. When the build is over, the socket is gone, but the bind mount is still there. This does not cause issues until vhost-proxy tries to restart a stopped project stack with a missing mount in its config.

Doing `fin up` in the project folder in the server fixes the issue, since `fin` uses `docker-compose` to update the stack config and recreate affected containers. Unfortunately, vhost-proxy has to operate at a lower lever - there is no fin/docker-compose/Docksal embedded inside the vhost-proxy container - and it cannot update/recreate affected containers.

The solution for now is to disabled SSH agent forwarding on sandbox servers:

```
# Run this on the sandbox server
fin config set --global DOCKSAL_SSH_AGENT_USE_HOST=0
```

**Comment by lmakarov** [comment] 2020-04-08 16:55
Looks like the changes in #1291 did not help. Reopening.

**Comment by sergey-zabolotny** [comment] 2020-05-14 13:15
already merged https://github.com/docksal/docksal/pull/1308 fixes this issue.

**Closed** 2020-05-14 18:24 UTC
Labels: investigation, 🏷bug
