### ISSUE TITLE
Docksal OpenSSL?

### ISSUE THREAD

**Issue by loopy3025** [docksal/docksal#625] opened 2018-06-20 13:12 UTC
Our network here at my job has changed rather drastically of late and I've finally been able to get a Drupal 7 and Drupal 8 site running on my local dev using both http and https. I am ecstatic! There's just one more roadblock and that is downloading and enabling modules. 

I run
```
$ frush en examples -y
```
and I get
```
examples was not found.                                                                                                            [warning]
simplexml_load_file(): I/O warning : failed to load external entity "" Project.php:74                                              [warning]
Failed to get available update data from https://updates.drupal.org/release-history/examples/8.x  
```
I googled a bunch and found this telling me to enable the open.ssl extension in php: https://www.drupal.org/project/infrastructure/issues/2661298

And this discussing enabling php modules:
https://github.com/docksal/service-cli/issues/9

When I tried adding this to the site's .docksal\etc\php\php.ini file, drupal got very, very angry with me when I ran cache-rebuild.
```
extension_dir=C:/PHP7/ext
extension=php_openssl.dll
```
I'm wondering if all that is even necessary, though.

**Output of `fin config`:**

<details>
  <summary>fin config output</summary>

```
---------------------
COMPOSE_PROJECT_NAME_SAFE: examples
COMPOSE_FILE:
C:/Users/afasoldt/.babun/cygwin/home/afasoldt/.docksal/stacks/volumes-bind.yml
C:/Users/afasoldt/.babun/cygwin/home/afasoldt/.docksal/stacks/stack-default.yml
C:/Users/afasoldt/.babun/cygwin/home/afasoldt/projects/examples/.docksal/docksal.yml
ENV_FILE:
C:/Users/afasoldt/.babun/cygwin/home/afasoldt/projects/examples/.docksal/docksal.env
C:/Users/afasoldt/.babun/cygwin/home/afasoldt/projects/examples/.docksal/docksal-local.env

PROJECT_ROOT: /c/Users/afasoldt/.babun/cygwin/home/afasoldt/projects/examples
DOCROOT: docroot
VIRTUAL_HOST: examples.docksal
VIRTUAL_HOST_ALIASES: *.examples.docksal
IP: 192.168.64.100
MYSQL: 192.168.64.100:32771

Docker Compose configuration
---------------------
services:
  cli:
    dns:
    - 192.168.64.100
    - 8.8.8.8
    environment:
      BLACKFIRE_CLIENT_ID: null
      BLACKFIRE_CLIENT_TOKEN: null
      DOCROOT: docroot
      HOST_GID: null
      HOST_UID: null
      SECRET_ACAPI_EMAIL: null
      SECRET_ACAPI_KEY: null
      SECRET_SSH_PRIVATE_KEY: null
      SECRET_TERMINUS_TOKEN: null
      VIRTUAL_HOST: examples.docksal
      XDEBUG_CONFIG: remote_connect_back=0 remote_host=192.168.64.1
      XDEBUG_ENABLED: '0'
    hostname: cli
    image: docksal/cli:2.1-php7.1
    volumes:
    - docksal_ssh_agent:/.ssh-agent:ro
    - /home/docker
    - project_root:/var/www:rw,nocopy
  db:
    dns:
    - 192.168.64.100
    - 8.8.8.8
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: null
      MYSQL_DATABASE: default
      MYSQL_INITDB_SKIP_TZINFO: null
      MYSQL_ONETIME_PASSWORD: null
      MYSQL_PASSWORD: user
      MYSQL_RANDOM_ROOT_PASSWORD: null
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
    hostname: db
    image: docksal/db:1.2-mysql-5.6
    ports:
    - 0:3306/tcp
    volumes:
    - project_root:/var/www:ro,nocopy
  web:
    depends_on:
      cli:
        condition: service_started
    dns:
    - 192.168.64.100
    - 8.8.8.8
    environment:
      APACHE_BASIC_AUTH_PASS: null
      APACHE_BASIC_AUTH_USER: null
      APACHE_DOCUMENTROOT: /var/www/docroot
    hostname: web
    image: docksal/web:2.1-apache2.4
    labels:
      io.docksal.project-root: /c/Users/afasoldt/.babun/cygwin/home/afasoldt/projects/examples
      io.docksal.virtual-host: examples.docksal,*.examples.docksal,examples.docksal.*
    volumes:
    - project_root:/var/www:ro,nocopy
version: '2.1'
volumes:
  docksal_ssh_agent:
    external: true
    name: docksal_ssh_agent
  project_root:
    driver: local
    driver_opts:
      device: /c/Users/afasoldt/.babun/cygwin/home/afasoldt/projects/examples
      o: bind
      type: none

---------------------

```

</details>

<br>

**Output of `fin sysinfo`:**

<details>
  <summary>fin sysinfo output</summary>

  ```
███  OS
Cygwin Windows 10.0
CYGWIN_NT-10.0-WOW W2UA7502F80 1.7.35(0.287/5/3) 2015-03-04 12:07 i686 Cygwin
Mode: Docker for Windows

███  FIN
fin version: 1.60.2

███  ENVIRONMENT
DOCKER_HOST             |
 WARNING:  Non-default DOCKER_HOST

███  DOCKER
EXPECTED VERSION: 18.03.1-ce

Client:
 Version:      18.03.1-ce
 API version:  1.37
 Go version:   go1.9.5
 Git commit:   9ee9f40
 Built:        Thu Apr 26 07:12:48 2018
 OS/Arch:      windows/amd64
 Experimental: false
 Orchestrator: swarm

Server:
 Engine:
  Version:      18.03.1-ce
  API version:  1.37 (minimum version 1.12)
  Go version:   go1.9.5
  Git commit:   9ee9f40
  Built:        Thu Apr 26 07:22:38 2018
  OS/Arch:      linux/amd64
  Experimental: false

███  DOCKER INFO
Containers: 12
 Running: 12
 Paused: 0
 Stopped: 0
Images: 11
Server Version: 18.03.1-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 773c489c9c1b21a6d78b5c538cd395416ec50f88
runc version: 4fc53a81fb7c994640722ac585fa9ca548971871
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.87-linuxkit-aufs
Operating System: Docker for Windows
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 3.837GiB
Name: linuxkit-00155de68f3e
ID: 6LBF:Q7ZL:4QZF:3P7W:LYEL:QTSK:KQRP:2R3F:BKKM:EKIJ:4PT7:ANHD
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 66
 Goroutines: 76
 System Time: 2018-06-20T13:11:08.000942Z
 EventsListeners: 3
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

███  DOCKER COMPOSE
EXPECTED VERSION: 1.21.1
docker-compose version 1.21.1, build 7641a569
docker-py version: 3.2.1
CPython version: 3.6.4
OpenSSL version: OpenSSL 1.0.2k  26 Jan 2017

███  DOCKER MACHINE
EXPECTED VERSION: 0.14.0
docker-machine.exe version 0.14.0, build 89b8332

NAME   ACTIVE   DRIVER   STATE   URL   SWARM   DOCKER   ERRORS

███  DOCKER: IMAGES
REPOSITORY                 TAG                 IMAGE ID            CREATED             SIZE
docksal/cli                2.2-php7.1          f8397b8a269f        2 weeks ago         867MB
docksal/db                 1.2-mysql-5.6       0f0acba4c6d1        2 months ago        256MB
docksal/cli                2.1-php7.1          4c7331d4cf77        2 months ago        950MB
docksal/cli                2.0-php5.6          0fea463bfbd9        3 months ago        887MB
docksal/vhost-proxy        1.2                 a1c980537985        3 months ago        166MB
docker4w/nsenter-dockerd   latest              cae870735e91        7 months ago        187kB
docksal/cli                1.3-php5            80248f5ea845        9 months ago        814MB
docksal/web                2.1-apache2.4       32c1d32eba6d        9 months ago        87.5MB
docksal/db                 1.1-mysql-5.6       6feb79af9597        11 months ago       298MB
docksal/dns                1.0                 20c7a535479d        17 months ago       61.6MB
docksal/ssh-agent          1.0                 148220cc033d        17 months ago       12.2MB

███  DOCKER: CONTAINERS
CONTAINER ID        IMAGE                       COMMAND                  CREATED             STATUS                    PORTS                                                       NAMES
3f9ec9be6394        docksal/web:2.1-apache2.4   "httpd-foreground"       38 minutes ago      Up 38 minutes             80/tcp, 443/tcp                                             examples_web_1
8665fd98d500        docksal/cli:2.1-php7.1      "/opt/startup.sh sup…"   38 minutes ago      Up 38 minutes (healthy)   22/tcp, 3000/tcp, 9000/tcp                                  examples_cli_1
5f75991cf370        docksal/db:1.2-mysql-5.6    "/entrypoint.sh mysq…"   19 hours ago        Up 38 minutes             0.0.0.0:32771->3306/tcp                                     examples_db_1
a87734106f95        docksal/ssh-agent:1.0       "/run.sh ssh-agent"      21 hours ago        Up 18 hours                                                                           docksal-ssh-agent
3dc4d718047b        docksal/dns:1.0             "/opt/entrypoint.sh …"   21 hours ago        Up 18 hours               192.168.64.100:53->53/udp                                   docksal-dns
545f134c4716        docksal/vhost-proxy:1.2     "docker-entrypoint.s…"   21 hours ago        Up 18 hours               192.168.64.100:8080->80/tcp, 192.168.64.100:8443->443/tcp   docksal-vhost-proxy

███  HDD Usage
Caption  FreeSpace     Size
C:       141581553664  255086030848
D:       999846887424  1000068870144
E:


███  RAM Usage
find: ‘Available Physical Memory’: No such file or directory

███  RAM Usage per container
CONTAINER ID        NAME                  CPU %               MEM USAGE / LIMIT     MEM %               NET I/O             BLOCK I/O           PIDS
3f9ec9be6394        examples_web_1        0.03%               5.52MiB / 3.837GiB    0.14%               1.22kB / 0B         0B / 0B             82
8665fd98d500        examples_cli_1        0.01%               30.41MiB / 3.837GiB   0.77%               541kB / 388kB       16MB / 28.7kB       5
5f75991cf370        examples_db_1         0.03%               474.1MiB / 3.837GiB   12.07%              386kB / 540kB       365kB / 5.37MB      22
a87734106f95        docksal-ssh-agent     0.00%               1.367MiB / 3.837GiB   0.03%               4.79kB / 0B         4.91MB / 0B         2
3dc4d718047b        docksal-dns           0.09%               16.52MiB / 3.837GiB   0.42%               576kB / 1.05MB      15.4MB / 0B         10
545f134c4716        docksal-vhost-proxy   0.09%               19.91MiB / 3.837GiB   0.51%               313kB / 315kB       38.3MB / 28.7kB     14

  ```

</details>

**Comment by loopy3025** [comment] 2018-06-20 13:56
We're probably going to set up drush to run natively as well, but it would be cool to see if this can still be done from the container instead.

**Comment by sean-e-dietrich** [comment] 2018-06-20 14:40
@loopy3025 looks like you are using your local machine path for the `extension_dir` you would have to use the directory path within the `cli` container.

**Comment by loopy3025** [comment] 2018-06-20 14:57
@sean-e-dietrich There doesn't appear to be an extensions folder in the container. :(
Or do you mean I should be using \C\PHP7\ext

**Comment by shelane** [comment] 2018-06-20 15:12
So the issue I had with this was that our firewall does an SSL inspection on all https traffic. So, I had two options, get our root certs installed into the container or get an exception placed in the firewall for https://udpates.drupal.org. I tried the first. https://github.com/docksal/docksal/issues/518 I think I got close to solving it, but in the end, an approval was point in place for the firewall rule and I can now run drush dl and drush up in the container. So, one way to test is to run `fin exec curl https://updates.drupal.org` and then `fin exec curl -k https://updates.drupal.org` and compare the results. If the first is blocked and the second is not, then I would suspect they are doing something similar. If you are not able to get the firewall rule into place, you may look into the SSL cert route.

**Comment by sean-e-dietrich** [comment] 2018-06-20 15:25
@loopy3025 the default `extension_dir` should be located 

```
/usr/local/lib/php/extensions/no-debug-non-zts-20160303
```

Yours should be the same, but if you remove your line set in your `php.ini` file.

```
fin project restart
fin exec "php -i | grep extension_dir"
```

It should read something like this:

```
extension_dir => /usr/local/lib/php/extensions/no-debug-non-zts-20160303 => /usr/local/lib/php/extensions/no-debug-non-zts-20160303
sqlite3.extension_dir => no value => no value
```

**Comment by loopy3025** [comment] 2018-06-20 15:55
Thanks to the both of you. I'll check all that out!

**Comment by loopy3025** [comment] 2018-06-20 16:05
Hmmm...

![snip1](https://user-images.githubusercontent.com/6729935/41670419-42b8d2ce-7482-11e8-97e5-437ce9dc99a6.PNG)

![snip2](https://user-images.githubusercontent.com/6729935/41670425-44aff10c-7482-11e8-87b7-95c2f2c46bc9.PNG)

**Comment by shelane** [comment] 2018-06-20 17:13
That was the same for me. I would get it on my computer, but not running it within the container. My host computer has the certs installed, the container did not.

**Comment by achekulaev** [comment] 2018-06-20 18:27
Openssl seems to be already enabled since 2.2.

```
14:26:03 ~/Projects/canvas/vision_us
§ fin config | grep docksal/cli
    image: docksal/cli:2.2-php7.1

14:26:14 ~/Projects/canvas/vision_us
§ fin exec php -m | grep openssl
openssl

14:27:24 ~/Projects/canvas/vision_us
§ fin exec openssl version
OpenSSL 1.1.0f  25 May 2017
```

**Comment by loopy3025** [comment] 2018-06-20 18:49
Rats. Do you think my only recourse is to have the exception added to the firewall? Or is the fact that I can access it without the container mean that the exception already exists?

This is the same cert that was added to my windows certs to get everything else working
![cert1](https://user-images.githubusercontent.com/6729935/41678340-d4d4c684-7498-11e8-809e-5cd526744e84.PNG)

I added it here, but everything was commented out before. That means it was already using the Windows one, right?
![cert2](https://user-images.githubusercontent.com/6729935/41678395-f9cd4ad8-7498-11e8-8a2c-acf13106bbcc.PNG)

poop
![cert3](https://user-images.githubusercontent.com/6729935/41678397-fb7f72c0-7498-11e8-83f3-4f7dd2c346c5.PNG)

**Comment by achekulaev** [comment] 2018-06-20 19:57
```
fin exec curl -v https://updates.drupal.org/release-history/examples.7.x
```

Should give you more info on whether it is a connectivity issue.

**Comment by achekulaev** [comment] 2018-06-26 17:09
@loopy3025 please update the issue with comments when you have ability.

**Comment by loopy3025** [comment] 2018-06-27 15:17
We are having terrible issues with our certs. I had everything running last week and now it's all wrecked again. I wish I could remember what, specifically, I did to fix this. Once we get certs figured out, I'll try to backtrack and see what I did.

**Comment by loopy3025** [comment] 2018-06-27 16:54
OMG

Well, we spent two days trying to figure out why docksal suddenly quit working. It's because I changed my computer password. When you do that, you need to:

1. Go to Docker -> Shared Drives
2. Un-check your shared drive
3. Apply
4. Wait for it to restart
5. Go back to Docker -> Shared Drives
6. Re-check the drive you want to share
7. Click Apply

I repeat: OMG

There are three things that we have done since this was resolved. I'm sorry, but it's possible it could have been resolved by any of these things:

We imported a cert that was very specific to our company.  Kitematic is somewhat upset about using a self-signed cert, but at least everything works.

It is also possible that enabling openssl on the computer level (rather than the vm level) may have also had something to do with this working now. I really wish I could say. I did just disable it, then restart babun and my containers still started fine, so I'm not sure that would have made a difference. Then again, it's possible I'd have to restart docker itself in order for that change to have made an impact. Not sure.

Lastly, we switched the ports docksal is using to 8080 and 8443 because our network is dedicating 80 to corporate processes that we cannot stop.

![image](https://user-images.githubusercontent.com/6729935/41988038-f1a211ac-7a08-11e8-9345-162776936510.png)

FYI, a tip for checking to see whether the certs location is set correctly is to use the echo $CURL_CA_BUNDLE command and then to use the cat command on that file from the command line.

At any rate, thanks for your help!

**Comment by achekulaev** [comment] 2018-06-27 20:17
@loopy3025 thanks, this feedback is very valuable! I have actually created a ticket to improve life for people who would meet same issues https://github.com/docksal/docksal/issues/657

**Comment by loopy3025** [comment] 2018-06-29 14:29
So it turns out that, although I fixed my other problems, our download problem has reared it's head again. curl is fine. fin exec curl is not.

![image](https://user-images.githubusercontent.com/6729935/42097866-3bf1d830-7b87-11e8-8a39-6b84b5ba0da6.png)

**Comment by loopy3025** [comment] 2018-06-29 14:30
Now that is definitely the wrong CA Path. It is going to the wrong file.

**Comment by achekulaev** [comment] 2018-06-29 14:32
Frankly speaking I don't even have enough understanding how it works. `curl` error says "could not resolve. Which sounds like DNS issue to me. Is OpenSSL somehow affects DNS resolution?

**Comment by loopy3025** [comment] 2018-06-29 14:39
It seems to be a problem with wget finding the right cert. We've added .wgetrc to the main folder and it doesn't seem to be working. 

![image](https://user-images.githubusercontent.com/6729935/42098360-b3510936-7b88-11e8-82a3-e1c55700630f.png)

**Comment by loopy3025** [comment] 2018-06-29 14:40
@achekulaev  I'm not sure. We'll keep you posted.

**Comment by achekulaev** [comment] 2018-06-29 14:41
@loopy3025 

```
nslookup updates.drupal.org
```

**Comment by loopy3025** [comment] 2018-06-29 14:41
I think we're using openssl at the root computer php level so I don't think that would be affecting it.

**Comment by loopy3025** [comment] 2018-06-29 15:33
Okay. I'll have a look.

**Comment by loopy3025** [comment] 2018-06-29 15:38
Well, Aleksi. This is interesting. 

![image](https://user-images.githubusercontent.com/6729935/42101377-ee9ce8cc-7b90-11e8-9f23-bf8ec900840d.png)

**Comment by loopy3025** [comment] 2018-06-29 15:40
Even in cmd, it says we're running it from the docksal server.  Network says we are not banned from Google DNS. Why would Docksal be taking over like this? Won't that cause authentication issues?

![image](https://user-images.githubusercontent.com/6729935/42101461-23a4fb40-7b91-11e8-9d20-85b7cfd45c3c.png)

**Comment by loopy3025** [comment] 2018-06-29 15:47
## sysinfo

<details><summary>CLICK</summary>
<p>

####
```
# afasoldt @ W2UA7502F80 in ~/projects/drupal8/docroot on git:master x [11:38:00]
$ fin sysinfo
███  OS
Cygwin Windows 10.0
CYGWIN_NT-10.0-WOW W2UA7502F80 1.7.35(0.287/5/3) 2015-03-04 12:07 i686 Cygwin
Mode: Docker for Windows

███  FIN
fin version: 1.60.2

███  ENVIRONMENT
DOCKER_HOST             |
 WARNING:  Non-default DOCKER_HOST

███  DOCKER
EXPECTED VERSION: 18.03.1-ce

Client:
 Version:      18.03.1-ce
 API version:  1.37
 Go version:   go1.9.5
 Git commit:   9ee9f40
 Built:        Thu Apr 26 07:12:48 2018
 OS/Arch:      windows/amd64
 Experimental: false
 Orchestrator: swarm

Server:
 Engine:
  Version:      18.03.1-ce
  API version:  1.37 (minimum version 1.12)
  Go version:   go1.9.5
  Git commit:   9ee9f40
  Built:        Thu Apr 26 07:22:38 2018
  OS/Arch:      linux/amd64
  Experimental: false

███  DOCKER INFO
Containers: 14
 Running: 6
 Paused: 0
 Stopped: 8
Images: 11
Server Version: 18.03.1-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 773c489c9c1b21a6d78b5c538cd395416ec50f88
runc version: 4fc53a81fb7c994640722ac585fa9ca548971871
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.87-linuxkit-aufs
Operating System: Docker for Windows
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 3.837GiB
Name: linuxkit-00155de68f3e
ID: 5NXN:LKPH:WEYZ:OIVK:RVU5:D335:NWND:TEVD:LBEG:LEZC:FDAT:M6EK
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 66
 Goroutines: 76
 System Time: 2018-06-29T15:43:41.2213349Z
 EventsListeners: 3
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

███  DOCKER COMPOSE
EXPECTED VERSION: 1.21.1
docker-compose version 1.21.1, build 7641a569
docker-py version: 3.2.1
CPython version: 3.6.4
OpenSSL version: OpenSSL 1.0.2k  26 Jan 2017

███  DOCKER MACHINE
EXPECTED VERSION: 0.14.0
docker-machine.exe version 0.14.0, build 89b8332

NAME   ACTIVE   DRIVER   STATE   URL   SWARM   DOCKER   ERRORS

███  DOCKER: IMAGES
REPOSITORY                 TAG                 IMAGE ID            CREATED             SIZE
docksal/cli                2.2-php7.1          f8397b8a269f        3 weeks ago         867MB
docksal/db                 1.2-mysql-5.6       0f0acba4c6d1        2 months ago        256MB
docksal/cli                2.1-php7.1          4c7331d4cf77        2 months ago        950MB
docksal/cli                2.0-php5.6          0fea463bfbd9        3 months ago        887MB
docksal/vhost-proxy        1.2                 a1c980537985        3 months ago        166MB
docker4w/nsenter-dockerd   latest              cae870735e91        8 months ago        187kB
docksal/cli                1.3-php5            80248f5ea845        9 months ago        814MB
docksal/web                2.1-apache2.4       32c1d32eba6d        10 months ago       87.5MB
docksal/db                 1.1-mysql-5.6       6feb79af9597        11 months ago       298MB
docksal/dns                1.0                 20c7a535479d        17 months ago       61.6MB
docksal/ssh-agent          1.0                 148220cc033d        17 months ago       12.2MB

███  DOCKER: CONTAINERS
CONTAINER ID        IMAGE                       COMMAND                  CREATED             STATUS                    PORTS                                                       NAMES
9c1f9636b75e        docksal/web:2.1-apache2.4   "httpd-foreground"       47 hours ago        Up 13 minutes             80/tcp, 443/tcp                                             drupal8_web_1
d735666f5934        docksal/db:1.2-mysql-5.6    "/entrypoint.sh mysq…"   47 hours ago        Up 13 minutes             0.0.0.0:32768->3306/tcp                                     drupal8_db_1
f41907ece0d4        docksal/cli:2.2-php7.1      "/opt/startup.sh sup…"   47 hours ago        Up 13 minutes (healthy)   22/tcp, 3000/tcp, 9000/tcp                                  drupal8_cli_1
b8dab66cc344        docksal/ssh-agent:1.0       "/run.sh ssh-agent"      3 days ago          Up 13 minutes                                                                         docksal-ssh-agent
f147cbe53275        docksal/dns:1.0             "/opt/entrypoint.sh …"   3 days ago          Up 13 minutes             192.168.64.100:53->53/udp                                   docksal-dns
0a8a2b2a9336        docksal/vhost-proxy:1.2     "docker-entrypoint.s…"   3 days ago          Up 13 minutes             192.168.64.100:8080->80/tcp, 192.168.64.100:8443->443/tcp   docksal-vhost-proxy

███  HDD Usage
Caption  FreeSpace       Size
C:       139991822336    255086030848
D:       999846887424    1000068870144
E:
V:       13126863556608  49741906042880


███  RAM Usage
find: ‘Available Physical Memory’: No such file or directory

███  RAM Usage per container
CONTAINER ID        NAME                  CPU %               MEM USAGE / LIMIT     MEM %               NET I/O             BLOCK I/O           PIDS
9c1f9636b75e        drupal8_web_1         0.08%               5.746MiB / 3.837GiB   0.15%               1.43kB / 0B         8.12MB / 0B         82
d735666f5934        drupal8_db_1          0.04%               471.4MiB / 3.837GiB   12.00%              15.9kB / 810kB      35.9MB / 569kB      22
f41907ece0d4        drupal8_cli_1         1.71%               54.75MiB / 3.837GiB   1.39%               812kB / 30.2kB      121MB / 53.2kB      5
b8dab66cc344        docksal-ssh-agent     0.00%               1.367MiB / 3.837GiB   0.03%               1.87kB / 0B         2.83MB / 0B         2
f147cbe53275        docksal-dns           0.19%               16.24MiB / 3.837GiB   0.41%               36.1kB / 66.7kB     17.7MB / 4.1kB      10
0a8a2b2a9336        docksal-vhost-proxy   0.17%               19.52MiB / 3.837GiB   0.50%               7.74kB / 0B         37.6MB / 16.4kB     12
```
</p>
</details>

**Comment by loopy3025** [comment] 2018-06-29 17:36
We're going through your instructions here right now. We'll let you know how it goes.
https://blog.docksal.io/issues-with-corporate-networks-or-vpn-blocking-dns-b96b131c2212

**Comment by achekulaev** [comment] 2018-06-29 18:13
@loopy3025 can you please run something for me and show output

```
ipconfig /all | grep "Primary WINS"
```

I am creating a functionality to auto-resolve issues like the one you experience right now and need help from windows users in testing.

**Comment by loopy3025** [comment] 2018-06-29 18:31
Sure. FYI, w're now getting this after setting the IP from your blog post.

![image](https://user-images.githubusercontent.com/6729935/42108636-1c7e1e1a-7ba9-11e8-8556-51a5685a097b.png)

I'll go run that command now.

**Comment by loopy3025** [comment] 2018-06-29 18:33
![image](https://user-images.githubusercontent.com/6729935/42108729-57a8e916-7ba9-11e8-80c0-da1a24de3dd1.png)

**Comment by loopy3025** [comment] 2018-06-29 18:45
![image](https://user-images.githubusercontent.com/6729935/42109268-115ef584-7bab-11e8-9587-a6587cca942e.png)

**Comment by loopy3025** [comment] 2018-06-29 18:48
![image](https://user-images.githubusercontent.com/6729935/42109382-6b9b2c0c-7bab-11e8-982e-009d71cf44b7.png)

![image](https://user-images.githubusercontent.com/6729935/42109396-752cc00a-7bab-11e8-8f9a-0affa769ec09.png)

**Comment by justinlevi** [comment] 2018-06-29 18:57
We've got about 4 people so far running into the same issue.

**Comment by achekulaev** [comment] 2018-06-29 19:30
Ok so now you have solved the DNS issue, which clearly was present. 
Now it is down to wget and configuring it properly.

**Comment by achekulaev** [comment] 2018-06-29 19:31
Looks like

```
fin exec sudo apt-get update
fin exec sudo apt-get install ca-certificates
```

might help

**Comment by loopy3025** [comment] 2018-06-30 01:35
Ca-certs is already installed. We're using our own cert for our machines to reach out with curl. We haven't had to specify a cert for wget in the past. It has usually just used the one we imported into Windows. I'm not sure if I can use different certs for docksal and babun.

**Comment by achekulaev** [comment] 2018-06-30 02:20
In this case you probably need to copy those certs wherever they are on your windows somewhere into your project or just somewhere in the `cli` container and tell `wget` to use them from there via `ca_directory`.

E.g. if you copy them to `<your_project>.docksal/etc/openssl` then in `cli` you would need to create `wgetrc` with `ca_directory=/var/www/.docksal/etc/openssl`, and that should do the job I guess.

**Comment by justinlevi** [comment] 2018-07-02 12:58
This approach seems to have solved the problem with being able to run drush from within the container. 

I first copied the custom cert `ca-bundle.crt` into my home directory, then ran the following commands from within the project directory.
```
mkdir -p .docksal/etc/openssl && cp ~/ca-bundle.cr .docksal/etc/openssl
fin exec -T "echo 'ca_directory=/var/www/.docksal/etc/openssl' >~/.wgetrc"
```

I then ssh'd into the cli via `fin bash` and verified that the file was created in the correct location with the correct contents via `more ~/.wgetrc`. I could have also done something like, `fin exec -T "more ~/.wgetrc"`

After the .wgetrc file is created and the cert is in the right place, I was able to run `fin exec-T drush dl pathauto`

![drush-dl](https://user-images.githubusercontent.com/1117989/42165071-7d495f38-7dd5-11e8-8cd9-aff3dc1ab09a.png)

Is there a way to run a custom bash script to do these two steps when creating the containers for a project the first time?

**Comment by achekulaev** [comment] 2018-07-02 13:14
@justinlevi great! I'm glad it helped!

And yes! Definitely there is an ability to automate it. The freedom of custom automation is the one of the main advantages of Docksal!
https://docs.docksal.io/en/master/fin/custom-commands/
Usually you would name it `.docksal/commands/init` and run it when you need to init your project from scratch, where you would create your containers and run any additional commands you need to run.

**Comment by loopy3025** [comment] 2018-07-02 13:15
Nice!  We could add it to the init script.

**Comment by achekulaev** [comment] 2018-07-02 13:20
Feel free to close it if the issue is solved.

**Comment by justinlevi** [comment] 2018-07-02 13:21
@loopy3025 on it...

**Comment by loopy3025** [comment] 2018-07-10 17:57
Hey @achekulaev We've been plugging away at this for a few days now and we think we've got it working.

@justinlevi please correct me if I give any wrong info.

Private Root Certificate
---
The users need to get their organization's private root certificate

a. Open up your start menu.

b. Start typing "Internet Options" and select it when it pops up.

c. Go to the Content tab --> click on Certificates.

d. Go to Trusted Root Certificate Authorities tab.

e. Select the certificate with Issued To/Issued by your organization.

f. Click button to Export.

g. Leave format option as the default selection.

h. Specify filename. Call it whatever tou want. For the purposes of this exersise, we'll call it myprivateroot.cer. Click Next, then click Finish.

i. Save the myprivateroot.cer file from the steps above, to the C:/Users/<you>/.babun/cygwin/etc/pki/ca-trust/source/anchors directory

j. Switch to babun and execute the command to update the ca-trust. This will prevent the changes from being overwritten each time the update-ca-trust extract command gets executed.
```
$ update-ca-trust
```

Docksal.env Settings
---
First of all, we still need to set the following in our docksal.env:
```
DOCKER_NATIVE=1
DOCKSAL_UUID=<DOCKSAL-AUTOMATICALLY-GENERATED-UUID>
DOCKSAL_VHOST_PROXY_PORT_HTTP=8080
DOCKSAL_VHOST_PROXY_PORT_HTTPS=8443
DOCKSAL_DNS_UPSTREAM=##.###.###.##
```
Individual users should get the DNS Upstream from their administrator.

Then we run
```
fin system reset
```

Initial Project Setup
---
@justinlevi created a custom init script for this part, but the part that is quite different from the usual scripts is the following:
```
# setup .wgetrc to use the custom cert
mkdir -p .docksal/etc/openssl && cp /etc/pki/ca-trust/source/anchors/myprivateroot.cer .docksal/etc/openssl/
fin exec -T "echo 'ca_directory=/var/www/.docksal/etc/openssl' >~/.wgetrc"
```
This imports the custom cert into the docker cli container and sets up the .wgetrc which should enable drush to work

If that Doesn't Work
---
The latter worked for some of us. Others had to go a bit further.

```
fin bash
#switch to root user
sudo su 
#cd to directory with saved root cert
cd /var/www/.docksal/etc/openssl/
#convert certificate format
openssl x509 -inform der -in itsprivateroot.cer -out itsprivateroot.pem 
#append to docksal cert file (if required chmod 744 ca-certificates.crt) - we had to do this
cat itsprivateroot.pem >> /etc/ssl/certs/ca-certificates.crt
```

**Comment by achekulaev** [comment] 2018-07-10 20:41
@lmakarov we might want to add a feature when `cli` would look for certificates in `.docksal/etc/ssl/certs`, convert `.cer` to `.pem` and copy them to `/etc/ssl/certs`.

**Comment by lmakarov** [comment] 2018-07-11 00:17
I'm actually puzzled with how much hassle you have to go through to access internet, @loopy3025 :D  
We could have a built-in support for setups like this in `cli`, but... it's looks very edge-casy to me.

Reminds me about the other edge case we had a while ago - #287, which we also have not implemented or documented for the very same reason.

Blog post, maybe?

**Comment by shelane** [comment] 2018-07-11 00:39
@lmakarov I think their situation is similar to mine that I posted in #518. Instead of installing the certs, our current workaround is firewall exceptions. That works for Drush, github, and Acquia cloud because they are our known requirements. It doesn’t work when we start working on another solution that requires SSL access to a site that is not predefined for our firewall. Then we end up with self-signed cert errors as our network attempts SSL inspection without the root cert installed.

**Comment by lmakarov** [comment] 2018-10-31 22:41
@loopy3025 , @shelane is this something you guys can contribute as a PR to the Docksal docs AND/OR a blog post on blog.docksal.io?
Describe the specifics of the network environment that you have (as much as you can/are allowed to) and how to solve the problem that you are having.

**Comment by loopy3025** [comment] 2018-11-01 01:06
@lmakarov  Yes. I'd be happy to write something up. We're still kind of working on our documentation, but I think we are ready to write something coherent. 

@justinlevi and the rest of our team have actually been working on a bunch of exciting things lately that might be worth a couple of articles, including Robo tasks and whatnot.

**Comment by achekulaev** [comment] 2018-11-16 18:04
@loopy3025 ready when you are!

**Comment by lmakarov** [comment] 2019-01-04 22:42
Closing, as there are no further actions in the context of this project.

**Closed by lmakarov** 2019-01-04 22:42 UTC
Labels: 🏷documentation, 🏷new feature
