### ISSUE TITLE
Bug activating docksal machine in ZSH?

### ISSUE THREAD

**Issue by lpeabody** [docksal/docksal#271] opened 2017-06-22 15:53 UTC
**Description**

When you've previously activated docksal machine, and then open a new terminal window in ZSH, and run `fin vm ls`, the machine is not activated.

**Steps to reproduce the issue:**

1. In ZSH, activate docksal machine in one tab.
2. Open another tab.
3. Run `fin vm ls`.
4. Note that docksal machine is not marked as active.

**Describe the results you received:**

When running fin commands that interact with a container, get an error saying docker socket can't be connected to.

**Describe the results you expected:**

Expected to be able to run interactive container commands via fin (drush, db, etc...).

**Comment by lmakarov** [comment] 2017-06-22 16:14
I'm not able to reproduce this bug. I'm using https://github.com/sorin-ionescu/prezto myself. It's an extension on top of ZSH.

There must be something special about your ZSH setup.

Feel free to post the solution/root cause explanation here when you figure it out. I'm going to close the issue, since it's not Docksal related.

**Closed by lmakarov** 2017-06-22 16:14 UTC

**Comment by achekulaev** [comment] 2017-06-22 18:46
Not sure what "activate" means. Making docker machine active? `docker-machine active ...`? If that is so, then it might be possible that active will be different but Docksal Fin in general does not care which machine is active in terms of docker-machine configuration as it always uses `docksal` one.
