### ISSUE TITLE
cURL cannot resolve host after Docker update 

### ISSUE THREAD

**Issue by hamletta** [docksal/docksal#1836] opened 2024-10-10 22:42 UTC
**Description**

I updated my Docker to 4.34, and now I can't run composer update, because curl can't resolve the hosts.

**Describe the results you received:**

When I run `composer diag`, I get:
```
Checking https connectivity to packagist: FAIL
The following exception probably indicates you have misconfigured DNS resolver(s)
[Composer\Downloader\TransportException] curl error 6 while downloading https://repo.packagist.org/packages.json: Could not resolve host: repo.packagist.org

```

**Describe the results you expected:**

I expect it to download my packages.

**Output of `fin config`:**

<details>
  <summary>fin config output</summary>

```
COMPOSE_FILE:
/Users/rebeccaluxford/.docksal/stacks/volumes-bind.yml
/Users/rebeccaluxford/.docksal/stacks/stack-default.yml
/Users/rebeccaluxford/Projects/drupal_elms/.docksal/docksal.yml
/Users/rebeccaluxford/.docksal/stacks/overrides-dd-bind.yml
ENV_FILE:
/Users/rebeccaluxford/Projects/drupal_elms/.docksal/docksal.env
/Users/rebeccaluxford/Projects/drupal_elms/.docksal/docksal-local.env

PROJECT_ROOT: /Users/rebeccaluxford/Projects/drupal_elms
DOCROOT: web
VIRTUAL_HOST: my-site.docksal.site
VIRTUAL_HOST_ALIASES: *.my-site.docksal.site
IP: 192.168.64.100

MySQL endpoint: 192.168.64.100:32774
Public URL:

Docker Compose configuration
---------------------
name: drupal_elms
services:
  cli:
    dns:
      - 8.8.8.8
      - 9.9.9.9
    environment:
      CLI_IMAGE: docksal/cli:php8.1-3
      COMPOSER_ALLOW_XDEBUG: "0"
      COMPOSER_DISABLE_XDEBUG_WARN: "0"
      CRON_my-site: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
      DB_IMAGE: docksal/mysql:5.7
      DOCKSAL_STACK: default
      DOCROOT: web
      DRUSH_ALLOW_XDEBUG: "0"
      DRUSH_OPTIONS_URI: my-site.docksal.site
      HOST_GID: "20"
      HOST_UID: "501"
      K8S_NAMESPACE: local
      MYSQL_DATABASE: default
      MYSQL_HOST: db
      MYSQL_PASSWORD: user
      MYSQL_PORT_MAPPING: 32774:3306
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
      REDIS_HOST: redis
      REDIS_KEY: redis
      REDIS_PORT: "6379"
      SALT_my-site: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
      SSH_AUTH_SOCK: /.ssh-agent/proxy-socket
      VIRTUAL_HOST: my-site.docksal.site
      VIRTUAL_HOST_CERT_NAME: ZscalerRootCertificate-2048-SHA256
      XDEBUG_CONFIG: client_host=192.168.64.1
      XDEBUG_ENABLED: "0"
      XDEBUG_MODE: debug
    hostname: cli
    healthcheck:
      interval: 10s
    image: docksal/cli:php8.1-3
    labels:
      io.docksal.shell: bash
      io.docksal.user: docker
    logging:
      options:
        max-file: "10"
        max-size: 1m
    networks:
      default: null
    volumes:
      - type: volume
        source: project_root
        target: /var/www
        volume:
          nocopy: true
      - type: volume
        source: docksal_ssh_agent
        target: /.ssh-agent
        read_only: true
        volume: {}
      - type: bind
        source: /tmp/.docksal/drupal_elms
        target: /tmp/.docksal/drupal_elms
        read_only: true
        bind:
          create_host_path: true
      - type: volume
        source: cli_home
        target: /home/docker
        volume: {}
  db:
    dns:
      - 8.8.8.8
      - 9.9.9.9
    environment:
      CLI_IMAGE: docksal/cli:php8.1-3
      CRON_my-site: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
      DB_IMAGE: docksal/mysql:5.7
      DOCKSAL_STACK: default
      DOCROOT: web
      K8S_NAMESPACE: local
      MYSQL_DATABASE: default
      MYSQL_HOST: db
      MYSQL_PASSWORD: user
      MYSQL_PORT_MAPPING: 32774:3306
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
      REDIS_HOST: redis
      REDIS_KEY: redis
      REDIS_PORT: "6379"
      SALT_my-site: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
      VIRTUAL_HOST: my-site.docksal.site
      VIRTUAL_HOST_CERT_NAME: ZscalerRootCertificate-2048-SHA256
      XDEBUG_ENABLED: "0"
    hostname: db
    healthcheck:
      interval: 10s
    image: docksal/mysql:5.7
    logging:
      options:
        max-file: "10"
        max-size: 1m
    networks:
      default: null
    ports:
      - mode: ingress
        target: 3306
        published: "32774"
        protocol: tcp
    volumes:
      - type: volume
        source: project_root
        target: /var/www
        read_only: true
        volume:
          nocopy: true
      - type: volume
        source: db_data
        target: /var/lib/mysql
        volume: {}
  mail:
    dns:
      - 8.8.8.8
      - 9.9.9.9
    hostname: mail
    healthcheck:
      interval: 10s
    image: axllent/mailpit:v1.15.1
    labels:
      io.docksal.cert-name: ZscalerRootCertificate-2048-SHA256
      io.docksal.virtual-host: mail.my-site.docksal.site,mail.my-site.docksal.site.*
      io.docksal.virtual-port: "8025"
    logging:
      options:
        max-file: "10"
        max-size: 1m
    networks:
      default: null
    volumes:
      - type: volume
        source: project_root
        target: /var/www
        read_only: true
        volume:
          nocopy: true
  redis:
    command:
      - redis-server
      - --requirepass
      - redis
    hostname: redis
    image: wodby/redis:5.0
    networks:
      default: null
    ports:
      - mode: ingress
        target: 6379
        protocol: tcp
    volumes:
      - type: volume
        source: redis_data
        target: /data
        volume: {}
  web:
    depends_on:
      cli:
        condition: service_started
        required: true
    dns:
      - 8.8.8.8
      - 9.9.9.9
    environment:
      APACHE_DOCUMENTROOT: /var/www/web
      APACHE_FCGI_HOST_PORT: cli:9000
    hostname: web
    healthcheck:
      interval: 10s
    image: docksal/apache:2.4-2.5
    labels:
      io.docksal.cert-name: ZscalerRootCertificate-2048-SHA256
      io.docksal.permanent: "false"
      io.docksal.project-root: /Users/rebeccaluxford/Projects/drupal_elms
      io.docksal.virtual-host: my-site.docksal.site,*.my-site.docksal.site,my-site.docksal.site.*
    logging:
      options:
        max-file: "10"
        max-size: 1m
    networks:
      default: null
    volumes:
      - type: volume
        source: project_root
        target: /var/www
        read_only: true
        volume:
          nocopy: true
networks:
  default:
    name: drupal_elms_default
volumes:
  cli_home:
    name: drupal_elms_cli_home
  db_data:
    name: drupal_elms_db_data
  docksal_ssh_agent:
    name: docksal_ssh_agent
    external: true
  project_root:
    name: drupal_elms_project_root
    driver: local
    driver_opts:
      device: /host_mnt/Users/rebeccaluxford/Projects/drupal_elms
      o: bind
      type: none
  redis_data:
    name: drupal_elms_redis_data
```

</details>

<br>

**Output of `fin sysinfo`:**

<details>
  <summary>fin sysinfo output</summary>

  ```
███  DOCKSAL
Docksal version: v1.19.0
fin version:     v1.118.0

███  OS
Darwin macOS 14.6.1
Darwin C02YJ0M2JGH7 23.6.0 Darwin Kernel Version 23.6.0: Mon Jul 29 21:13:00 PDT 2024; root:xnu-10063.141.2~1/RELEASE_X86_64 x86_64

███  ENVIRONMENT
MODE : Docker Desktop
DOCKER_HOST : 

███  NFS
DOCKSAL_NFS_PATH : /Users

nfsd service is disabled
nfsd is running (pid 5869, 8 threads)

/etc/exports:
-------------

# <ds-nfs docksal
/Users 127.0.0.1 192.168.64.1 192.168.81.0 -alldirs -maproot=0:0
# ds-nfs>
-------------

Exports list on localhost:
/Users                              127.0.0.1 192.168.64.1 192.168.81.0

All mounts on localhost:

███  DOCKER
Expected client version: 26.0.0
Expected server version: 26.0.0

Installed versions:

Client:
 Version:           26.0.0
 API version:       1.45
 Go version:        go1.21.8
 Git commit:        2ae903e
 Built:             Wed Mar 20 15:14:46 2024
 OS/Arch:           darwin/amd64
 Context:           desktop-linux

Server: Docker Desktop 4.34.3 (170107)
 Engine:
  Version:          27.2.0
  API version:      1.47 (minimum version 1.24)
  Go version:       go1.21.13
  Git commit:       3ab5c7d
  Built:            Tue Aug 27 14:15:15 2024
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.7.20
  GitCommit:        8fc6bcff51318944179630522a095cc9dbf9f353
 runc:
  Version:          1.1.13
  GitCommit:        v1.1.13-0-g58aa920
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0

███  DOCKER COMPOSE
Expected version:  2.26.1
Installed version: 2.26.1

███  DOCKSAL: PROJECTS
project       STATUS                      virtual host                                                                                       project root
drupal_elms   Up 25 minutes (healthy)     my-site.docksal.site,*.my-site.docksal.site,my-site.docksal.site.*                              /Users/rebeccaluxford/Projects/drupal_elms
dol_d8        Exited (0) 31 hours ago     local-ilab-d8.dol.docksal.site,*.local-ilab-d8.dol.docksal.site,local-ilab-d8.dol.docksal.site.*   /Users/rebeccaluxford/Projects/dol_d8
opig-d10      Exited (0) 53 minutes ago   opig-d10.docksal.site,*.opig-d10.docksal.site,opig-d10.docksal.site.*                              /Users/rebeccaluxford/Projects/opig-d10
volume        Exited (0) 2 weeks ago      volume.docksal.site,*.volume.docksal.site,volume.docksal.site.*                                    /Users/rebeccaluxford/Projects/volume
projects      Exited (0) 3 weeks ago      projects.docksal.site,*.projects.docksal.site,projects.docksal.site.*                              /Users/rebeccaluxford/Projects
pirate        Exited (0) 3 weeks ago      pirate.docksal.site,*.pirate.docksal.site,pirate.docksal.site.*                                    /Users/rebeccaluxford/Projects/pirate
drupal        Exited (0) 12 months ago    drupal.docksal.site,*.drupal.docksal.site,drupal.docksal.site.*                                    /Users/rebeccaluxford/Projects/react-and-drupal-examples-hello-world/drupal

███  DOCKSAL: VIRTUAL HOSTS
*.my-site.docksal.site
mail.my-site.docksal.site.*
mail.my-site.docksal.site
my-site.docksal.site.*
my-site.docksal.site

███  DOCKSAL: NETWORKING

DOCKSAL_IP: 192.168.64.100
DOCKSAL_HOST_IP: 192.168.64.1
DOCKSAL_VHOST_PROXY_IP: 0.0.0.0
DOCKSAL_DNS_IP: 0.0.0.0
DOCKSAL_DNS_DISABLED: 1
DOCKSAL_NO_DNS_RESOLVER: 1
DOCKSAL_DNS_UPSTREAM: 8.8.8.8
DOCKSAL_DNS_DOMAIN: docksal.site

███  DOCKSAL: CONNECTIVITY

Host to 192.168.64.100: 	PASS
Container to 192.168.64.100: 	PASS
Container to 192.168.64.1: 	PASS

Checking connectivity to http://dns-test.docksal.site...
Host: PASS
Containers: FAIL

███  DOCKER: RUNNING CONTAINERS
CONTAINER ID   IMAGE                     COMMAND                  CREATED          STATUS                    PORTS                                      NAMES
a097dd7867ec   docksal/ssh-agent:1.4     "docker-entrypoint.s…"   26 minutes ago   Up 26 minutes (healthy)                                              docksal-ssh-agent
2ce7776b6fb9   docksal/vhost-proxy:1.8   "docker-entrypoint.s…"   26 minutes ago   Up 26 minutes (healthy)   0.0.0.0:80->80/tcp, 0.0.0.0:443->443/tcp   docksal-vhost-proxy
fb81a709744c   docksal/cli:php8.1-3      "/opt/startup.sh sup…"   6 hours ago      Up 25 minutes (healthy)   22/tcp, 3000/tcp, 9000/tcp                 drupal_elms_cli_1
a83f9b8560fe   docksal/apache:2.4-2.5    "httpd-foreground"       2 days ago       Up 25 minutes (healthy)   80/tcp, 443/tcp                            drupal_elms_web_1
015f7b93fcbe   docksal/mysql:5.7         "docker-entrypoint.s…"   2 days ago       Up 25 minutes (healthy)   33060/tcp, 0.0.0.0:32774->3306/tcp         drupal_elms_db_1
47d9eaa52a5d   axllent/mailpit:v1.15.1   "/mailpit"               4 months ago     Up 25 minutes (healthy)   1025/tcp, 1110/tcp, 8025/tcp               drupal_elms_mail_1
14bfe2c745e1   wodby/redis:5.0           "/docker-entrypoint.…"   12 months ago    Up 25 minutes             0.0.0.0:53644->6379/tcp                    drupal_elms_redis_1

███  DOCKER: NETWORKS
NETWORK ID     NAME                             DRIVER    SCOPE
89a0e7ba4fe2   _default                         bridge    local
cf628a46c011   bridge                           bridge    local
b02229cbcd3c   ddev-react-tutorials-2_default   bridge    local
65127412eb0c   ddev_default                     bridge    local
bbdc22402738   dol_d8_default                   bridge    local
54dbdb6a4596   drupal_default                   bridge    local
4d22a24a16c2   drupal_elms_default              bridge    local
263a27875e38   examples_mod_default             bridge    local
6ce0649ef11c   host                             host      local
bcaca47a8298   none                             null      local
b4e50a1c0ed9   opig-d10_default                 bridge    local
2b531a67a399   type_default                     bridge    local
be751c9b4a64   volume_default                   bridge    local

███  DOCKER DESKTOP
EXPECTED VERSION: 4.29.0
DETECTED VERSION: 4.34.3

███  HDD Usage
Filesystem        Size    Used   Avail Capacity iused ifree %iused  Mounted on
/dev/disk1s5s1   466Gi   9.6Gi    77Gi    11%    404k  811M    0%   /
devfs            190Ki   190Ki     0Bi   100%     656     0  100%   /dev
/dev/disk1s2     466Gi   2.2Gi    77Gi     3%    4.5k  811M    0%   /System/Volumes/Preboot
/dev/disk1s4     466Gi   3.0Gi    77Gi     4%       3  811M    0%   /System/Volumes/VM
/dev/disk1s6     466Gi   3.0Mi    77Gi     1%      22  811M    0%   /System/Volumes/Update
/dev/disk1s1     466Gi   372Gi    77Gi    83%    2.5M  811M    0%   /System/Volumes/Data
map auto_home      0Bi     0Bi     0Bi   100%       0     0     -   /System/Volumes/Data/home
  ```

</details>

Thanks, y'all!

**Comment by lmakarov** [comment] 2024-10-11 13:12
I was not able to reproduce this with the most recent Docker Desktop 4.34.3 (170107) on macOS (both arm64 and x86_64).

Try:
- `fin system reset`
- Restart Docker Desktop
- Restart computer

Is your Docker Desktop running in the "Virtualization framework" mode?

<img width="926" alt="Screenshot 2024-10-11 at 15 10 51" src="https://github.com/user-attachments/assets/7c3570f6-b891-46ec-81b4-b4bf52d8cba7">

**Comment by hamletta** [comment] 2024-10-11 13:35
> Is your Docker Desktop running in the "Virtualization framework" mode?

Yes.

Also, there is a problem with Port 53 blocked:
```
Resetting Docksal system services...
 * proxy
 * dns
   upstream 8.8.8.8
docker: Error response from daemon: Ports are not available: exposing port UDP 0.0.0.0:53 -> 0.0.0.0:0: listen udp 0.0.0.0:53: bind: address already in use.
 ERROR:  Failed starting the DNS service.

```
Earlier, I checked out what was running there:
```
% netstat -vanp udp | awk '$4 ~ /\.53$/' | awk '{print $8}' | xargs ps -p
  PID TTY           TIME CMD
  347 ??         1:20.28 /usr/sbin/mDNSResponder

```
I don't know if the additional details are useful, because this is all way above my pay grade! But thanks for answering.

**Comment by lmakarov** [comment] 2024-10-11 13:58
In your original post you had the DNS resolver disabled (`DOCKSAL_DNS_DISABLED: 1` in `fin sysinfo` output).
I assume you re-enabled it at some point and that's the reason for the "Failed starting the DNS service." error.

Better keep it disabled. See https://docs.docksal.io/stack/configuration-variables/#docksal-dns-disabled

Please post the output from these commands:

```
nslookup github.com
fin run-cli --clean nslookup github.com
```

**Comment by hamletta** [comment] 2024-10-11 14:06
OK, I re-disabled the DNS resolver and ran your commands:

```
nslookup github.com                    
Server:		10.8.8.8
Address:	10.8.8.8#53

Non-authoritative answer:
Name:	github.com
Address: 140.82.114.3

fin run-cli --clean nslookup github.com
;; communications error to 8.8.8.8#53: timed out
;; communications error to 8.8.8.8#53: timed out
;; communications error to 8.8.8.8#53: timed out
;; communications error to 9.9.9.9#53: timed out
;; no servers could be reached

```
Oh, and as an added bonus, this is a work computer with VPN and security software out the wazoo, including the dreaded Zscaler.

**Comment by lmakarov** [comment] 2024-10-11 14:11
> Oh, and as an added bonus, this is a work computer with VPN and security software out the wazoo, including the dreaded Zscaler.

Well, there's your answer to "why" 😁 
> ;; communications error to 8.8.8.8#53: timed out
Your network does not allow using external DNS.

You will have to manually configure the local upstream DNS server.
See https://docs.docksal.io/core/system-dns/#override-the-default-upstream-dns-settings

In this case it will be this:

```
fin config set --global DOCKSAL_DNS_UPSTREAM=10.8.8.8
```

Then test again with `fin run-cli --clean nslookup github.com`

**Comment by lmakarov** [comment] 2024-10-11 14:12
Moving this to Discussions.

**Closed as completed** 2024-10-11 14:12 UTC
Labels: investigation
