### ISSUE TITLE
project_root showing different paths in docker and docksal. Unable to restart project without removing volumes.

### ISSUE THREAD

**Issue by gconry18** [docksal/docksal#1368] opened 2020-06-29 21:40 UTC
**Description**

When starting up a "new" project (after running `fin project remove`) the docker volume created for the project_root and the docksal project config show different paths. This leads to an issue when restarting the project that there is a volume of the same name with a different "device" driver_opt.

docksal config path: `/c/Users/gconry/DocksalSites/relatedacsf`
docker volume path: `/host_mnt/c/Users/gconry/DocksalSites/relatedacsf`

This is using WSL Ubuntu 18.04. 
I've never had this issue before and have other projects that are working correctly (although I dare not reset them). Their docker container path match the docksal config path.

Something to note:
My project that works has `"com.docker.compose.version": "1.23.2"`
The one that is having the issue is `"com.docker.compose.version": "1.24.1"`

**Steps to reproduce the issue:**

1. `fin up` to start project
2. `fin stop` to stop it
3. `fin up` to restart issue
4. error message thrown

**Describe the results you received:**

Error Message:
ERROR: Configuration for volume project_root specifies "device" driver_opt /c/Users/gconry/DocksalSites/relatedacsf, but a volume with the same name uses a different "device" driver_opt (/host_mnt/c/Users/gconry/DocksalSites/relatedacsf). If you wish to use the new configuration, please remove the existing volume "relatedacsf_project_root" first:
$ docker volume rm relatedacsf_project_root

**Describe the results you expected:**

Docker volume should have the same path (or not conflict)

**Output of `fin config`:**

<details>
  <summary>fin config output</summary>

```
Docker Compose configuration
---------------------
services:
  cli:
    dns:
    - 192.168.64.100
    - 8.8.8.8
    environment:
      BLACKFIRE_CLIENT_ID: null
      BLACKFIRE_CLIENT_TOKEN: null
      COMPOSER_ALLOW_XDEBUG: '1'
      COMPOSER_DISABLE_XDEBUG_WARN: '1'
      DOCROOT: docroot
      DRUSH_ALLOW_XDEBUG: '1'
      DRUSH_OPTIONS_URI: relatedacsf.docksal.site
      GIT_USER_EMAIL: ''
      GIT_USER_NAME: ''
      HOST_GID: '1000'
      HOST_UID: '1000'
      MYSQL_DATABASE: default
      MYSQL_HOST: db
      MYSQL_PASSWORD: user
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
      PHP_IDE_CONFIG: null
      SECRET_ACAPI_EMAIL: null
      SECRET_ACAPI_KEY: null
      SECRET_PLATFORMSH_CLI_TOKEN: null
      SECRET_SSH_PRIVATE_KEY: null
      SECRET_TERMINUS_TOKEN: null
      SSH_AUTH_SOCK: /.ssh-agent/proxy-socket
      VIRTUAL_HOST: relatedacsf.docksal.site
      XDEBUG_CONFIG: remote_connect_back=0 remote_host=192.168.64.1
      XDEBUG_ENABLED: '1'
    hostname: cli
    image: docksal/cli:php7.2
    labels:
      io.docksal.shell: bash
      io.docksal.user: docker
    volumes:
    - docksal_ssh_agent:/.ssh-agent:ro
    - cli_home:/home/docker:rw
    - project_root:/var/www:rw,nocopy,cached
  db:
    dns:
    - 192.168.64.100
    - 8.8.8.8
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: null
      MYSQL_DATABASE: default
      MYSQL_INITDB_SKIP_TZINFO: null
      MYSQL_ONETIME_PASSWORD: null
      MYSQL_PASSWORD: user
      MYSQL_RANDOM_ROOT_PASSWORD: null
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
    hostname: db
    image: docksal/mysql:5.6-1.4
    ports:
    - 0:3306/tcp
    volumes:
    - db_data:/var/lib/mysql:rw
    - project_root:/var/www:ro,nocopy,cached
  web:
    depends_on:
      cli:
        condition: service_started
    dns:
    - 192.168.64.100
    - 8.8.8.8
    environment:
      APACHE_BASIC_AUTH_PASS: null
      APACHE_BASIC_AUTH_USER: null
      APACHE_DOCUMENTROOT: /var/www/docroot
      APACHE_FCGI_HOST_PORT: cli:9000
    hostname: web
    image: docksal/apache:2.4
    labels:
      io.docksal.cert-name: none
      io.docksal.permanent: "false"
      io.docksal.project-root: /c/Users/gconry/DocksalSites/relatedacsf
      io.docksal.virtual-host: relatedacsf.docksal.site,*.relatedacsf.docksal.site,relatedacsf.docksal.site.*
    volumes:
    - project_root:/var/www:ro,nocopy,cached
version: '2.1'
volumes:
  cli_home: {}
  db_data: {}
  docksal_ssh_agent:
    external: true
    name: docksal_ssh_agent
  project_root:
    driver: local
    driver_opts:
      device: /c/Users/gconry/DocksalSites/relatedacsf
      o: bind
      type: none

---------------------
```

</details>

<br>

**Output of `docker volume inspect`:**

<details>
  <summary>docker volume inspect output</summary>

  ```
[
    {
        "CreatedAt": "2018-12-11T14:57:16Z",
        "Driver": "local",
        "Labels": {
            "com.docker.compose.project": "relatedacsf",
            "com.docker.compose.version": "1.24.1",
            "com.docker.compose.volume": "project_root"
        },
        "Mountpoint": "/var/lib/docker/volumes/relatedacsf_project_root/_data",
        "Name": "relatedacsf_project_root",
        "Options": {
            "device": "/host_mnt/c/Users/gconry/DocksalSites/relatedacsf",
            "o": "bind",
            "type": "none"
        },
        "Scope": "local"
    }
]
  ```

</details>

**Output of `fin sysinfo`:**

<details>
  <summary>fin sysinfo output</summary>

  ```
███  OS
WSL Ubuntu 18.04
Linux ZA-NB003 4.4.0-17763-Microsoft #864-Microsoft Thu Nov 07 15:22:00 PST 2019 x86_64 x86_64 x86_64 GNU/Linux

███  ENVIRONMENT
MODE : Docker Desktop

███  FIN
fin version: 1.95.0

███  DOCKER COMPOSE
EXPECTED VERSION: 1.24.1
docker-compose version 1.24.1, build 4667896b
docker-py version: 3.7.3
CPython version: 3.6.8
OpenSSL version: OpenSSL 1.1.0j  20 Nov 2018

███  DOCKER
EXPECTED VERSION: 19.03.4

Client: Docker Engine - Community
 Version:           19.03.4
 API version:       1.40
 Go version:        go1.12.10
 Git commit:        9013bf583a
 Built:             Fri Oct 18 15:49:05 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.8
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.17
  Git commit:       afacb8b
  Built:            Wed Mar 11 01:29:16 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.2.13
  GitCommit:        7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683

███  DOCKSAL: PROJECTS
project             STATUS                    virtual host                                                                     project root
relatedacsf         Up 20 minutes (healthy)   relatedacsf.docksal.site,*.relatedacsf.docksal.site,relatedacsf.docksal.site.*   /c/Users/gconry/DocksalSites/relatedacsf

███  DOCKSAL: VIRTUAL HOSTS
*.relatedacsf.docksal.site
relatedacsf.docksal.site.*
relatedacsf.docksal.site

███  DOCKSAL: DNS
curl: (6) Could not resolve host: dns-test.docksal
ERROR: Requesting http://dns-test.docksal failed!

███  DOCKER: RUNNING CONTAINERS
CONTAINER ID        IMAGE                     COMMAND                  CREATED             STATUS                    PORTS                                      NAMES
28f05aea1a3d        docksal/apache:2.4        "httpd-foreground"       20 minutes ago      Up 20 minutes (healthy)   80/tcp, 443/tcp                            relatedacsf_web_1
66c8db8d573e        docksal/mysql:5.6-1.4     "docker-entrypoint.s…"   20 minutes ago      Up 20 minutes (healthy)   0.0.0.0:32768->3306/tcp                    relatedacsf_db_1
a7ec28aecc96        docksal/cli:php7.2        "/opt/startup.sh sup…"   20 minutes ago      Up 20 minutes (healthy)   22/tcp, 3000/tcp, 9000/tcp                 relatedacsf_cli_1
8a627d0a4e2f        docksal/ssh-agent:1.3     "docker-entrypoint.s…"   About an hour ago   Up 33 minutes (healthy)                                              docksal-ssh-agent
df683668acd8        docksal/dns:1.1           "docker-entrypoint.s…"   About an hour ago   Up 33 minutes (healthy)   0.0.0.0:53->53/udp                         docksal-dns
07ae0b1e9bc6        docksal/vhost-proxy:1.5   "docker-entrypoint.s…"   About an hour ago   Up 33 minutes (healthy)   0.0.0.0:80->80/tcp, 0.0.0.0:443->443/tcp   docksal-vhost-proxy

███  DOCKER: NETWORKS
NETWORK ID          NAME                  DRIVER              SCOPE
61da783a4523        _default              bridge              local
dc8120ae36ee        bridge                bridge              local
cde000a0bdd4        host                  host                local
44e294e9ad94        none                  null                local
96758b31a2f0        relatedacsf_default   bridge              local

███  DOCKER DESKTOP
EXPECTED VERSION: 2.0.0.3
DETECTED VERSION: 2.3.0.3

███  HDD Usage
Caption  FreeSpace    Size
C:       30313897984  252841029632
  ```

</details>

**Comment by kenrbnsn** [comment] 2020-06-30 01:26
I have seen this also. The weird thing is that if I go to the website for the project it starts up fine.

**Comment by gconry18** [comment] 2020-06-30 08:04
> I have seen this also. The weird thing is that if I go to the website for the project it starts up fine.

Thanks for the tip. Good workaround in the meantime.

**Comment by achekulaev** [comment] 2020-07-01 15:41
Docksal creates a hardlink "/mnt/c" -> "/c". This is needed historically for windows docker-compose.exe to work. Might be not needed anymore. Looks like some Docker update broke this thing that used to work for ages

**Comment by kenrbnsn** [comment] 2020-07-01 17:11
It looks like there needs to be a link from "/host_mnt/c" to "/c" also or instead of the "/mnt/c" to "/c". Is there a command we could enter to try to see if this works?

**Comment by achekulaev** [comment] 2020-07-01 17:15
@kenrbnsn sure, the original bind mount is created via

```bash
sudo mkdir -p "/$drive"
sudo mount --bind "/mnt/$drive" "/$drive"
```

where `$drive` is essentially drive letter `c`, `d`, etc.

**Comment by lmakarov** [comment] 2020-07-06 22:17
@gconry18 just a random thing to try to help diagnose the problem (should list the contents of `C:\Users`):

```
fin docker run --rm -v c:/Users/:/data alpine ls /data
```

**Comment by gconry18** [comment] 2020-07-09 09:52
Results:
```
Default
Public
gconry
```

> @gconry18 just a random thing to try to help diagnose the problem (should list the contents of `C:\Users`):
> 
> ```
> fin docker run --rm -v c:/Users/:/data alpine ls /data
> ```

**Comment by kenrbnsn** [comment] 2020-07-21 12:28
I just update fin to v1.99.0 and this is still a problem. 🙁

**Comment by achekulaev** [comment] 2020-07-21 14:05
Have you tried creating that bind mount that we discussed above? You didn't reply back then

**Comment by lmakarov** [comment] 2020-07-21 19:03
I'm able to reproduce with a fresh project in WSL (Ubuntu 18.04) + Docker Desktop v2.3.0.2

```
user@DESKTOP-BH83C3D:/c/projects/test$ fin project reset
 ALERT:  Removing containers and volumes of test
Continue? [y/n]: y
Removing containers...
Stopping test_web_1 ... done                                                                                                                   Stopping test_cli_1 ... done                                                                                                                   Stopping test_db_1  ... done                                                                                                                   Removing test_web_1 ... done                                                                                                                   Removing test_cli_1 ... done                                                                                                                   Removing test_db_1  ... done                                                                                                                   Removing network test_default
Removing volume test_cli_home
Removing volume test_project_root
Removing volume test_db_data
Volume docksal_ssh_agent is external, skipping
Starting services...
Creating network "test_default" with the default driver
Creating volume "test_cli_home" with default driver
Creating volume "test_project_root" with local driver
Creating volume "test_db_data" with default driver
Creating test_cli_1 ... done                                                                                                                   Creating test_db_1  ... done                                                                                                                   Creating test_web_1 ... done                                                                                                                   Connected vhost-proxy to "test_default" network.
Waiting for project stack to become ready...
user@DESKTOP-BH83C3D:/c/projects/test$ fin project start
Starting services...
ERROR: Configuration for volume project_root specifies "device" driver_opt /c/projects/test, but a volume with the same name uses a different "device" driver_opt (/host_mnt/c/projects/test). If you wish to use the new configuration, please remove the existing volume "test_project_root" first:
$ docker volume rm test_project_root
```

```
user@DESKTOP-BH83C3D:/c/projects/test$ fin docker inspect test_project_root
[
    {
        "CreatedAt": "2020-07-21T18:49:37Z",
        "Driver": "local",
        "Labels": {
            "com.docker.compose.project": "test",
            "com.docker.compose.version": "1.26.0",
            "com.docker.compose.volume": "project_root"
        },
        "Mountpoint": "/var/lib/docker/volumes/test_project_root/_data",
        "Name": "test_project_root",
        "Options": {
            "device": "/host_mnt/c/projects/test",
            "o": "bind",
            "type": "none"
        },
        "Scope": "local"
    }
]
```

I'll be looking into what's going on there.

**Comment by lmakarov** [comment] 2020-07-21 21:09
Downgrading docker-compose from 1.26.0 to 1.23.2 does not help.

Downgrading to Docker Desktop [2.1.0.5](https://github.com/docksal/docksal/issues/1268#issuecomment-576993644) solves the issue.
Apparently, the new file sharing implementation in Docker Desktop [2.2.0.0+](https://docs.docker.com/docker-for-windows/release-notes/#docker-desktop-community-2200) cause this issue.

**Comment by gconry18** [comment] 2020-07-21 21:31
Is this something you think could be fixed within docksal, or would keeping docker below 2.2.0.0 be the way to go going forward?

**Comment by achekulaev** [comment] 2020-07-21 23:01
I think it might be Docker - docker-compose combo https://github.com/docker/compose/issues/5563

**Comment by lmakarov** [comment] 2020-07-22 04:45
[This](https://github.com/docker/for-win/issues/6628#issuecomment-635906394)...

It's something in the way docker creates bind mount volumes.

On 2.1.0.5:

```
user@DESKTOP-BH83C3D:/c/projects/test$ fin debug "docker volume create --driver local --opt type=none --opt device=${PWD} --opt o=bind test_vol; docker inspect test_vol; docker volume rm test_vol"
test_vol
[
    {
        "CreatedAt": "2020-07-22T04:42:56Z",
        "Driver": "local",
        "Labels": {},
        "Mountpoint": "/var/lib/docker/volumes/test_vol/_data",
        "Name": "test_vol",
        "Options": {
            "device": "/c/projects/test",
            "o": "bind",
            "type": "none"
        },
        "Scope": "local"
    }
]
test_vol
```

On 2.3.0.3:

```
user@DESKTOP-BH83C3D:/c/projects/test$ fin debug "docker volume create --driver local --opt type=none --opt device=${PWD} --opt o=bind test_vol; docker inspect test_vol; docker volume rm test_vol"
test_vol
[
    {
        "CreatedAt": "2020-07-22T04:40:18Z",
        "Driver": "local",
        "Labels": {},
        "Mountpoint": "/var/lib/docker/volumes/test_vol/_data",
        "Name": "test_vol",
        "Options": {
            "device": "/host_mnt/c/projects/test",
            "o": "bind",
            "type": "none"
        },
        "Scope": "local"
    }
]
test_vol
```

I'm leaning towards just adding an override with `stacks/volumes-win-dd.yaml` like this:

```
version: "2.1"

volumes:
  cli_home:  # /home/docker volume in cli
  project_root:  # Project root volume (bind mount)
    driver: local
    driver_opts:
      type: none
      device: /mnt/${PROJECT_ROOT}
      o: bind
  db_data:  # Database data volume
  docksal_ssh_agent:  # Shared ssh-agent volume
    external: true
```

@achekulaev thoughts?

**Comment by lmakarov** [comment] 2020-07-22 04:46
> Is this something you think could be fixed within docksal, or would keeping docker below 2.2.0.0 be the way to go going forward?

@gconry18 stick with 2.1.0.5 until we figure out and release a workaround.

**Comment by gconry18** [comment] 2020-09-29 15:07
@lmakarov, Any luck with this?

**Comment by lmakarov** [comment] 2020-10-12 03:35
> Any luck with this?

@gconry18 this is still on the back-burner...

**Comment by lmakarov** [comment] 2020-10-14 18:57
FWIW I'm getting this issue on Docker Desktop for Mac v2.4.0.0 when using osxfs/bind mode (`DOCKSAL_VOLUMES=bind`).

```bash
# Applying configuration change after the project stack has been already initialized:
$ fin up
Starting services...
ERROR: Configuration for volume project_root specifies "device" driver_opt /Users/leonid/Work/Projects/test, but a volume with the same name uses a different "device" driver_opt (/host_mnt/Users/leonid/Work/Projects/test). If you wish to use the new configuration, please remove the existing volume "test_project_root" first:
$ docker volume rm test_project_root
```

Adding the following override in `docksal-local.yml` can be used as a stop-gap solution for Docker Desktop (Mac and Windows):

```yaml
volumes:
  project_root:
    driver: local
    driver_opts:
      device: /host_mnt${PROJECT_ROOT}
      o: bind
      type: none
```

I'm also going to work on a permanent fix for this.

**Closed** 2020-10-17 01:35 UTC
Labels: os/windows, 🏷bug

**Comment by emircanerkul** [comment] 2020-10-17 04:23
@lmakarov Hi,

I changed these files manuelly but i got same error as like before.

Starting services... ERROR: Configuration for volume project_root specifies "device" driver_opt /home/emircan/projects/drupal, but a volume with the same name uses a different "device" driver_opt (/run/desktop/mnt/host/wsl/docker-desktop-bind-mounts/Ubuntu/4d517cdc27e9497b47928fa410726df15793c4328c2b43a6023946018d24ee9e). If you wish to use the new configuration, please remove the existing volume "drupal_project_root" first: $ docker volume rm drupal_project_root

**Comment by lmakarov** [comment] 2020-10-19 05:58
@emircanerkul `fin sysinfo`?

**Comment by gconry18** [comment] 2020-10-20 09:07
@lmakarov is this fix public? Can I just do a `fin update`?

**Comment by emircanerkul** [comment] 2020-10-23 19:51
> @emircanerkul `fin sysinfo`?

@lmakarov 

`
███  OS
Linux Ubuntu 20.04
Linux DESK 4.19.128-microsoft-standard #1 SMP Tue Jun 23 12:58:10 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

███  ENVIRONMENT
MODE : Linux Kernel

███  FIN
fin version: 1.99.0

███  DOCKER COMPOSE
EXPECTED VERSION: 1.26.0
docker-compose version 1.26.0, build d4451659
docker-py version: 4.2.1
CPython version: 3.7.7
OpenSSL version: OpenSSL 1.1.0l  10 Sep 2019

███  DOCKER
EXPECTED CLIENT VERSION: 19.03.9
EXPECTED SERVER VERSION: 19.03.9

Client: Docker Engine - Community
 Cloud integration  0.1.18
 Version:           19.03.13
 API version:       1.40
 Go version:        go1.13.15
 Git commit:        4484c46d9d
 Built:             Wed Sep 16 17:02:36 2020
 OS/Arch:           linux/amd64
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          19.03.13
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       4484c46d9d
  Built:            Wed Sep 16 17:07:04 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.3.7
  GitCommit:        8fba4e9a7d01810a393d5d25a3621dc101981175
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683

███  DOCKSAL: PROJECTS
project             STATUS              virtual host        project root

███  DOCKSAL: VIRTUAL HOSTS
---

███  DOCKSAL: NETWORKING

DOCKSAL_IP: 192.168.64.100
DOCKSAL_VHOST_PROXY_IP: 0.0.0.0
DOCKSAL_DNS_IP:
DOCKSAL_DNS_DISABLED: 0
DOCKSAL_NO_DNS_RESOLVER: 0
DOCKSAL_DNS_UPSTREAM:
DOCKSAL_DNS_DOMAIN: docksal

Checking connectivity to http://dns-test.docksal...
Host: FAIL
Containers: FAIL

███  DOCKER: RUNNING CONTAINERS
CONTAINER ID        IMAGE                     COMMAND                  CREATED             STATUS                  PORTS                                      NAMES
47c0acc0ba82        docksal/ssh-agent:1.3     "docker-entrypoint.s…"   6 days ago          Up 26 hours (healthy)                                              docksal-ssh-agent
f01c9a810225        docksal/dns:1.1           "docker-entrypoint.s…"   6 days ago          Up 26 hours (healthy)   127.0.0.1:32768->53/udp                    docksal-dns
3145b544d4e8        docksal/vhost-proxy:1.6   "docker-entrypoint.s…"   6 days ago          Up 26 hours (healthy)   0.0.0.0:80->80/tcp, 0.0.0.0:443->443/tcp   docksal-vhost-proxy

███  DOCKER: NETWORKS
NETWORK ID          NAME                DRIVER              SCOPE
ecdf0f245b4d        _default            bridge              local
36bf07dc0b61        bridge              bridge              local
cf54c93e2d67        drupal_default      bridge              local

███  DOCKER DESKTOP
EXPECTED VERSION: 2.1.0.5
DETECTED VERSION:

███  HDD Usage
Filesystem      Size  Used Avail Use% Mounted on
/dev/sdc        251G  2.5G  236G   2% /
tmpfs           2.0G     0  2.0G   0% /mnt/wsl
/dev/sdb        251G  7.2G  232G   3% /mnt/wsl/docker-desktop-data/isocache
none            2.0G   12K  2.0G   1% /mnt/wsl/docker-desktop/shared-sockets/host-services
/dev/sda        251G  122M  239G   1% /mnt/wsl/docker-desktop/docker-desktop-proxy
/dev/loop0      285M  285M     0 100% /mnt/wsl/docker-desktop/cli-tools
tools           448G   95G  354G  22% /init
none            2.0G     0  2.0G   0% /dev
none            2.0G   12K  2.0G   1% /run
none            2.0G     0  2.0G   0% /run/lock
none            2.0G     0  2.0G   0% /run/shm
none            2.0G     0  2.0G   0% /run/user
tmpfs           2.0G     0  2.0G   0% /sys/fs/cgroup
C:\             448G   95G  354G  22% /mnt/c
D:\             300G   12G  289G   4% /mnt/d
E:\              30G  2.4G   28G   8% /mnt/e
F:\             172G   13G  159G   8% /mnt/f
G:\             632G   21G  611G   4% /mnt/g
`

**Comment by robertsinton** [comment] 2020-11-22 05:30
@lmakarov I'm experiencing this issue after upgrading to Mac OS X 11 Big Sur, latest versions of Docker docksal.

I was able to get going again on one project ("pulse" in the listing below) with a `fin project reset`, although obviously that's a bit drastic.

```
robert@Mac-mini afes % fin start
Starting services...
ERROR: Configuration for volume project_root specifies "device" driver_opt /host_mnt/Users/robert/DockerSites/afes, but a volume with the same name uses a different "device" driver_opt (/Users/robert/DockerSites/afes). If you wish to use the new configuration, please remove the existing volume "afes_project_root" first:
$ docker volume rm afes_project_root
robert@Mac-mini afes % fin sysinfo
███  OS
Darwin macOS 11.0.1
Darwin Mac-mini.local 20.1.0 Darwin Kernel Version 20.1.0: Sat Oct 31 00:07:11 PDT 2020; root:xnu-7195.50.7~2/RELEASE_X86_64 x86_64

███  ENVIRONMENT
MODE : Docker Desktop

███  FIN
fin version: 1.102.0

███  DOCKER COMPOSE
EXPECTED VERSION: 1.27.4
docker-compose version 1.27.4, build 40524192
docker-py version: 4.3.1
CPython version: 3.7.7
OpenSSL version: OpenSSL 1.1.1g  21 Apr 2020

███  DOCKER
EXPECTED CLIENT VERSION: 19.03.13
EXPECTED SERVER VERSION: 19.03.13

Client: Docker Engine - Community
 Version:           19.03.13
 API version:       1.40
 Go version:        go1.13.15
 Git commit:        4484c46d9d
 Built:             Wed Sep 16 16:58:31 2020
 OS/Arch:           darwin/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.13
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       4484c46d9d
  Built:            Wed Sep 16 17:07:04 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.3.7
  GitCommit:        8fba4e9a7d01810a393d5d25a3621dc101981175
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683

███  DOCKSAL: PROJECTS
project             STATUS                   virtual host                                    project root
pulse               Up 8 minutes (healthy)   pulse.docksal,*.pulse.docksal,pulse.docksal.*   /Users/robert/DockerSites/pulse

███  DOCKSAL: VIRTUAL HOSTS
*.pulse.docksal
mail.pulse.docksal.*
mail.pulse.docksal
pulse.docksal.*
pulse.docksal

███  DOCKSAL: NETWORKING

DOCKSAL_IP: 192.168.64.100
DOCKSAL_VHOST_PROXY_IP: 0.0.0.0
DOCKSAL_DNS_IP: 0.0.0.0
DOCKSAL_DNS_DISABLED: 0
DOCKSAL_NO_DNS_RESOLVER: 0
DOCKSAL_DNS_UPSTREAM: 
DOCKSAL_DNS_DOMAIN: docksal

Checking connectivity to http://dns-test.docksal...
Host: PASS
Containers: PASS

███  DOCKER: RUNNING CONTAINERS
CONTAINER ID        IMAGE                      COMMAND                  CREATED             STATUS                    PORTS                                      NAMES
b68ce07a4869        docksal/apache:2.4-2.3     "httpd-foreground"       11 minutes ago      Up 8 minutes (healthy)    80/tcp, 443/tcp                            pulse_web_1
855f98bb42c6        docksal/cli:2.10-php7.2    "/opt/startup.sh sup…"   11 minutes ago      Up 8 minutes (healthy)    22/tcp, 3000/tcp, 9000/tcp                 pulse_cli_1
e16e76d321b3        mailhog/mailhog            "MailHog"                11 minutes ago      Up 8 minutes              1025/tcp, 8025/tcp                         pulse_mail_1
5c43ea204b6c        docksal/db:1.3-mysql-5.7   "docker-entrypoint.s…"   11 minutes ago      Up 8 minutes (healthy)    33060/tcp, 0.0.0.0:32769->3306/tcp         pulse_db_1
315d1550adcd        wodby/redis:5.0            "/docker-entrypoint.…"   11 minutes ago      Up 8 minutes              6379/tcp                                   pulse_redis_1
24f4b16df98d        docksal/ssh-agent:1.3      "docker-entrypoint.s…"   15 minutes ago      Up 15 minutes (healthy)                                              docksal-ssh-agent
50c1758cf923        docksal/dns:1.1            "docker-entrypoint.s…"   15 minutes ago      Up 15 minutes (healthy)   0.0.0.0:53->53/udp                         docksal-dns
1eb3f29332ca        docksal/vhost-proxy:1.6    "docker-entrypoint.s…"   15 minutes ago      Up 15 minutes (healthy)   0.0.0.0:80->80/tcp, 0.0.0.0:443->443/tcp   docksal-vhost-proxy

███  DOCKER: NETWORKS
NETWORK ID          NAME                       DRIVER              SCOPE
ebf239d606e3        _default                   bridge              local
214faa4c5f3d        afes_default               bridge              local
e8dca9e19b0f        bridge                     bridge              local
bd93ef71c97b        host                       host                local
163afc7e9c09        laralve-api-todo_default   bridge              local
2f161eaec747        laravel-api-todo_default   bridge              local
6c73bd5dd126        none                       null                local
abe7c31b9919        pulse_default              bridge              local

███  DOCKER DESKTOP
EXPECTED VERSION: 2.5.0.1
DETECTED VERSION: 2.5.0.1

███  HDD Usage
Filesystem                                                    Size   Used  Avail Capacity     iused       ifree %iused  Mounted on
/dev/disk1s1s1                                               466Gi   14Gi   24Gi    38%      563932  4881888948    0%   /
devfs                                                        235Ki  235Ki    0Bi   100%         812           0  100%   /dev
/dev/disk1s5                                                 466Gi   20Ki   24Gi     1%           0  4882452880    0%   /System/Volumes/VM
/dev/disk1s3                                                 466Gi  272Mi   24Gi     2%         760  4882452120    0%   /System/Volumes/Preboot
/dev/disk1s6                                                 466Gi  548Ki   24Gi     1%          16  4882452864    0%   /System/Volumes/Update
/dev/disk1s2                                                 466Gi  427Gi   24Gi    95%     5130476  4877322404    0%   /System/Volumes/Data
map auto_home                                                  0Bi    0Bi    0Bi   100%           0           0  100%   /System/Volumes/Data/home
/dev/disk3s2                                                 1.8Ti  365Gi  1.5Ti    20%     2728326 19530359074    0%   /Volumes/Ext 2TB
drivefs                                                      466Gi  443Gi   22Gi    96% 18446744069414584636  4294967295 5856109228385582080%   /Volumes/GoogleDrive
```
