### ISSUE TITLE
MacOS Ventura upgrade causes composer autoload to hang

### ISSUE THREAD

**Issue by jimbobthecoder** [docksal/docksal#1733] opened 2022-11-18 03:21 UTC
I upgraded to Ventura about a week ago and started noticing straight away that in order to get the containers to serve pages correctly I had to remove the vendor and composer-lock.json folder and then complete a fin composer install.

For reference i am running the stock images
docksal/cli:php8.0.3.1
docksal/nginx:1.20-1.2
docksal/mysql:5.7

I am running the latest version of Docker Desktop and Docksal 1.17.0

The application i am running is laravel 8.x

I couple of days ago nothing would work again so i would delete the above again and fin composer install again but it would just hang at generating the autoload process. (After it says 'Generating Optimized autload file' nothing happens - it just hangs). Kill and restarting the cli containers gives me back control of the terminal prompt.

It would be very intermittent whether it would work or not. I tried increasing ram and swap file resources, restarting and resetting docker, downgrading docker and docksal to previous versions.

If i was able to complete the fin composer install process i could work on the system. If i then restarted the docksal containers for the project it wouldn't complete a query (from postman). I went through and debugged the call and i found the line it was getting stuck on.

in /vendor/composer/autload_real.php there is a line

require DIR . '/autoload_static.php

It doesn't get past this. I try fin composer dumpautoload and again it hangs. If i run the global composer it doesn't work either.

I get the feeling that this is a permission problem that when you restart docker or the cotainers docksal it loses some form of permission....don't know though and i tried fin composer install -vvv and fin composer dumpautoload -vvv to give me more info but again i get to the 'Generating optimized....' and nothing after.

FInally after 2 days of trying to debug this, i downgraded back to Monterey and lasted versions of docker and docksal and all seems fine and stable again

**Comment by mdyoung3** [comment] 2022-11-25 16:12
After I upgraded, I cannot run `drush` or `artisan` without it hanging eternally.

**Comment by jaybeckr** [comment] 2022-11-29 18:48
hey @mdyoung3 , hope you're doing well!

@jimbobthecoder - We bumped into this and it seemed to be related to the nfs file mount, are you using that for the file sharing? When we switched to mutagen then the sites resumed working. My theory is that something with the number of files composer is loading somehow chokes nfs and it just stalls out (totally wild guess) - loading a static file works fine, or even a simple php file is processed correctly.

**Comment by mdyoung3** [comment] 2022-11-29 19:25
Oh hey @jaybeckr Doing good? You?

I can confirm that mutagen seems to be the workaround. I set up Ddev using Colima and haven't had any hanging with `drush`, `composer` or `artisen`

**Comment by sean-e-dietrich** [comment] 2022-11-30 00:28
@mdyoung3 @jaybeckr @jimbobthecoder 

There is currently a fix for this in the `develop` branch but it hasn't made it's way out in a new release just yet but if you edit the following file it should fix the issue https://github.com/docksal/docksal/blob/develop/stacks/volumes-nfs.yml#L15

Note: you will have to destroy and rebuild the project

**Comment by jaybeckr** [comment] 2022-11-30 22:37
@sean-e-dietrich - oh nice, thanks!

@mdyoung3 - doing well! Debugging an issue and saw a profile pic I recognized :smile:

**Comment by seanmacgillivray** [comment] 2023-01-05 17:28
@sean-e-dietrich just wanted to confirm that we're seeing this issue with Ventura as well and that the fix does appear to work, thanks!

**Comment by iuscare** [comment] 2023-01-17 08:48
@sean-e-dietrich can also confirm that I ran into that issue and the fix seems to work

**Comment by spectatora** [comment] 2023-01-27 16:13
For other people who came here after tracing all the issues. 

The fix on develop works, you could download directly the docksal version from develop but don't forget 
```
fin project reset
```

**Comment by firewaller** [comment] 2023-02-01 06:02
I can confirm the above fix works. Thanks!

**Comment by adrianliegmann** [comment] 2023-02-01 10:07
It works for me too!

**Comment by nplowman** [comment] 2023-02-09 22:54
This fix worked for me as well.

**Comment by gravelpot** [comment] 2023-02-09 23:26
One more 👍 for this fix worked for me.

Any chance of a new release anytime soon? This didn't reveal itself in a very obvious way, and was a head-scratcher until I thought to come here and look for any issues related to Ventura.

**Closed** 2023-07-06 12:30 UTC
