### ISSUE TITLE
Can no longer start cli container after upgrade to 1.9.0

### ISSUE THREAD

**Issue by drubage** [docksal/docksal#233] opened 2017-05-25 04:08 UTC
When attempting to create containers on a project I get this error:

```
ERROR: for cli  Cannot create container for service cli: error while mounting vo
lume with options: type='none' device='/c/Users/drew.michael/.babun/cygwin/home/
drew.michael/projects/gzcentral' o='bind': no such file or directory
ERROR: Encountered errors while bringing up the project.
```

**Steps to reproduce the issue:**

1. Run `fin project create` and create a Drupal 7 project.
2. See the error when the containers spin up. 

**Describe the results you received:**

```
ERROR: for db  Cannot start service db: error while mounting volume '/mnt/sda1/v
ar/lib/docker/volumes/clitest_project_root/_data': error while mounting volume w
ith options: type='none' device='/c/Users/drew.michael/.babun/cygwin/home/drew.m
ichael/projects/clitest' o='bind': no such file or directory

ERROR: for cli  Cannot create container for service cli: error while mounting vo
lume with options: type='none' device='/c/Users/drew.michael/.babun/cygwin/home/
drew.michael/projects/clitest' o='bind': no such file or directory
ERROR: Encountered errors while bringing up the project.
```

**Describe the results you expected:**

A functioning Docksal environment.

**Output of `fin config`:**

<details>
  <summary>fin config output</summary>

```
 ERROR:  Cannot detect project root.
         Please make sure you have .docksal directory in the root of your projec
t.
         To setup a basic Docksal stack in the current directory run fin config
generate
```

</details>

<br>

**Output of `fin sysinfo`:**

<details>
  <summary>fin sysinfo output</summary>

  ```
███  OS & BASICS
CYGWIN_NT-6.1-WOW drfrulpt-PC 1.7.35(0.287/5/3) 2015-03-04 12:07 i686 Cygwin
 Microsoft Windows [Version 6.1.7601]
fin version: 1.9.0
Mode:  VirtualBox VM
███  INSTANCES
NAME      ACTIVE   DRIVER       STATE     URL                         SWARM   DO
CKER        ERRORS
default   -        virtualbox   Error                                         Un
known       machine does not exist
docksal   *        virtualbox   Running   tcp://192.168.64.100:2376           v1
7.04.0-ce
███  DOCKER
DOCKER_HOST:    tcp://192.168.64.100:2376

Docker: Client:
 Version:      17.04.0-ce
 API version:  1.28
 Go version:   go1.7.5
 Git commit:   4845c56
 Built:        Wed Apr  5 23:33:17 2017
 OS/Arch:      windows/amd64

Server:
 Version:      17.04.0-ce
 API version:  1.28 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   4845c56
 Built:        Wed Apr  5 18:45:47 2017
 OS/Arch:      linux/amd64
 Experimental: false
███  DOCKER COMPOSE
Docker Compose: docker-compose version 1.12.0, build ee0f34e1
docker-py version: 2.2.1
CPython version: 2.7.13
OpenSSL version: OpenSSL 1.0.2j  26 Sep 2016
███  DOCKER MACHINE
docker-machine.exe version 0.10.0, build 76ed2a6
███  DOCKER: IMAGES
REPOSITORY            TAG                 IMAGE ID            CREATED
  SIZE
memcached             latest              6c32c12d9101        2 weeks ago
  83.9MB
mailhog/mailhog       latest              669347153085        5 weeks ago
  19.1MB
docksal/cli           1.2-php5            11f47dc7d024        6 weeks ago
  845MB
docksal/vhost-proxy   1.0                 2c8a8b1e62c4        2 months ago
  164MB
docksal/dns           1.0                 20c7a535479d        4 months ago
  61.6MB
docksal/ssh-agent     1.0                 148220cc033d        4 months ago
  12.2MB
docksal/web           1.0-apache2.2       a9c03f8a5f0f        4 months ago
  188MB
docksal/db            1.0-mysql-5.7       35f1494f03b6        4 months ago
  400MB
docksal/db            1.0-mysql-5.5       9fb8c0aed5fc        4 months ago
  255MB
███  DOCKER: CONTAINERS
CONTAINER ID        IMAGE                      COMMAND                  CREATED
            STATUS              PORTS
         NAMES
74f3b80479f2        docksal/db:1.0-mysql-5.7   "/entrypoint.sh my..."   7 minute
s ago       Up 7 minutes        0.0.0.0:32769->3306/tcp
         nationalhousing_db_1
a11ce302b368        mailhog/mailhog            "MailHog"                7 minute
s ago       Up 7 minutes        80/tcp, 1025/tcp, 8025/tcp
         nationalhousing_mail_1
d1d727fb6eb5        memcached                  "docker-entrypoint..."   7 minute
s ago       Up 7 minutes        11211/tcp
         nationalhousing_memcached_1
04a8611b6bf3        docksal/db:1.0-mysql-5.7   "/entrypoint.sh my..."   9 minute
s ago       Up 9 minutes        0.0.0.0:32768->3306/tcp
         gzcentral_db_1
e48590bf5102        mailhog/mailhog            "MailHog"                9 minute
s ago       Up 9 minutes        80/tcp, 1025/tcp, 8025/tcp
         gzcentral_mail_1
b3fc0e9e6cfa        memcached                  "docker-entrypoint..."   9 minute
s ago       Up 9 minutes        11211/tcp
         gzcentral_memcached_1
f9bbd4e20cee        docksal/ssh-agent:1.0      "/run.sh ssh-agent"      28 minut
es ago      Up 28 minutes
         docksal-ssh-agent
7baf7cf50807        docksal/dns:1.0            "/opt/entrypoint.s..."   28 minut
es ago      Up 28 minutes       192.168.64.100:53->53/udp
         docksal-dns
b325362fa8a6        docksal/vhost-proxy:1.0    "/usr/local/bin/st..."   28 minut
es ago      Up 28 minutes       192.168.64.100:80->80/tcp, 192.168.64.100:443->4
43/tcp   docksal-vhost-proxy
███  VIRTUALBOX
5.1.22r115126
███  NETWORK INTERFACES
Name:            VirtualBox Host-Only Ethernet Adapter #3
GUID:            e6454998-e50d-4b68-bd21-c418e0bf868b
DHCP:            Disabled
IPAddress:       192.168.64.1
NetworkMask:     255.255.255.0
IPV6Address:     fe80:0000:0000:0000:1cdb:3c42:9663:6075
IPV6NetworkMaskPrefixLength: 64
HardwareAddress: 0a:00:27:00:00:37
MediumType:      Ethernet
Status:          Up
VBoxNetworkName: HostInterfaceNetworking-VirtualBox Host-Only Ethernet Adapter #
3

Name:            VirtualBox Host-Only Ethernet Adapter #5
GUID:            04a45e75-8f4f-43d5-b64a-39cfefe14441
DHCP:            Enabled
IPAddress:       169.254.77.44
NetworkMask:     255.255.0.0
IPV6Address:     fe80:0000:0000:0000:c90e:e29e:6baa:4d2c
IPV6NetworkMaskPrefixLength: 64
HardwareAddress: 0a:00:27:00:00:33
MediumType:      Ethernet
Status:          Up
VBoxNetworkName: HostInterfaceNetworking-VirtualBox Host-Only Ethernet Adapter #
5

Name:            VirtualBox Host-Only Ethernet Adapter #4
GUID:            055ec56b-bdd7-4a00-95d2-1d2e3e751213
DHCP:            Enabled
IPAddress:       169.254.13.97
NetworkMask:     255.255.0.0
IPV6Address:     fe80:0000:0000:0000:f939:c842:e9bf:0d61
IPV6NetworkMaskPrefixLength: 64
HardwareAddress: 0a:00:27:00:00:31
MediumType:      Ethernet
Status:          Up
VBoxNetworkName: HostInterfaceNetworking-VirtualBox Host-Only Ethernet Adapter #
4

Name:            VirtualBox Host-Only Ethernet Adapter #2
GUID:            a57ef571-f08d-40fe-9967-a9ed529a803b
DHCP:            Disabled
IPAddress:       192.168.88.1
NetworkMask:     255.255.255.0
IPV6Address:     fe80:0000:0000:0000:6cd6:90a4:3165:db81
IPV6NetworkMaskPrefixLength: 64
HardwareAddress: 0a:00:27:00:00:1b
MediumType:      Ethernet
Status:          Up
VBoxNetworkName: HostInterfaceNetworking-VirtualBox Host-Only Ethernet Adapter #
2

Name:            VirtualBox Host-Only Ethernet Adapter
GUID:            58be5bf6-a111-43be-9723-1da59beb5683
DHCP:            Disabled
IPAddress:       192.168.56.1
NetworkMask:     255.255.255.0
IPV6Address:     fe80:0000:0000:0000:6c34:cc99:0894:a7c0
IPV6NetworkMaskPrefixLength: 64
HardwareAddress: 0a:00:27:00:00:10
MediumType:      Ethernet
Status:          Up
VBoxNetworkName: HostInterfaceNetworking-VirtualBox Host-Only Ethernet Adapter

███  MOUNTS
tmpfs on / type tmpfs (rw,relatime,size=917692k)
proc on /proc type proc (rw,relatime)
sysfs on /sys type sysfs (rw,relatime)
devpts on /dev/pts type devpts (rw,relatime,mode=600,ptmxmode=000)
tmpfs on /dev/shm type tmpfs (rw,relatime)
fusectl on /sys/fs/fuse/connections type fusectl (rw,relatime)
/dev/sda1 on /mnt/sda1 type ext4 (rw,relatime,data=ordered)
cgroup on /sys/fs/cgroup type tmpfs (rw,relatime,mode=755)
cgroup on /sys/fs/cgroup/cpuset type cgroup (rw,relatime,cpuset)
cgroup on /sys/fs/cgroup/cpu type cgroup (rw,relatime,cpu)
cgroup on /sys/fs/cgroup/cpuacct type cgroup (rw,relatime,cpuacct)
cgroup on /sys/fs/cgroup/blkio type cgroup (rw,relatime,blkio)
cgroup on /sys/fs/cgroup/memory type cgroup (rw,relatime,memory)
cgroup on /sys/fs/cgroup/devices type cgroup (rw,relatime,devices)
cgroup on /sys/fs/cgroup/freezer type cgroup (rw,relatime,freezer)
cgroup on /sys/fs/cgroup/net_cls type cgroup (rw,relatime,net_cls)
cgroup on /sys/fs/cgroup/perf_event type cgroup (rw,relatime,perf_event)
cgroup on /sys/fs/cgroup/net_prio type cgroup (rw,relatime,net_prio)
cgroup on /sys/fs/cgroup/hugetlb type cgroup (rw,relatime,hugetlb)
cgroup on /sys/fs/cgroup/pids type cgroup (rw,relatime,pids)
/dev/sda1 on /mnt/sda1/var/lib/docker/aufs type ext4 (rw,relatime,data=ordered)
none on /mnt/sda1/var/lib/docker/aufs/mnt/922345e093082a416ca2db3b53870b591bcc41
18b206675b0de27ffa1f6aabd2 type aufs (rw,relatime,si=480afc1b1bd028de,dio,dirper
m1)
shm on /mnt/sda1/var/lib/docker/containers/b325362fa8a62544d3dec2df87764d77ef99d
33a019b6941da7d36730d6ef131/shm type tmpfs (rw,nosuid,nodev,noexec,relatime,size
=65536k)
nsfs on /var/run/docker/netns/4b3cd955fbc7 type nsfs (rw)
none on /mnt/sda1/var/lib/docker/aufs/mnt/8507e3a1b11ba99260d04760d370591a3ea8ea
27ccc3e6e6fd9f94a43a58ba37 type aufs (rw,relatime,si=480afc1b00f828de,dio,dirper
m1)
shm on /mnt/sda1/var/lib/docker/containers/7baf7cf50807ba2e128bbcc5e3e1553a11d87
050eb41ef54918ac3e5ab5ac35d/shm type tmpfs (rw,nosuid,nodev,noexec,relatime,size
=65536k)
nsfs on /var/run/docker/netns/88a30cd6354c type nsfs (rw)
none on /mnt/sda1/var/lib/docker/aufs/mnt/7b8b7944ed4891c7dbf18807b116c1fbbc4256
95e09a23907f7e18923e3a96ba type aufs (rw,relatime,si=480afc1b000f28de,dio,dirper
m1)
shm on /mnt/sda1/var/lib/docker/containers/f9bbd4e20cee5e403edd8c20545bf14af15e8
f0e6547f733f37f1185e6b92309/shm type tmpfs (rw,nosuid,nodev,noexec,relatime,size
=65536k)
nsfs on /var/run/docker/netns/fb611dc8def6 type nsfs (rw)
none on /mnt/sda1/var/lib/docker/aufs/mnt/b72c1154daba33acce1ad3a63c544ee519dde7
6541fd1cbce54a2b84b78c8f2e type aufs (rw,relatime,si=480afc1b00aa28de,dio,dirper
m1)
none on /mnt/sda1/var/lib/docker/aufs/mnt/c78db37a6a68a7db63ef0155156c32cc2722c8
04e9453350e6bb745485791c42 type aufs (rw,relatime,si=480afc1b1be498de,dio,dirper
m1)
shm on /mnt/sda1/var/lib/docker/containers/b3fc0e9e6cfaad3e0db1b008856b834513cdf
b1fa9da6606f93709362c6c7f2d/shm type tmpfs (rw,nosuid,nodev,noexec,relatime,size
=65536k)
nsfs on /var/run/docker/netns/4036ca0ec206 type nsfs (rw)
shm on /mnt/sda1/var/lib/docker/containers/e48590bf51029718a4bea15a4b977e6ed2c3d
9acad990312741ec1b0bfb39d75/shm type tmpfs (rw,nosuid,nodev,noexec,relatime,size
=65536k)
none on /mnt/sda1/var/lib/docker/aufs/mnt/993a09daa0fc20327fd26ad5e0caea236609f1
85930753f47e8fe40c4487cc0b type aufs (rw,relatime,si=480afc1b16b1c8de,dio,dirper
m1)
nsfs on /var/run/docker/netns/065af84dff7f type nsfs (rw)
shm on /mnt/sda1/var/lib/docker/containers/04a8611b6bf3471e914800b785c8623262c66
d85d1c2573bc4fa79fdc62f8e7a/shm type tmpfs (rw,nosuid,nodev,noexec,relatime,size
=65536k)
nsfs on /var/run/docker/netns/317fb24f5682 type nsfs (rw)
none on /mnt/sda1/var/lib/docker/aufs/mnt/320e00a09414dc5ade48013b2391f566d96ece
95c45deda7b728164241a1269b type aufs (rw,relatime,si=480afc1b027538de,dio,dirper
m1)
shm on /mnt/sda1/var/lib/docker/containers/d1d727fb6eb59f3ebd9f4839ab93e47e82327
ca992fe155b72914f974fab9638/shm type tmpfs (rw,nosuid,nodev,noexec,relatime,size
=65536k)
none on /mnt/sda1/var/lib/docker/aufs/mnt/d6049dec69d727d777fb172c6f33af0789f915
fec186615f20a9f8464946fab6 type aufs (rw,relatime,si=480afc1b00eed8de,dio,dirper
m1)
nsfs on /var/run/docker/netns/ff6da6945ca8 type nsfs (rw)
shm on /mnt/sda1/var/lib/docker/containers/74f3b80479f2264b3b54ed26f931152de43b8
ae03167a93b783253bc8d17e416/shm type tmpfs (rw,nosuid,nodev,noexec,relatime,size
=65536k)
none on /mnt/sda1/var/lib/docker/aufs/mnt/cbbb000d7aeaee8ceda59f7d19d3db9ebea040
9cc43f3230c17159a98d210db9 type aufs (rw,relatime,si=480afc1b369558de,dio,dirper
m1)
shm on /mnt/sda1/var/lib/docker/containers/a11ce302b3689e0ea0e7441188c6104c8a8e2
1fd36d62c4899ef4a6ca796677e/shm type tmpfs (rw,nosuid,nodev,noexec,relatime,size
=65536k)
nsfs on /var/run/docker/netns/7d7de9017cf6 type nsfs (rw)
nsfs on /var/run/docker/netns/e216b8a56d05 type nsfs (rw)
  ```

</details>

**Comment by lmakarov** [comment] 2017-05-25 18:28
@drubage I do not see the `NFS EXPORTS` section in your `fin sysinfo` output.

This is most likely a dupe of #226.

**Comment by lmakarov** [comment] 2017-05-25 18:30
I take it back... You are on Windows, not Mac.

So this is a followup to #117

**Comment by lmakarov** [comment] 2017-05-25 18:32
@drubage please provide the output of `fin vm restart` and/or `fin vm mount`

**Comment by drubage** [comment] 2017-05-25 18:54
Well since it's already mounted the restart says:

```
Starting "docksal"...
(docksal) Check network to re-create if needed...
(docksal) Waiting for an IP...
Machine "docksal" was started.
Waiting for SSH to be available...
Detecting the provisioner...
Started machines may have new IP addresses. You may need to re-run the `docker-machine env` command.
Configuring SMB shares...
Enter your Windows account password:
mount: mounting //192.168.64.1/docksal-c on /c failed: Operation now in progress
exit status 255
Mount command failed... Trying an alternative method...
mount: mounting //192.168.64.1/docksal-c on /c failed: Operation now in progress
exit status 255
 ERROR:  SMB share mount failed.
         Make sure your Windows password is correct and run fin vm restart to try again.
```

And the mount says:

```
Configuring SMB shares...
Enter your Windows account password:
mount: mounting //192.168.64.1/docksal-c on /c failed: Operation now in progress
exit status 255
Mount command failed... Trying an alternative method...
mount: mounting //192.168.64.1/docksal-c on /c failed: Operation now in progress
exit status 255
 ERROR:  SMB share mount failed.
         Make sure your Windows password is correct and run fin vm restart to try again.

```

**Comment by lmakarov** [comment] 2017-05-25 19:02
Yeah, we are seeing this across the board with Windows. So far it's unclear whether the Docksal update is causing it or some Windows update that happened around the same time. We were not able to reproduce this on a clean Windows 10 instance with the latest Docksal release (Docksal 1.3.0 / fin 1.9.0). Also, rolling back to the previous Docksal release does not change the situation.

@drubage please join the discussion in #117 and try the steps I mentioned in the last two comments.
We are also putting together a troubleshooting guide for these issues:  #229

I'm closing this as a dupe.

**Closed by lmakarov** 2017-05-25 19:02 UTC

**Comment by achekulaev** [comment] 2017-05-25 23:41
The guide https://github.com/docksal/docksal/blob/develop/docs/troubleshooting-smb.md
