### ISSUE TITLE
The virtual machine 'docksal' has terminated unexpectedly during startup

### ISSUE THREAD

**Issue by suvasishmanna** [docksal/docksal#455] opened 2018-01-22 20:49 UTC
**Description**

At the time of installing Docksal in Mac, I'm getting the below mentioned error at the time of '_fin vm start_' 

**Steps to reproduce the issue:**

1. Installed Docksal using '_curl -fsSL https://get.docksal.io | sh_' in Mac (IOS v10.13.2)
2. Starting virtual machine using '_fin vm start_'

**Describe the results you received:**

```
$ fin vm start
Creating docker machine 'docksal'...
Running pre-create checks...
Creating machine...
(docksal) Downloading /Users/a367758/.docker/machine/cache/boot2docker.iso from https://github.com/boot2docker/boot2docker/releases/download/v17.09.0-ce/boot2docker.iso...
(docksal) 0%....10%....20%....30%....40%....50%....60%....70%....80%....90%....100%
(docksal) Creating VirtualBox VM...
(docksal) Creating SSH key...
(docksal) Starting the VM...
(docksal) Check network to re-create if needed...
(docksal) Found a new host-only adapter: "vboxnet0"
Error creating machine: Error in driver during machine creation: Unable to start the VM: /usr/local/bin/VBoxManage startvm docksal --type headless failed:
VBoxManage: error: The virtual machine 'docksal' has terminated unexpectedly during startup with exit code 1 (0x1)
VBoxManage: error: Details: code NS_ERROR_FAILURE (0x80004005), component MachineWrap, interface IMachine

 ERROR:  Proper creation of virtual machine has failed
         For details please refer to the log above.
         It is recommended to remove malfunctioned virtual machine.
Remove docksal? [y/n]: Y
```

**Output of `fin sysinfo`:**

<details>
  <summary>fin sysinfo output</summary>

  ```
  ███  OS
Mac OS X 10.13.2
Darwin 02HW030947.local 17.3.0 Darwin Kernel Version 17.3.0: Thu Nov  9 18:09:22 PST 2017; root:xnu-4570.31.3~1/RELEASE_X86_64 x86_64
Mode: VirtualBox VM

███  FIN
fin version: 1.43.2

███  ENVIRONMENT
DOCKER_HOST		| 
 WARNING:  Non-default DOCKER_HOST
------------------------------------------------------------
DOCKSAL_NFS_PATH	| 

███  DOCKER
EXPECTED VERSION: 17.09.0-ce

Client:
 Version:      17.09.0-ce
 API version:  1.32
 Go version:   go1.8.3
 Git commit:   afdb6d4
 Built:        Tue Sep 26 22:40:09 2017
 OS/Arch:      darwin/amd64
Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?

███  DOCKER INFO
Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
███  DOCKER COMPOSE
EXPECTED VERSION: 1.17.1
docker-compose version 1.17.1, build 6d101fb
docker-py version: 2.5.1
CPython version: 2.7.12
OpenSSL version: OpenSSL 1.0.2j  26 Sep 2016

███  DOCKER MACHINE
EXPECTED VERSION: 0.13.0
docker-machine version 0.13.0, build 9ba6da9

NAME   ACTIVE   DRIVER   STATE   URL   SWARM   DOCKER   ERRORS

███  VIRTUALBOX
EXPECTED VERSION: 5.1.28
5.1.28r117968

███  VIRTUALBOX NETWORK INTERFACES
███  NFS EXPORTS


███  HDD Usage
Docker machine docksal is not created. Use 'fin vm start' or 'fin up'.

███  RAM Usage
Docker machine docksal is not created. Use 'fin vm start' or 'fin up'.

███  RAM Usage per container
Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
  ```

</details>

**Comment by lmakarov** [comment] 2018-01-22 23:15
@suvasishmanna I found [this](https://github.com/hashicorp/vagrant/issues/8687#issuecomment-339014825) while googling for `VBoxManage: error: Details: code NS_ERROR_FAILURE (0x80004005), component MachineWrap, interface IMachine`

Try rebooting, then run the do `fin vm start` again to create the Docksal VM.

If you are still having this issue and this is the first time you are installing Docksal/VirtualBox on your Mac, then it's most likely a dupe of #417.

**Comment by suvasishmanna** [comment] 2018-01-23 17:38
@lmakarov I have tried rebooting multiple times with no luck. Similar error message is still coming. 

```
$ fin vm start
Starting "docksal"...
(docksal) Check network to re-create if needed...
Unable to start the VM: /usr/local/bin/VBoxManage startvm docksal --type headless failed:
VBoxManage: error: The virtual machine 'docksal' has terminated unexpectedly during startup with exit code 1 (0x1)
VBoxManage: error: Details: code NS_ERROR_FAILURE (0x80004005), component MachineWrap, interface IMachine
 ERROR:  Failed starting virtual machine
```

I had an earlier instance of Docksal which was working properly with native Docker application. This time I removed both of them and trying to reinstall with VirtualBox

**Comment by achekulaev** [comment] 2018-01-23 18:51
You use High Sierra. Have you loaded kernel extension after installing Virtualbox?
https://github.com/docksal/docksal/issues/417

On Mac I would recommend using Docker for Mac
https://docs.docksal.io/en/master/getting-started/env-setup-native/#using-native-docker-applications

**Comment by suvasishmanna** [comment] 2018-01-24 19:55
@achekulaev I am not getting the "Blocked kernel extension" message to manually approve and load KEXT. The virtual machine is getting created but at the time of starting the VM it is getting stuck with the unexpected error message. I will try to setup with Docker if this issue with VirtualBox is not getting resolved.

<img width="1352" alt="screen shot 2018-01-24 at 2 12 34 pm" src="https://user-images.githubusercontent.com/7619591/35352273-6e54d764-0111-11e8-8a86-1d6da43e3590.png">

**Comment by achekulaev** [comment] 2018-01-24 20:58
@suvasishmanna 
Look here https://github.com/hashicorp/vagrant/issues/8687

Make sure you have enough RAM to fit the virtual machine.
Make sure you have enough disk drive space.

Try restarting your host machine. 
If that does not help try that `sudo /sbin/vboxconfig`

If nothing helps as a fallback scenario I would recommend using Docker for Mac. 
Just download the 17.09 one https://download.docker.com/mac/stable/19611/Docker.dmg
Install it and start application (it will site in the menu tray). 
Add a line `DOCKER_NATIVE=1` to `$HOME/.docksal/docksal.env` file and you should be good to go.
You will not need VirtualBox on that case.

**Comment by suvasishmanna** [comment] 2018-01-29 15:52
Yes using Docker its working properly without any issue

**Comment by achekulaev** [comment] 2018-01-29 16:25
Feel free to close the issue if it is resolved.

**Closed** 2018-01-31 19:58 UTC
Labels: question
