### ISSUE TITLE
docksal-sda1 mount fails on WSL, fin version 1.85.1

### ISSUE THREAD

**Issue by MikeGodin** [docksal/docksal#1060] opened 2019-05-13 19:05 UTC
**Description**

Fin installation attempts to mount a "special device" called "docksal-sda1" and fails.  The troubleshooting instructions at https://docs.docksal.io/troubleshooting/windows-smb/ only mention the smb mounts "docksal-c" and "docksal-d" (which are being created and mounting without issue), but does not mention "docksal-sda1".  I would create it manually if I knew what directory it was supposed to share.

**Steps to reproduce the issue:**

1. `bash <(curl -fsSL https://get.docksal.io)`
2. enter WSL password
3. enter Windows password

**Describe the results you received:**

```
...[Lines omitted]

Configuring SMB shares...
Enter your Windows account password:
Adding docker SMB share docksal-c...

Adding docker SMB share docksal-d...


Adding docker SMB share docksal-sda1...
mount: special device //192.168.64.1/docksal-sda1 does not exist

exit status 32
Mount command failed... Trying an alternative method...
mount: wrong fs type, bad option, bad superblock on //192.168.64.1/docksal-sda1,
       missing codepage or helper program, or other error
       (for several filesystems (e.g. nfs, cifs) you might
       need a /sbin/mount.<type> helper program)

       In some cases useful info is found in syslog - try
       dmesg | tail or so.

exit status 32
 ERROR:  SMB share mount failed.
         Make sure your Windows password is correct and run fin vm mount to try again.
         For troubleshooting instructions see https://docs.docksal.io/troubleshooting/windows-smb/
```

**Describe the results you expected:**

Did not expect to see: `mount: special device //192.168.64.1/docksal-sda1 does not exist`

**Output of `fin config`:**

<details>
  <summary>fin config output</summary>

```
N/A - this occurs during docksal installation
```

</details>

<br>

**Output of `fin sysinfo`:**

<details>
  <summary>fin sysinfo output</summary>

  ```
███  OS
WSL Ubuntu 18.04
Linux Goldie 4.4.0-17134-Microsoft #706-Microsoft Mon Apr 01 18:13:00 PST 2019 x86_64 x86_64 x86_64 GNU/Linux

███  ENVIRONMENT
MODE : VirtualBox VM
DOCKER_HOST : tcp://192.168.64.101:2376

███  FIN
fin version: 1.85.1

███  DOCKER COMPOSE
EXPECTED VERSION: 1.23.2
docker-compose version 1.23.2, build 1110ad01
docker-py version: 3.6.0
CPython version: 3.6.7
OpenSSL version: OpenSSL 1.1.0f  25 May 2017

███  DOCKER
EXPECTED VERSION: 18.09.2

Client: Docker Engine - Community
 Version:           18.09.2
 API version:       1.39
 Go version:        go1.10.8
 Git commit:        6247962
 Built:             Sun Feb 10 04:11:47 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.2
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.6
  Git commit:       6247962
  Built:            Sun Feb 10 04:20:28 2019
  OS/Arch:          linux/amd64
  Experimental:     false

███  DOCKER MACHINE
EXPECTED VERSION: 0.16.1
docker-machine.exe version 0.16.1, build cce350d7

NAME      ACTIVE   DRIVER       STATE     URL                         SWARM   DOCKER     ERRORS
default   -        virtualbox   Error                                         Unknown    machine does not exist
docksal   -        virtualbox   Running   tcp://192.168.64.101:2376           v18.09.2

███  DOCKSAL: PROJECTS
project             STATUS              virtual host        project root

███  DOCKSAL: VIRTUAL HOSTS
Error response from daemon: Container 2f7c6856b938fdf56f31a150ff6ecab927c0f09f1d2fc5262f7c4b15f980a589 is not running
No virtual hosts found

███  DOCKSAL: DNS
curl: (6) Could not resolve host: dns-test.docksal
ERROR: Requesting http://dns-test.docksal failed!

███  DOCKER: RUNNING CONTAINERS
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES

███  DOCKER: NETWORKS
NETWORK ID          NAME                DRIVER              SCOPE
15fd4564460e        bridge              bridge              local
eca9d4271448        host                host                local
b165d7eeeac3        none                null                local

███  VIRTUALBOX
EXPECTED VERSION: 5.2.26
5.2.26r128414

███  DOCKSAL MOUNTS
//192.168.64.1/docksal-c on /c type cifs (rw,relatime,vers=3.02,sec=ntlmssp,cache=strict,username=mikeg,domain=GOLDIE,uid=0,noforceuid,gid=0,noforcegid,addr=192.168.64.1,file_mode=0777,dir_mode=0777,soft,nounix,serverino,mapposix,nobrl,mfsymlinks,noperm,rsize=1048576,wsize=1048576,echo_interval=60,actimeo=1)
//192.168.64.1/docksal-d on /d type cifs (rw,relatime,vers=3.02,sec=ntlmssp,cache=strict,username=mikeg,domain=GOLDIE,uid=0,noforceuid,gid=0,noforcegid,addr=192.168.64.1,file_mode=0777,dir_mode=0777,soft,nounix,serverino,mapposix,nobrl,mfsymlinks,noperm,rsize=1048576,wsize=1048576,echo_interval=60,actimeo=1)


███  HDD Usage

Filesystem                Size      Used Available Use% Mounted on
/dev/sda1                46.1G    234.7M     43.5G   1% /mnt/sda1
  ```

</details>

**Comment by lmakarov** [comment] 2019-05-13 19:19
This is likely a dupe of https://github.com/docksal/docksal/issues/1059.

In WSL do: `ls -la /mnt/` and `ls -la /mnt/sda1`.

You will likely have `/mnt/sda1` there and it will be empty.
For now, you can simply delete `/mnt/sda1` and do `fin system reset`.

**Comment by lmakarov** [comment] 2019-06-01 01:05
Closing in favor of #1059

**Closed by lmakarov** 2019-06-01 01:05 UTC
Labels: duplicate, pending
